### ISSUE TITLE
Video Module Doesn't Push Winning Bids to Auction Winning Bids State

### ISSUE THREAD

**Issue by fowler446** [prebid/Prebid.js#10008]
## Type of issue
Bug

## Description
The Prebid video module doesn't add winning bids to the `_winningBids` state of an auction. This is because the `pbjsRenderAd` function doesn't run when a video ad unit plays:
https://github.com/prebid/Prebid.js/blob/master/src/prebid.js#L528

## Steps to reproduce
Implement the video module on a test page and have some bids win the auction and play. Then type `pbjs.getAllWinningBids()` and notice how it's empty.

**Comment by dgirardi** [comment]
I am wondering if this is limited to the video module, or if it's a problem for video in general. The video module calls `markWinningBidAsUsed` when it knows a bid has been rendered, which is the [same flow](https://docs.prebid.org/dev-docs/publisher-api-reference/markWinningBidAsUsed.html) used before the video module was introduced.

However, that seems to only mark the bid as "rendered", and not as winning, and I don't know why - it seems to have been like this since the [beginning](https://github.com/prebid/Prebid.js/pull/2777). Paging @mkendall07 for the slim chance of some context.

**Comment by karimMourra** [comment]
I had already fixed this in https://github.com/prebid/Prebid.js/pull/9612/files but it seems like my changes were deleted. the git blame for that line indicates a commit from 2018.

**Comment by karimMourra** [comment]
@dgirardi i do think this fix should work. i am concerned though that other fixes might have been lost when #9612 was undone

**Comment by dgirardi** [comment]
I am also confused by your commit. With some digging it looks like it was erased with a heavy handed [conflict merge](https://github.com/prebid/Prebid.js/commit/40cdc5e2e5150304ae0107d868ae03e1fa9940e7). Do you see anything else in there that may also be broken?

**Comment by karimMourra** [comment]
I don't see anything else that looks broken in the conflict merge.
