### ISSUE TITLE
Change meta object ID fields (e.g. networkId) type from int to string

### ISSUE THREAD

**Issue by maxime-dupuis** [prebid/Prebid.js#10060]
## Type of issue

Feature request

## Description

The `bidResponse.meta` ID fields are currently of type `int`. [Prebid.js Release 4.0](https://prebid.org/blog/prebid-js-release-4-0/), [bidResponse reference](https://docs.prebid.org/dev-docs/bidder-adaptor.html#interpreting-the-response).
In our exchange we represent Network ID's (or DSP ID's) as a `string`, so it would be more convenient for us if this field was a string. It would also open more options like using UUID's.

### Expected results

meta ID fields are of type `string`

### Actual results

meta ID fields are of type `int`

## Platform details
Prebid.js version 4+

**Comment by dgirardi** [comment]
I don't think the type matters (or is defined) for most things in `meta`. You should be able to set for example `meta.networkId` as a string since nothing in our codebase expects it to be otherwise. I'd argue the documentation is also not explicit about types so in theory other integrations should be able to handle strings as well.

**Comment by maxime-dupuis** [comment]
@dgirardi Thank you I'll give it a shot and tell you if it works

**Comment by krjackso** [comment]
> I don't think the type matters (or is defined) for most things in `meta`. You should be able to set for example `meta.networkId` as a string since nothing in our codebase expects it to be otherwise. I'd argue the documentation is also not explicit about types so in theory other integrations should be able to handle strings as well.

@dgirardi I think this issue was in reference to [this blog post](https://prebid.org/blog/prebid-js-release-4-0/). Also the documentation examples do show them all as numbers. I think explicitly switching these to strings would completely remove the ambiguity

![image](https://github.com/prebid/Prebid.js/assets/2296020/8b8e0ed5-7b52-493f-86bb-db6b49ae9c28)
![image](https://github.com/prebid/Prebid.js/assets/2296020/3d191590-4bf1-4f60-a271-2926e45a6952)
