### ISSUE TITLE
ConsentManagement Bug Report: api locator fails when prebid is loaded in a safeframe

### ISSUE THREAD

**Issue by fasenderos** [prebid/Prebid.js#10120]
I would like to suggests two changes to the `ConsentManagement` module.

1) If Prebid is loaded inside a SafeFrame, after some iterations it silently fails with the error `Cannot read property 'parent' of undefined (reading f)`. So i suggests to change the line 72 with `if (f === window.top || f === undefined) break;` 
https://github.com/prebid/Prebid.js/blob/a35cda0896d9223ac2f0f6c90e201593b30851e3/modules/consentManagement.js#L72-L73

**Comment by patmmccann** [comment]
Please open (2) as a second issue for tracking and discussion

**Comment by dgirardi** [comment]
Is it fair to sum up the issue as "consentManagement stops auctions when a CMP is not available"? (even after your point 1 you'd still get no auction).
If you know in advance whether you're supposed to find one, you could work around this by only enabling consent management when it's appropriate. Otherwise, no objections to a PR.

**Comment by patmmccann** [comment]
One additional note: safeframe communication may have intentionally been removed by the IAB

https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/0f2e4a9552c670fac158618afa81046dee680e91/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md?plain=1#L1058
