### ISSUE TITLE
Have valid bids but no winning bid

### ISSUE THREAD

**Issue by sfai05** [prebid/Prebid.js#1017]
## Type of issue
Bug ?

## Description
![untitled 2](https://cloud.githubusercontent.com/assets/1597348/23451458/f3b08ff4-fe9a-11e6-8583-6681d7812c0c.png)

I found some cases that even the slot have some valid bids ( have response before timeout ) the systems did not pick any of them as winning bids.
And theres some cases that not always the bid with highest CPM wins.

Whats the algorithm behind picking the winning bids ?

**Comment by mkendall07** [comment]
The "no prebid winners" isn't really accurate. ( @rmloveland we should update our JS snippets to say "no prebid demand was picked to display" or similar).

This means that while there was prebid demand, ultimately the ad server decided not to display the prebid ad because there was something else that won. 

Now if no other ad showed, or the prebid line item was picked, then there is a problem.

**Comment by headerbidding** [comment]
How can I get a report like the one pictured in the original post?

**Comment by mkendall07** [comment]
http://prebid.org/dev-docs/toubleshooting-tips.html#see-all-bids-in-the-console

**Comment by sfai05** [comment]
@mkendall07 Thanks for the reply. So "winning bids" only means the ads rendered with prebid lineitems.

And one more thing I would like to confirm, is prebid library are always use the highest bid price as dfp targeting ?

**Comment by mkendall07** [comment]
@sfai05 correct.

Default behavior is to use the highest CPM bid for DFP targeting. You can also send all the bids received via http://prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.enableSendAllBids

**Comment by sfai05** [comment]
Thanks 👍
