### ISSUE TITLE
Hello world and postbid examples not working anymore

### ISSUE THREAD

**Issue by espen-j** [prebid/Prebid.js#10260]
## Type of issue
All of a sudden our demo projects start failing with newer versions of prebid.

Error in console happens here:
``` 
Uncaught TypeError: index.getAdUnit(...) is undefined
    getPreparedBidForAuction auction.js:716
    acceptBidResponse auction.js:478
    handleBidResponse auction.js:473
    acceptBidResponse auction.js:477
    addBidResponse auction.js:417
```

Affected Code snippet:
```

/**
 * Add additional bid response properties that are universal for all _accepted_ bids.
 */
function getPreparedBidForAuction(bid, {index = auctionManager.index} = {}) {
  // Let listeners know that now is the time to adjust the bid, if they want to.
  //
  // CAREFUL: Publishers rely on certain bid properties to be available (like cpm),
  // but others to not be set yet (like priceStrings). See #1372 and #1389.
  events.emit(CONSTANTS.EVENTS.BID_ADJUSTMENT, bid);

  // a publisher-defined renderer can be used to render bids
  const bidRenderer = index.getBidRequest(bid)?.renderer || index.getAdUnit(bid).renderer;
```

## Description

We have a demo setup based on the [hello-world example](https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/hello_world.html).
That has been working nicely throughout the 7 releases, but is now borked since updating to latest prebid versions.

The bundle we serve on the demo page is created with the follwoing command:
`gulp build-bundle-dev --modules=consentManagement,gdprEnforcement,cwireBidAdapter,prebidServerBidAdapter`

## Test page
[Internal testing site](https://creatives-testing.cwi.re/prebid/?cwcreative=3221)

Also tested with postbid after reading this:
https://stackoverflow.com/questions/72854153/prebid-js-ad-is-not-getting-rendered

But it fails on the same line of code.

**Comment by dgirardi** [comment]
I deduce from the page URL that you are affiliated with cwire?

The issue is that the cwire bid adapter sets `transactionId` on bid responses, carrying it over from the request. With version 8 transactionId (and auctionId) are disabled by default, so they are being overridden with empty values. We did [go through all adapters](https://github.com/prebid/Prebid.js/pull/9969) to check for this pattern, but unfortunately missed cwire since it's doing it server-side.

I'll have a PR shortly to disregard `transactionId` / `auctionId`  from adapter responses (I actually thought we were already discarding them - they are not supposed to be set by adapters).

**Comment by dgirardi** [comment]
Good point on the docs - they should mention that they can both be null since version 8. They do have corresponding fields in ortb2 [reference](https://docs.prebid.org/dev-docs/pb8-notes.html#transaction-identifiers-are-now-reliable-and-opt-in), but it's not an alternative - unless the publisher opts in, those will also be missing.

You are still free to use them server-side, with the caveat that they are no longer always defined. On responses I recommend not setting them - that would fix the issue for everyone using version 8.0 up until the next release (where I hope to get my PR in).

**Comment by espen-j** [comment]
I'll remove them from the response as well. 

I'll have to check in with some team mates to see what consequences that change has. `transactionId` and `auctionId` are carrying information that we otherwise won't have AFAIK.

Again, thanks for your time and responsiveness, always a pleasure!

**Comment by patmmccann** [comment]
transactionId and auctionId are carrying information that you would not otherwise know; they are optional in the openrtb spec and the publishers in the project have elected this option to be theirs. If they don't share it, there is no alternative. You should not make up id's in their place to send to DSPs or you may be risking blacklistng by said DSPs

**Comment by espen-j** [comment]
Thanks, updated to latest version and the our test setup is working again. 👍
