### ISSUE TITLE
can rtdModule generate auction timeouts 

### ISSUE THREAD

**Issue by matthieularere-msq** [prebid/Prebid.js#10320]
## Type of issue
Question

## Description
The use of `getBidRequestData` in a rtd module happens with a raise of timeouts for a publisher.
When active, the publisher sees more timeout in its analytics tools. We tried with an almost empty rtd module and the behavior persists. I haven't been able to see the timeouts myself, it's a claim for the analytic tool which relies on the `BID_TIMEOUT` event

I've checked in `modules/rtdModule/index.js` and searched in `src/prebid.js` and `src/auction.js` to understand how the rtd modules are launched and check if somehow its run time could be counted in the delay given to bidders to send their responses but I did not find any evidence of that. To me the rtd module should behave has expected, delaying the start of auctions and so the simple fact of activating it should not be able to produce timeouts for bidders. 

My question is : do you see any way for a rtd module to make bidders generate more timeouts ?

Thanks

## Steps to reproduce
Here is a rtdModule which happens to generate more timeouts according to the publisher.
```
import { submodule } from '../src/hook.js'
import { logInfo } from '../src/utils.js'

const LOG_PREFIX = 'testRtdProvider submodule: ';

export const testSubmodule = {
  name: 'testRtd',
  init: init,
  getBidRequestData: getBidRequestData,
};

function init(config, userConsent) {
  return true;
}

function getBidRequestData(reqBidsConfigObj, callback, config, userConsent) {
  logInfo(LOG_PREFIX + 'started.');
  callback();
}


submodule('realTimeData', testSubmodule);
```

**Comment by dgirardi** [comment]
RTD modules shouldn't increase timeouts, and especially with the example you gave I don't see how it could. Can we get some more information - prebid version and installed modules? Or a link to a page where with this behavior, even if it doesn't include an RTD module?

**Comment by matthieularere-msq** [comment]
You can see the test integration here : https://www.lepoint.fr/?hbv-prv=true#hbv-beta&hbv-pbjs
The publisher made a test on another website where they had another rtd module installed for months : they removed it and the timeout rates dropped.

**Comment by GLStephen** [comment]
Just spit balling a bit, but is it possible that the whole auction is timing out more somehow? @dgirardi this is good bidder level timeout analysis, but how does the global timer effect bidder level reporting to analytics?

**Comment by patmmccann** [comment]
Are you referring to https://github.com/prebid/Prebid.js/blob/master/modules/oxxionRtdProvider.js ? Are Oxxion and hubvisor the same company?

**Comment by manfriedn64** [comment]
Hi @patmmccann 
That's the module we want to get implemented on this publisher yes, however the hubvisors stats show a considerable increase in timeout when it's installed in their wrapper. Because it made no sense, I've sent hubvisor the almost empty module from my initial post and the same timeout increase happened.
With another publisher hubvisor has another rtd module installed for years, so they made a test to remove it and it lowered the timeout rate. 

My assumptions are that either prebid rtd module increase timeouts for an unexpected reason or hubvisor count on timeouts are somehow wrong and rtd module interfere with them. I can not prove the latest so I am turning towards you to sure if the first assumption can be true.

poke @JulieLorin from hubvisor has she might be able to give details from what happens on her side.

Oxxion and Hubvisor are not the same company.

**Comment by manfriedn64** [comment]
> 2\. RTD modules could conceivably modify `timeToRespond` on bid responses, or modify bid requests on the initial auction configuration in a way that triggers false positives in the "late" detection logic. These would be issues specific to particular RTD modules, not RTD in general.

Hi @dgirardi 
My module's listen to the `getBidRequestData` event in order in order to filter the bidders plugged in adunits. Could this trigger false positives you are talking about for the bidders which are removed from it ?

**Comment by matthieularere-msq** [comment]
Redoing my responses with my pro github account ^^

Hi @patmmccann
That's the module we want to get implemented on this publisher yes, however the hubvisors stats show a considerable increase in timeout when it's installed in their wrapper. Because it made no sense, I've sent hubvisor the almost empty module from my initial post and the same timeout increase happened.
With another publisher hubvisor has another rtd module installed for years, so they made a test to remove it and it lowered the timeout rate.

My assumptions are that either prebid rtd module increase timeouts for an unexpected reason or hubvisor count on timeouts are somehow wrong and rtd module interfere with them. I can not prove the latest so I am turning towards you to sure if the first assumption can be true.

poke @JulieLorin from hubvisor has she might be able to give details from what happens on her side.

Oxxion and Hubvisor are not the same company.

> 2\. RTD modules could conceivably modify `timeToRespond` on bid responses, or modify bid requests on the initial auction configuration in a way that triggers false positives in the "late" detection logic. These would be issues specific to particular RTD modules, not RTD in general.

Hi @dgirardi
My module's listen to the getBidRequestData event in order in order to filter the bidders plugged in adunits. Could this trigger false positives you are talking about for the bidders which are removed from it ?

**Comment by JulieLorin** [comment]
Hi, 
I have been trying to debug this issue, using a RTD module with an "empty" `getBidRequestData` function (just calls the callback) : 
- I could not confirm if we are counting timeouts correctly but I could not find any reason why not (we are based on prebid BID_TIMEOUT event)
- I found a difference in the auction flow with RTD module enabled, and I am not sure if this can have side effect on the auction : 

I am testing on an outdated version of Prebid (7.48), but we see the same increase in more recent versions of prebid. 
In the RTD hook function, when there is an enabled module, the callback (which trigger startAuction) is called asynchronously. 
I tried to make it synchronous (just for testing, I know it's not valid code, but it works for the single rtd module I was testing) : 
![image](https://github.com/prebid/Prebid.js/assets/635021/f7f70520-08ed-4c45-a6de-4b61982a8110)
Removing asynchronous behavior do not trigger more timeouts. 

I tried to dig a bit deeper and found that it changes the "order" when calling startAuction. I added some logs (file prebid.js) : 
![image](https://github.com/prebid/Prebid.js/assets/635021/032468d0-615b-4c48-9f64-9cd54ba614a5)

With the synchrone behavior, logs are in this order : 
![image](https://github.com/prebid/Prebid.js/assets/635021/f4650657-0a17-4f99-bee9-906cc2600485)
... Later
![image](https://github.com/prebid/Prebid.js/assets/635021/d341db11-bf93-40e9-af4f-7878098e1db7)
=> The startAuction promise is resolved at the end (`DEBUG FINISHED AUCTION HERE?`)

When I change RTD Module to call exitHook asynchronously in the onGetBidRequestDataCallback function (with the setTimeout, I just switched with the commented line), the order is different : 
![image](https://github.com/prebid/Prebid.js/assets/635021/6f131c27-d888-436f-8242-b927f6e38f84)
The log `DEBUG FINISHED AUCTION HERE?` is now just after RTD callback is called which means the startAuction promise resolves much earlier (and not at the end of the auction). 

From what I understand, as the hook is wrapped, the fact that it resolves earlier should not have side effect when calling the function, but would it be possible that it could affect other things based on the `requestBids` hook directly (not the wrapped version) as it changes the moment it is "resolved" ? Or on the `startAuction` hook ? (I didn't find anythign obvious (yet?) but as I am not familiar enough with Prebid, maybe something else has an idea ? )

I am available if you need a live demo of this or any other information (here or on Slack)
I will keep looking as my planning allows it

**Comment by dgirardi** [comment]
@JulieLorin I think this is similar to https://github.com/prebid/Prebid.js/issues/9709 and https://github.com/prebid/Prebid.js/issues/8770 . In all 3 cases the common thread is that introducing an asynchronous "break" in `requestBids` increases timeouts; I think another commonality is that it affected hubvisor without yet confirmation that it also affects Prebid in general  (correct?). I'm wondering if that's a problem in what hubvisor does - the different order of execution could throw it off, but it's hard for me to guess how or why, since I am not familiar with it. Is it using the hook system to add custom logic in the `requestBids` chain?

Within Prebid, I am not able to spot how asyncronicity could cause this problem. The auction timeout, as well as the recording of `requestTimestamp`, starts after you put the `DEBUG START AUCTION TIMER`  message, and from that point on the order does not change. I've done some testing simulating timeouts using the debugging module:

```
            pbjs.setConfig({
                bidderTimeout: 100,
                debugging: {
                    enabled: true,
                    intercept: [
                        {
                            when: {},
                            then: {
                                ad: 'test'
                            },
                            options: {
                                delay: 90
                            }
                        }
                    ]
                },
```

tweaking the value of `delay` to get it to produce mostly timeouts or mostly successful bids, the behavior does not change when I introduce an RTD module (which is what I expected by looking at our timeout logic). Does it produce a difference if you introduce hubvisor?

**Comment by dgirardi** [comment]
Expanding on the simulated timeouts test. With this:

```javascript
pbjs.que.push(function () {
    pbjs.setConfig({
        bidderTimeout: 20,
        debugging: {
            enabled: true,
            intercept: [
                {
                    when: {},
                    then: {
                        ad: 'test'
                    },
                    options: {
                        delay: 17
                    }
                }
            ]
        },
        realTimeData: {
            auctionDelay: 10, // lower in real scenario to meet publisher spec
            dataProviders: [
                {
                    name: 'testRtd',
                    waitForIt: false,
                }
            ]
        }
    });
    pbjs.addAdUnits(adUnits);

    const intv = setInterval((() => {
        let i = 0;
        let tm = 0;
        return function () {
            if (i >= 100) {
                clearInterval(intv);
                console.log('TIMEOUTS: ', tm);
                return;
            }
            i++;
            pbjs.requestBids({
                bidsBackHandler: function () {
                },
            }).then(res => {
                console.log('RESULT', res);
                if (res.timedOut) {
                    tm += 1;
                }
            });

        };
    })(), 40);

});
```

the difference of 3ms between `bidderTimeout` and `delay` is what on my system produces almost no timeouts (on a run of 100 auctions, between 0 and 1 will time out). This does not change if I include or exclude the dummy RTD module (from the OP), by doing

```
gulp serve-fast --modules appnexusBidAdapter
```

versus 

```
gulp serve-fast --modules testRtdModule,rtdModule,appnexusBidAdapter
```

and also does not change if I set `waitForIt: true`.

**Comment by patmmccann** [comment]
@JulieLorin and @matthieularere-msq could you take a look at https://github.com/prebid/Prebid.js/pull/10779 ? It may solve and it may be that the increases in timeouts you saw were an increase in reported timeouts where total timeouts was static but underreported prior to 10779.

**Comment by JulieLorin** [comment]
@patmmccann I tried to deploy the updates from #10779 (along with prebid.js 8.30.0)
![image](https://github.com/prebid/Prebid.js/assets/635021/2b7cd514-ba2f-467a-8c19-835cbef13b09)
I disabled oxxion rtd module between 14:40 and 15:05 (the drop in timeout that we can see) - I wanted to check if the timeout increase with RTD module was still present with "latest" version of Prebid.
I deployed the updates from #10779 between 15:20 and 16:30 and there are no changes (so still higher timeouts)

Last comment from dgirardi about this issue was very interesting and I think he is completely right but I haven't been able to investigate more about this (and decided it was ok as there was no impact on other metrics)

Thank you for the ping !

**Comment by patmmccann** [comment]
@JulieLorin  Perhaps deploy #10779 then disable oxxion and see if the rate remains stable? 10779 might have the effect that the disabling the rtd module would have a stable rate reported.

**Comment by dgirardi** [comment]
Something peculiar about the increase in timeout related to #10779 is that it was unevenly distributed across browsers - IIRC there was a marked difference between Chrome Desktop and other browsers. If you are able to break down your data by browser, that may suggest whether it's likely to be the same issue.

**Comment by JulieLorin** [comment]
I have deployed prebid.js 8.33.0 (which contains #10779) with oxxion RTD module enabled. 
I then deployed the same version with oxxion RTD module disabled
I can still see a change in timeout rate (timeout rate is lower when oxxion RTD is disabled) : 
![image](https://github.com/prebid/Prebid.js/assets/635021/b06042e8-86ed-4023-9393-8c6632f239ba)
But I don't see any difference between browser : 
![image](https://github.com/prebid/Prebid.js/assets/635021/905b0385-9bea-4407-97b3-1cbeaec042b1)

(This issue is not a priority on our side so I am not actively working on it, even if I have an interesting lead that you gave me to look into when I'll have the time)

**Comment by patmmccann** [comment]
We're not sure how to proceed @JulieLorin and @matthieularere-msq , do you have any proposals or should we close, or just keep open indefinitely?

**Comment by JulieLorin** [comment]
> We're not sure how to proceed @JulieLorin and @matthieularere-msq , do you have any proposals or should we close, or just keep open indefinitely?

On my side, I think we should close (I keep the issue in my head, but even if it's closed, I'll find easily the issue if I want to look into it again)
