### ISSUE TITLE
Many 404 errors since : Sec-Browsing-Topics in 8.9

### ISSUE THREAD

**Issue by david-societe** [prebid/Prebid.js#10458]
## Type of issue
Lot of 404 errors in prebid sequence since [https://github.com/prebid/Prebid.js/pull/10340]

## Description
Prebid is trying to fetch my domain url with an object at the end (alledgally when trying to browseTopics).
-> GET https://www.dev3.societe.com/[object%20Object]
Returning a lot of 404 errors in the process

Related to this feature on 8.9 : 
  refactor ajax.js to use fetch instead of XHR
  automatically pass browsingTopics: true to fetch, for all bidder requests, when the transmitUfpd activity is allowed

No other changes in configuration 

## Platform details
PREBID > 8.8

**Comment by david-societe** [comment]
Hi,

I'm not an endpoint maintainer, just a publisher using my own wrapper.

Thx

Le lun. 11 sept. 2023 à 14:37, Patrick McCann ***@***.***> a
écrit :

**Comment by dgirardi** [comment]
Can we have a test page? Or your adapter's `buidRequest` code?

**Comment by david-societe** [comment]
you can test here here : https://www.dev3.societe.com/#debug=1

davidt
3x9Jspy3Ccp8

thx a lot

**Comment by dgirardi** [comment]
The issue is that page monkey-patches the [Request constructor](https://developer.mozilla.org/en-US/docs/Web/API/Request) with a version that does not have the same API:

![image](https://github.com/prebid/Prebid.js/assets/10151381/b386ad70-bb90-4d9a-bf38-38802bfef2e5)

and with that PR, we switched Prebid's network code from XHR to fetch & Request.

I am not sure what our options are here - is that monkey-patching necessary, and how commonly used is it?

**Comment by david-societe** [comment]
Yes. Thx again

Le lun. 11 sept. 2023 à 18:02, Patrick McCann ***@***.***> a
écrit :
