### ISSUE TITLE
How to implement Native in Adapter

### ISSUE THREAD

**Issue by QuentinGallard** [prebid/Prebid.js#10493]
## Type of issue
Question

## Description
Hi, I'm from Smilewanted and we have several questions about adding the Native Support to our Adapter.

The documentation here https://docs.prebid.org/prebid/native-implementation.html suggests to pass a Native OpenRTB 1.2 bidrequest in mediatypes.native.ortb, but every other adapters use the legacy version https://docs.prebid.org/prebid/native-implementation-legacy.html or convert the ortb request in legacy via the `convertOrtbRequestToProprietaryNative` function in `native.js`.

Is there any reason not to use the ortb method rather than the legacy method?

Is the documentation for the ortb method too recent?

What is the recommended way to implement Native in Adapters ?

**Comment by dgirardi** [comment]
The goal is to eventually move everything to ORTB, so that's what we recommend for new implementations. There are a number of adapters that do native ORTB, but all of them get it "for free" through the ortbConverter library. For example: https://github.com/prebid/Prebid.js/blob/d5744050ad93d90b47c2bceb1366deeab38b3f70/modules/a1MediaBidAdapter.js#L65

Here's the logic - but as you can see there's not much in it, since it's just passing ORTB objects back and forth:

https://github.com/prebid/Prebid.js/blob/master/libraries/ortbConverter/processors/native.js

From what I can tell Smilewanted does not talk ORTB - so you may need to do more legwork in the adapter. See also this discussion about the gaps between legacy and ORTB:

https://github.com/prebid/Prebid.js/issues/10249

**Comment by patmmccann** [comment]
closing as stale
