### ISSUE TITLE
Sequence of setting userIds doesn't work as expected.

### ISSUE THREAD

**Issue by GeneGenie** [prebid/Prebid.js#10548]
## Type of issue
Bug / question

## Description
Sequential sets of user id modules doesn't work, only first attempt gets processed. 
User Story:  3rd party identification services push their own ids through pubProvidedIdSystem, to avoid commiting new userId module. So they tend to discover pbjs instance in scope and push their ids, and this is an actual race, who will be able to pass config first: publisher, idProvider or wrapper library (in our case). 
Our case is that we are develping separate library to pass DMP identification in separate "thread" on a page, when it's ready, but it is being ignored due to wrapper already set userIds configuration

PS: i'm aware of pbjs.refreshUserIds(list?), but calling this method will invalidate stored ids, loosing linked ids is unwanted behaviour. 

## Steps to reproduce
1. check out this pr https://github.com/prebid/Prebid.js/pull/10547
2. run dev server ``` gulp serve-e2e-dev```
3. navigate to http://localhost:9999/test/pages/userId.html
4. observe v2/auction to adtelligent bid adapter. (picked adtelligent since it proxies all provided userIds)  https://imgur.com/a/zbpkgM6

### Expected results
I expect that  all provided ids will be passed to bidAdapters. especially sync pubProvidedId

### Actual results
only first set of userIds configs is processed by pbjs. 

## Platform details
prebid versions: 8.13.0-pre, also 7.*

## Other info
this is not a problem of pubProvidedId, case reproducible with any set of ids. 
looking at code of userId, i can tell that it's designed to register new modules by making a diff with new modules set, but it doesn't work. 

Thanks for attention!

**Comment by dgirardi** [comment]
The example you gave can be "fixed" by replacing the second `setConfig` with `mergeConfig` instead and immediately following that with `refreshUserIds`. 

However, if the use case is that multiple scripts are trying to inject their pubProvidedId, that's not enough because `mergeConfig` does not know that the repeated pubProvidedId configs are related and should be merged together, it will instead concatenate them into `userId`. You can still do it by doing `getConfig` + some manipulation + `setConfig`. I am hesitant to expand more on how because it seems pretty far from the module's intended use. Maybe we need a separate API for 3rd parties to append their IDs to?

**Comment by GeneGenie** [comment]
@dgirardi thanks for response. I've tested id concatanation also. Bur this doesn't help. Also refreshUserIds leads to refresh of stored ids of other providers. 

Isn't pubProvidedIdSystem not designed for this case. 
I think the issue is somewhere in userId module, since it registers newcoming module configs with ready state.

**Comment by dgirardi** [comment]
> Isn't pubProvidedIdSystem not designed for this case.

It isn't, but it's a gray area because from Prebid's POV we can't tell the difference between the publisher and 3rd party scripts that the publisher is allowing onto the page. The biggest worry is that pubProvidedId is assumed to be a first party ID and does not go through the same privacy controls (TCF, GPP, dataController, etc)  that "real" ID modules do.

> I think the issue is somewhere in userId module, since it registers newcoming module configs with ready state.

I see the argument (and we could automatically refresh new IDs - not sure why we don't), but that's not the issue you're describing; if you post new configuration to `setConfig`, we are not supposed to remember the old config. `mergeConfig` does that. It's clunky to use in your case because it was never intended to be used by multiple independent actors, the assumption was that the publisher knows the entire list of IDs they are providing.

> Bur this doesn't help. Also refreshUserIds leads to refresh of stored ids of other providers.

You can choose to refresh only the IDs that you manipulated. I'll paste how I fixed the example you gave below, but again, it's a hack, and needs more complexity when there's multiple parties all trying to muck with pubProvidedId - and they all need to collaborate with each other. (As an extreme example, if a 3rd party script says `setConfig({userSync: {userIds: []}})`, prebid has to interpret it as "the publisher wants to remove all user IDs" - we can't tell it's not really the publisher).

<details>
  <summary>Sample page "fix"</summary>
  
  ```
<!-- This is a Test Page for a Banner End-to-End test  -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Prebid.js Banner Example</title>

    <!-- Prebid.js -->
    <script async
            src="http://localhost:4444/bundle?modules[]=adtelligentBidAdapter&modules[]=userId&modules[]=criteoIdSystem&modules[]=pubProvidedIdSystem"></script>

    <!-- Google Publisher Tag -->
    <script async src="https://www.googletagservices.com/tag/js/gpt.js"></script>

    <script>
      var pbjs = pbjs || {};
      pbjs.que = pbjs.que || [];

      // Prebid Banner Ad Unit
      const adUnits = [{

        type: 'display',
        code: 'div-gpt-ad-1460505748561-0',
        mediaTypes: {
          banner: {
            sizes: [[300, 250]]
          }
        },
        bids: [{
          bidder: 'adtelligent',
          params: {
            aid: 350975,
            placementId: 'Billboard_Top',
            divId: 'Billboard_Top_3c5425', // optional parameter
            pageTemplate: 'home', // optional parameter
            badv: ['example.com'], // optional parameter
            bcat: ['IAB1-1', 'IAB1-2'], // optional parameter
            bapp: ['com.blocked'], // optional parameter
            battr: [1, 2] // optional parameter
          }
        }]
      }
      ];
    </script>

    <script>
      var googletag = googletag || {};
      googletag.cmd = googletag.cmd || [];

      googletag.cmd.push(function () {
        googletag.pubads().disableInitialLoad();
      });

      pbjs.que.push(function () {

        pbjs.setConfig({
          userSync: {
            userIds: [
              {
                name: 'criteo',
                storage:{
                  type:'html5',
                  name:'criteo_id'
                }
              }
            ]
          }
        })
        pbjs.mergeConfig({
          userSync: {
            userIds: [
              {
                name: 'pubProvidedId',
                params:{
                  eids:[{
                    source: "domain.com",
                    uids: [{
                      id: "value read from cookie or local storage",
                      atype: 1,
                      ext: {
                        stype: "ppuid"
                      }

                    }]
                  }]
                }
              }
            ]
          }
        })
        pbjs.refreshUserIds({submoduleNames: ['pubProvidedId']})

        // pbjs.refreshUserIds();
        pbjs.addAdUnits(adUnits);

        pbjs.requestBids({ bidsBackHandler: sendAdServerRequest });
        //setInterval(() => pbjs.requestBids({ bidsBackHandler: sendAdServerRequest }), 5000)
      });

      function sendAdServerRequest() {
        googletag.cmd.push(function () {
          pbjs.que.push(function () {
            pbjs.setTargetingForGPTAsync('div-gpt-ad-1460505748561-0');
            googletag.pubads().refresh();
          });
        });
      }
    </script>

    <script>
      googletag.cmd.push(function () {
        googletag
          .defineSlot('/19968336/header-bid-tag-0', [[300, 250], [300, 600]], 'div-gpt-ad-1460505748561-0')
          .addService(googletag.pubads());

        googletag.pubads().enableSingleRequest();
        googletag.enableServices();
      });
    </script>
</head>

<body>
<h2>Prebid.js Banner Ad Unit Test</h2>
<div id='div-gpt-ad-1460505748561-0'>
    <script>
      googletag.cmd.push(function () {
        googletag.display('div-gpt-ad-1460505748561-0');
      });
    </script>
</div>
<div id="targeting-keys"></div>
</body>

</html>

  ```
</details>

**Comment by patmmccann** [comment]
Seems like this is solved with mergeConfig; can you tell your friends at intentiq?

**Comment by patmmccann** [comment]
The dmp identifier you refer to; would you prefer something like this? https://github.com/prebid/Prebid.js/blob/702bbbec675baebda1fe355cdcefe2ebe5d95739/src/prebid.js#L852 or are you preferring to just not get stepped on but other script?

**Comment by jdwieland8282** [comment]
We discussed this topic at length in the Identity PMC. We agreed to:
1. mandate that id sub adapters declare a 'provider' field if the origin was different from the source, for example if liveintent decided to set a sharedid. 
2. decided on an order of precedence, which was the owner of the module would superseded any 3rd party attempting to set the same id. For example, if liveintent tried to set a sharedid but the sharedid already set an id the sharedid id would trump the liveintent one. This work was discussed [here](https://github.com/prebid/prebid.github.io/pull/4675) & documented [here](https://github.com/prebid/prebid.github.io/pull/4675)

**Comment by patmmccann** [comment]
@jdwieland8282 I am not sure any of that solves OP problem that setConfigs are being used instead of mergeConfigs and the whole userid object gets blown away on the second setConfig

**Comment by patmmccann** [comment]
I propose we mark this ready for dev and solve with documentation pr to warn people that setConfigs can blow away exsiting config and reference this example.

**Comment by jdwieland8282** [comment]
So I'm clear @patmmccann , if each 3p .js on the pubs page were to build a `mergeConfig` vs a `setConfig` all ids supplied to the `pubProvided` module would be merged together?
