### ISSUE TITLE
dfpAdServerVideo auto include the adpod module on build, potential size saving?

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#10552]
question:  does the video module auto include the adpod module on build, as I'm seeing the adpod module in my build but i'm not including it directly.  If so, it would be good to be able to drop the adpod include, if possible, if dont need it, saves some 24kib by the looks of it

includes with videojs, not checked with jwplayer

not in modules:

![modulesVideo_json_—_Prebid_js](https://github.com/prebid/Prebid.js/assets/8503167/8c72b430-172e-4bc1-8d08-4df203976af8)

but in build:
![prebid_js_—_Prebid_js](https://github.com/prebid/Prebid.js/assets/8503167/9c7d68f9-1d9c-405f-90e0-fcc848f4a408)

**Comment by spormeon** [comment]
it seems to be the "dfpAdServerVideo" module thats adding the "adpod" module as well

but then appnexus is adding "categoryTranslationMapping.js" with its adapter:
![dependencies_json_—_Prebid_js](https://github.com/prebid/Prebid.js/assets/8503167/1d46272c-49a3-4bcd-9d97-7aea7a1a4ea1)


no clue if its even possible to "drop" these, if someone doesnt need/ use them, but seems like a way to save some "size"

**Comment by dgirardi** [comment]
`dfpAdServerVideo` and `freeWheelAdserverVideo` are set up as `adpod` submodules. `adlooxAdServerVideo` (the youngest) is not. I think this is probably a historical accident, to me it looks like in the beginning adpod was meant to be what outstream video is now. 

The fix is unfortunately also a breaking change - marking this for 9.0

Appnexus is a different matter  - `categoryTranslationMapping.js` is the [library](https://github.com/prebid/Prebid.js/blob/master/libraries/categoryTranslationMapping/index.js), not the [module](https://github.com/prebid/Prebid.js/blob/master/modules/categoryTranslation.js), and expected.

**Comment by dgirardi** [comment]
proposal: move adpod logic in a new "dfpAdpodServerVideo"
