### ISSUE TITLE
The right way to get bidderDone time

### ISSUE THREAD

**Issue by dariaboyko** [prebid/Prebid.js#10592]
## Type of issue
question 

## Description
So earlier i received time from bid.metrics.getMetrics() adapter.client.net and the difference with real ms in console network was 1,5 ms. Now when I check it the difference can be random from 10ms up to 400ms. So are there some better options of getting bidder response time? 

## Steps to reproduce
I check it in console like that 
`pbjs.getEvents().filter((el)=>el.eventType === 'bidderDone').map((el)=>{ return {bid: el.args.bids[0].bidder, metrics:el.args.bids[0].metrics.getMetrics()}})`
![image](https://github.com/prebid/Prebid.js/assets/73283727/a910b9b2-f4f2-4fb7-87f0-97e68ef44294)
![image](https://github.com/prebid/Prebid.js/assets/73283727/7ea4af43-c7a5-41e6-8d0d-a69c9526abf8)

## Test page
[
https://admixer-tests.azurewebsites.net/prebidTimeQuestion.html
](https://admixer-tests.azurewebsites.net/prebidTimeQuestion.html)

simple prebid js build with example from the prebid docs

### Expected results
Getting the most accurate time that is possible

**Comment by dgirardi** [comment]
The number from `getMetrics` is the time elapsed from when Prebid is just about to make the network request to when the response callback is run; from Prebid's POV I believe that's the most accurate you can get - it's the time it spends waiting for the response. 

It's always going to be larger than true network time due to delays from the browser's scheduler; sometimes much larger, I know some browsers will pause execution when they're out of focus for example. But page code does not have access to browser internals. Perhaps extensions do - I don't know - but that wouldn't be much different than using dev tools.

**Comment by dariaboyko** [comment]
Thank you! Where can i get the time that Prebid waits for the response from bidders?

**Comment by dgirardi** [comment]
It's the number you pointed out in the OP. The difference between that and the numbers from devtools is time where the browser has the response (or request) ready, but has not passed control back to Prebid yet. This could be because the thread is occupied with other scripts, or the connection pool is full, or a number of other factors that depend on the browser and are not visible to Prebid.
