### ISSUE TITLE
purpose: "transmitPreciseGeo" in consentManagement, dont think its working properly

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#10854]
## Type of issue
when we include in the consentManagement setup:

{
                purpose: "transmitPreciseGeo",
                enforcePurpose: true,
                enforceVendor: true
              }

no "geo" info is being passed to any bidder that has "special features"  - Use precise geolocation data . In the cmp, such as Index Exchange:

geo omited: IX bidder
![Screenshot_18_12_2023__09_42](https://github.com/prebid/Prebid.js/assets/8503167/2f603c48-0231-4530-9fd2-53b2368186f1)

take the above config out, geo appears: IX bidder
![Screenshot_18_12_2023__09_44](https://github.com/prebid/Prebid.js/assets/8503167/03d7a644-fe43-4b31-a04a-7b91ee6d389d)

Geo is also set in realTimeData:

![playlistUIverticalAmazonParallelReBid_html_—_Prebid_Publishers__Workspace_](https://github.com/prebid/Prebid.js/assets/8503167/6dc12eb5-11fc-474a-afc3-4c605dcc4572)

when purpose: "transmitPreciseGeo" is on, these warning are thrown:
![Screenshot_18_12_2023__09_57](https://github.com/prebid/Prebid.js/assets/8503167/204aff2d-0d2d-4669-bbf4-6cea49b81019)

## Platform details
chrome, mac P.V: 8.18.0

**Comment by dgirardi** [comment]
The screenshots do not tell me what you're looking at, but I tried and failed to reproduce for both the input and output of the IX adapter. Could you provide a test page? 

I did confirm that the geolocation module always gets denied, because the gdpr rules expect it to provide a GVL ID. I'll need to think about how to fix it; I'm not sure transmitPreciseGeo is a good fit for it.

**Comment by spormeon** [comment]
professor prebid those top 2 screenshots are from

**Comment by dgirardi** [comment]
OK I think I understand - they are the same problem; when the geolocation module gets denied it won't put `geo` in the bid stream so IX doesn't see it. If you set it through other means (through for example setConfig([ortb2 -> device -> geo])) the bidder part works as expected, although IX in particular does not look at `device.geo`, only `user.geo`.

A workaround, for now, is to override with:

```
setConfig({
    allowActivities: {
        transmitPreciseGeo: {
            rules: [{
                condition: ({component}) => component === 'rtd.geolocation',
                allow: true
            }]
        }
    }
})
```

This effectively disables GDPR enforcement for the geolocation module, but I don't think that matters since each bidder (and other RTD modules) still need to pass the consent check to get the data.

**Comment by spormeon** [comment]
ok, does that give a knock on issue then in the geolocation module, i.e the module only pushes to device, so any bidder picking up on user, its useless? Shouldn't there be 1 p;ace where they all pick it up from, be that dvice or user, to harmonise it all?

**Comment by dgirardi** [comment]
They are both part of the ORTB spec; I think they are supposed to be two different pieces of information - where the device is compared to where the user lives. Bidders are supposed to pick up both, but I wouldn't blame them if they didn't know what to do with two sets of coordinates.

**Comment by patmmccann** [comment]
We need to make the geolocation module vendorless; we need to check the publisher consents, not the vendor consents as we do in some other vendorless modules; we need to also never pop a dialogue asking user for precise location when the publisher doesnt have consent to it.
