### ISSUE TITLE
PAAPI Module: accumulate perBuyerSignals

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#11094]
## Type of issue
Feature request

## Description
Some bidders that are DSPs will be more likely to respond with perBuyerSignals than AuctionConfig. We should have a utility function to assemble the perBuyerSignals for creation of the publisher auction config

PAAPI configuration would take an auctionConfig, PBS would be injected only into that one. Prebid wouldnt be able to prevent someone injecting it into a bidder provided auction Config, but that wouldnt be in scope for this. In the future, some ssps might want to provide an auction config that welcomes injections but it should be only when identified in the response somehow.

A publisher could say for example call

pbjs.accumulatePerBuyerSignalForAdUnitCode('x', myAuctionConfig) where myAuctionConfig is a json object defining a full auction config that could have decisionLogic on the publisher or some other origin.

Aside: the rtbhouse module already provides publisher defined auction config support in their vendor module

**Comment by dgirardi** [comment]
Summary of offline discussions:

adapters should be able to provide just buyers and buyer signals instead of a complete auction configs;
buyers should collated into a component level auction using seller and decision logic provided by the publisher;
buyer signals should be augmented with FPD in the same way that auction signals are now.

**Comment by mikemangas** [comment]
@dgirardi  @patmmccann  is this module now necessary in order to use fledgeForGpt? Or do they both work completely independent from each other?
