### ISSUE TITLE
Windows alerts download of prebid.js as "Trojan:Script/Wacatac.B!ml"

### ISSUE THREAD

**Issue by dermick12** [prebid/Prebid.js#11190]
Windows blocks the download because windows defender recognizes "Trojan:Script/Wacatac.B!ml"
I searched but couldn't find any information whether this is a know issue of false recognition.

I tried different combinations of bidders, modules and versions of prebid.js but the error seams to come with the main program.

**Comment by dermick12** [comment]
![pbvirus](https://github.com/prebid/Prebid.js/assets/122674874/5de35a98-601c-43c0-8277-2d0ef047d00f)

**Comment by patmmccann** [comment]
What page are you initiating the download from, please link it

**Comment by dermick12** [comment]
https://docs.prebid.org/download.html?version=8.23.0&modules=sharedIdSystem

**Comment by patmmccann** [comment]
I cannot reproduce

**Comment by dermick12** [comment]
Ok, interesting. Thanks for testing!

**Comment by dermick12** [comment]
I get the alert only when I download prebid with chrome, not with firefox. I will try to find out more and close this issue now.
Thanky you for checking!

**Comment by dermick12** [comment]
Closed

**Comment by dgirardi** [comment]
There are some online tools that can check an upload against various databases. As I'd expect it shows all green if I try it on files generated by our download page; for example: https://www.virustotal.com/gui/file/bd14e38e8846227eda05dce5f1b48314fc8a53981431e4e66f70e9bc0335b42b?nocache=1

You may want to try it yourself - it's possible your chrome install is compromised. Otherwise, microsoft has a tool to report false positives that asks for more information than I can provide (I am also not able to reproduce): https://www.microsoft.com/en-us/wdsi/filesubmission/

**Comment by dermick12** [comment]
This was my second thought that my chrome is infected. I compared the files downloaded by chrome and firefox and they are identical. The check with virustotal is all green too.

Thank you very much for your quick help!
