### ISSUE TITLE
Even though accessDevice is enabled in PrebidConfig, activity control denied

### ISSUE THREAD

**Issue by Lvovk** [prebid/Prebid.js#11273]
## Description
Even though accessDevice is enabled in PrebidConfig, I get this: error activity control: bidderSettings.*.storageAllowed denied 'accessDevice' for 'bidder'

Is this behavior expected? If yes, what should I change to the avoid problem?

https://prebid-deploy-test.b-cdn.net/prebid_8.39.0_accessDevice_example.html

## Test page

![image](https://github.com/prebid/Prebid.js/assets/119592873/71c98e74-fd4d-40bc-8438-0d3e2aae35ca)
![image](https://github.com/prebid/Prebid.js/assets/119592873/01dbdd99-af73-4aad-93f3-c9e906282e31)

**Comment by dgirardi** [comment]
It's expected behavior. Bid adapters are denied storage unless explicitly enabled through [bidderSettings](https://docs.prebid.org/dev-docs/publisher-api-reference/bidderSettings.html). The rationale is that storage is not required to bid; the additional setting is intended to make publishers aware of what is being stored and why.

**Comment by Lvovk** [comment]
@dgirardi Thankhs, got it 
One more question 
Is there is way to allow all activities at once ? every activity for every bidder

**Comment by dgirardi** [comment]
There's no single setting to allow all activities. It's possible, but not recommended, to enable each one using [allowActivities configuration](https://docs.prebid.org/dev-docs/activity-controls.html).

**Comment by dgirardi** [comment]
Pending: update `accessDevice` and FAQ to mention bidderSetting and allowActivities.

**Comment by dgirardi** [comment]
@Lvovk I realized too late that I misinterpreted your issue description (I thought you were referring to the global `accessDevice` estting rather than the `accessDevice` activity).. It's still expected behavior, but I neglected to mention that this:

```
setConfig({
    allowActivities: {
          accessDevice: {
                 default: true
          }
    }
})
```

has  no effect, because all activities already have `default: true`. The default is used only when no other rule applies, and in the case of `accessDevice` on bidders, there's a built-in rule that enforces `bidderSettings.*.storageAllowed`.

To _override_ all rules for an activity, do this instead:

```
setConfig({
    accessDevice: {
         rules: [{allow: true}]
    }
})
```
