### ISSUE TITLE
Invalid requests generated by minuteMedia and rise bid adapters

### ISSUE THREAD

**Issue by Sir-Will** [prebid/Prebid.js#11289]
## Type of issue
Bug

## Description
The util function [getBidIdParameter](https://github.com/prebid/Prebid.js/blob/8.42.0/src/utils.js#L105) can cause the returned value and type to change. E.g. when the value is `0` it ends up being an empty string.

I'm not sure if the bidders are not handling it correctly or if this is a not intended side effect.

There are bidder endpoints, like the ones below, which expect an integer, but end up receiving a string and result in a 400 request.
- https://github.com/prebid/Prebid.js/blob/8.42.0/modules/minutemediaBidAdapter.js#L303
- https://github.com/prebid/Prebid.js/blob/8.42.0/modules/riseBidAdapter.js#L313C30-L313C49

## Other information
- https://github.com/prebid/Prebid.js/issues/11288

**Comment by dgirardi** [comment]
`gedBidIdParameter` is from ancient times, when requests were GET and everything was a string. Over time it was copied all over the place and I'd be surprised if that fallback still makes sense for more than a handful of adapters, but it's so baked-in that the bug is now a feature. There's not much we can do to fix it besides alerting adapters about specific issues.

FYI @YakirLavi
