### ISSUE TITLE
meta.dsa vs ext.dsa

### ISSUE THREAD

**Issue by EskelCz** [prebid/Prebid.js#11549]
## Type of issue
Question

## Description
This doc says the DSA on the Response object is supposed to be on `ext.dsa`:
[https://github.com/InteractiveAdvertisingBureau/openrtb/blob/main/extensions/community_extensions/dsa_transparency.md#bid-response](https://github.com/InteractiveAdvertisingBureau/openrtb/blob/main/extensions/community_extensions/dsa_transparency.md#bid-response)

This doc says the DSA on the Response should be on `meta.dsa`:
[https://docs.prebid.org/dev-docs/bidder-adaptor.html#interpreting-the-response](https://docs.prebid.org/dev-docs/bidder-adaptor.html#interpreting-the-response)

What is going on here? :) Should I check both parameters, or is one of the docs out of date, or am I missing something obvious?
Thanks.

**Comment by dgirardi** [comment]
The first refers to ORTB responses, the second to Prebid responses (which we often refer to as just "bids"). It's similar to how in ORTB they have `adm`, `w`, `h` that get translated in Prebid to `ad`, `width`, `height`. 

Which one you should use depends on what you're doing. If you are bid adapter interfacing with an ORTB endpoint you are dealing with both, otherwise - in most cases - you'll only see `meta`.

**Comment by EskelCz** [comment]
@dgirardi I see, thanks for the clarification. Closing
