### ISSUE TITLE
Failing tests on `master`

### ISSUE THREAD

**Issue by viktor-yoc** [prebid/Prebid.js#11635]
## Type of issue
Bug 

## Description
Test are failing on `master` branch. Documentation was followed.

## Steps to reproduce
Select `master` branch, follow README documentation, initialise the project and run `gulp test` 

## Test page
NA

### Expected results
Test not to fail on `master` branch

### Actual results
Test failing on `master`

## Platform details
- The environment info (Mac OS 10.15.7)
- Browser version in tests (for me it's Chrome Headless 125.0.6422.113 (Mac OS 10.15.7))
- The error message:
![image](https://github.com/prebid/Prebid.js/assets/124144219/752c0437-57a5-4182-a5a6-bbacd8bb4463)

## Other information
Code where is failing:
https://github.com/prebid/Prebid.js/blob/master/test/spec/modules/adagioAnalyticsAdapter_spec.js#L185

**Comment by osazos** [comment]
Let me check.

**Comment by osazos** [comment]
@viktor-yoc can you try with the fix? 
As explained in the PR, I was not able to reproduce the bug locally as I have a up to date MacOS version. The one used in the issue (10.15.7) is obsolete.

**Comment by vfedoseev** [comment]
Hi @osazos,
Thank you a lot for checking this case.
We have re-checked the environment details. 
The tests fail in the following environment:
- MacOS Sonoma 14.3 (M3 chip)
- Chrome for MacOS (Version 125.0.6422.142 (Official Build) (arm64))
- Chrome User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36

So, the actual MacOS version is not obsolete, it's just the Chrome User Agent that refers to the obsolete version 10_15_7.

After the additional investigation we found out that the error could occur because of target in Babel config.
If we add this target to babelConfig.js, all the tests run without any errors:

`'targets': {
    'ie': '11'
  }`
  
![image](https://github.com/prebid/Prebid.js/assets/8183991/13d663d7-a17a-4644-8dcd-2c7e78657a01)

**Comment by osazos** [comment]
> So, the actual MacOS version is not obsolete, it's just the Chrome User Agent that refers to the obsolete version 10_15_7.

Thanks for clarification, so I ran my tests in the same condition and I'm not able to reproduce the error.

After the changes I did on the AdagioAnalyticsAdapter, is the code fail at the same point? 

> Code where is failing:
> https://github.com/prebid/Prebid.js/blob/master/test/spec/modules/adagioAnalyticsAdapter_spec.js#L185

**Comment by vfedoseev** [comment]
> After the changes I did on the AdagioAnalyticsAdapter, is the code fail at the same point?
I've tested the changes and now the tests are completed, but some tests failed with the similar JS error message:
`Cannot access .... before initialization`:

```
AdgenerationAdapter
    isBidRequestValid
      ✖ should return false when required params are not passed
        Chrome Headless 125.0.6422.142 (Mac OS 10.15.7)
      ReferenceError: Cannot access 'bid' before initialization
          at Context.<anonymous> (/var/folders/wd/lyd9cxjx1gvf1_ql21bbf7580000gp/T/_karma_webpack_618636/commons.js:216395:35)

  Admaru Adapter
    isBidRequestValidForBanner
      ✖ should return false when required params are not passed
        Chrome Headless 125.0.6422.142 (Mac OS 10.15.7)
      ReferenceError: Cannot access 'bid' before initialization
          at Context.<anonymous> (/var/folders/wd/lyd9cxjx1gvf1_ql21bbf7580000gp/T/_karma_webpack_618636/commons.js:221178:35)

  AdmixerAdapter
    isBidRequestValid
      ✖ should return false when required params are not passed
        Chrome Headless 125.0.6422.142 (Mac OS 10.15.7)
      ReferenceError: Cannot access 'bid' before initialization
          at Context.<anonymous> (/var/folders/wd/lyd9cxjx1gvf1_ql21bbf7580000gp/T/_karma_webpack_618636/commons.js:222492:35)

      ✖ should return false when params required by WL are not passed
        Chrome Headless 125.0.6422.142 (Mac OS 10.15.7)
      ReferenceError: Cannot access 'wlBid' before initialization
          at Context.<anonymous> (/var/folders/wd/lyd9cxjx1gvf1_ql21bbf7580000gp/T/_karma_webpack_618636/commons.js:222500:37)
```

I've also checked the node version - it's v18.4.0.

Now I've tried to run `npm install` again and the local tests run successfully. 
Probably the issue was related to the outdated versions of node modules. Sorry for the false alarm, I think no changes are needed (and the PR could be closed https://github.com/prebid/Prebid.js/pull/11636).
