### ISSUE TITLE
All prebid.js configurations downloaded are now failing with an ORB error

### ISSUE THREAD

**Issue by dilburt** [prebid/Prebid.js#11805]

**Comment by patmmccann** [comment]
Which version?

**Comment by dilburt** [comment]
I tried the last 3 versions, 8.51, 8.52 and 9.00 and got the same ORB error when prebid.js tries to load into Chrome. Just to make sure I also tried Firefox and got the same error. I tried several different configurations of modules with the same result every time. I did verify that no unsupported bidders or modules were being selected.

I should mention that we're dynamically loading the module but I seriously doubt if that can be related since if I use any of the prebid.js versions we created even a few days ago they load just fine.

**Comment by dgirardi** [comment]
Is this the same problem as in https://github.com/prebid/Prebid.js/issues/11811 / https://github.com/prebid/Prebid.js/issues/11810 - the prebid file not an actual js file if certain mdoules are selected? If not, could you provide steps to reproduce?

**Comment by dilburt** [comment]
I removed the TCF modules but am still getting the error. In addition, all previous modules had TCF selected and did not generate the ORB error.

**Comment by dgirardi** [comment]
What error? Could you provide steps to reproduce?

**Comment by dgirardi** [comment]
OK - it's is the same type of issue as in https://github.com/prebid/Prebid.js/issues/11811 - but with a twist.

For version 9, "enrichmentFpdModule" should not be selected (it was removed, but has been an empty module for a while, so it's safe to remove for 8.x as well)
For version 8 several of the recommended modules were renamed, currently they can't be included, should be fixed with https://github.com/prebid/prebid.github.io/pull/5434
And the twist: as far as I can tell, "Zeta Global" has never worked for any version. Should be fixed with https://github.com/prebid/prebid.github.io/pull/5435
