### ISSUE TITLE
Question: Development build with debugging module

### ISSUE THREAD

**Issue by EskelCz** [prebid/Prebid.js#11883]
## Type of issue
Question

## Description
Whenever I'm replacing production prebid with unminified/development build of prebid (using resource override) and using `__pbjs_debugging__` in session storage, I get this error:

<img width="911" alt="prebid-error" src="https://github.com/prebid/Prebid.js/assets/1198558/bf84afad-f5fa-4382-87ee-c25da6899eda">

Any idea what might be happening?

I'm building the full version like this: `gulp build-bundle-dev --modules=modules.json`, I assume that is correct.

## Steps to reproduce
1. Visit https://www.poznatsvet.cz/?pbjs_debug=true
2. Use resource override to replace:
https://cdn.cpex.cz/hb/prebid/prebid.min.js -> https://cdn.cpex.cz/stage/hb/prebid/8.49.0/prebid.js
3. Add debugging:
```
pbjs.setConfig({
  debugging: { enabled: true, bids: [{ cpm: 15 }] }
})
```

### Expected results
Debugging mode to work with unminified version

### Actual results
Error, Prebid breaks after that point

## Platform details
MacOS, latest Chrome, Prebid 8.49.0

**Comment by EskelCz** [comment]
I know the path isn't there but the same thing works with the minified version, so I assume the paths is supposed to be relative, within a bundle? Not sure how this works.

**Comment by dgirardi** [comment]
On development builds, by default, it points to the dev server (as you have discovered). It doesn't work too well for what you're trying to do, and maybe we should change it - it made sense to me because I was thinking of development on Prebid itself.

[this](https://github.com/prebid/Prebid.js/blob/0c560a39830d693011122417cd9f296cdfd2f9bf/plugins/pbjsGlobals.js#L37) is where the path is chosen, and [here](https://github.com/prebid/Prebid.js/blob/0c560a39830d693011122417cd9f296cdfd2f9bf/gulpfile.js#L169)'s the override. You can set it explicitly with:

```
gulp build --dist-url-base "https://cdn.jsdelivr.net/npm/prebid.js@latest/dist/"
```

**Comment by EskelCz** [comment]
Thanks, building in the module turned out to be the simplest solution. Closin
