### ISSUE TITLE
Appnexus BidAdapter: It may not be possible to use currencies other USD

### ISSUE THREAD

**Issue by saitoukun** [prebid/Prebid.js#11994]
## Type of issue

- Adapter and server mismatch

## Description

- We use `JPY` currency.
- `currency` will use `publisher_currency_codename` from  `Server's Bid`. This case is `JPY`
- But `cpm` is always seems to be `USD`
- As a result, the currency exchange process was not executed and was regarded as a very low cpm.

This means that the server may only support `USD`

## Platform details

There was no problem up to 8.50.0
I got problems since 8.51.0

> Appnexus Bid Adapter: parse the currency from the bid if specified
https://github.com/prebid/Prebid.js/releases/tag/8.51.0

## Other information

related PR
https://github.com/prebid/Prebid.js/pull/11581

**Comment by saitoukun** [comment]
Related MR
https://github.com/prebid/Prebid.js/pull/11581

**Comment by saitoukun** [comment]
I'm contacting appnexus for specs.

**Comment by saitoukun** [comment]
Here is sample of bid responce.
```
{
  "cpm": 0.477453,
  "cpm_publisher_currency": 74.943749,
  "publisher_currency_code": "¥",
  "publisher_currency_codename": "JPY",
  "content_source": "rtb",
  "ad_type": "banner",
  "media_type_id": 1,
  "media_subtype_id": 1,
  "brand_category_id": 180,
  "is_sov": false,
  "is_roadblock": false,
  "bidder_id": 440,
  "client_initiated_ad_counting": true,
  "is_managed": false,
  "no_consent": false,
}
```

- `publisher_currency_codename` is `JPY`
- It seems to be `cpm` is  always `USD`
- I found `cpm_publisher_currency`. It seems to be `JPY` (Now `$0.477` is around 74JPN)
- Maybe we should use this param, If we use currency other USD.

**Comment by saitoukun** [comment]
I am a partner, and this is just a guess from the Bid responce.
So I think It should be revert once. 
And then we should ask Appnexus engineers for imprement `newBid` function with the exact specifications.

**Comment by jsnellbaker** [comment]
Hi all,

So I contacted an engineer who works on the appnexus endpoint and confirmed some details about the cpm and currency functionality (as it changed a little).

The `cpm` field in our endpoint's bid response will always be USD.
The `cpm_publisher_currency` field in the bid response will reflect and convert to the currency that was set at the publisher entity in the ad server system.  

I confirmed this by setting up a new test publisher that was set to JPY, and in the test bid response I saw the following:
```
{
    "cpm": 1.5,
    "cpm_publisher_currency": 235.44858,
    "publisher_currency_code": "¥",
    "publisher_currency_codename": "JPY",
    "content_source": "rtb",
    "ad_type": "banner",
    ...
}
```

The bid is set to $1.5 USD normally and for the JPY test publisher the `cpm_publisher_currency` field had the JPY equivalent.  

Currently in the adapter, the `cpm_publisher_currency` is not included in the prebid bid object.  The prebid currency module (tmk) will convert the cpm value depending on the publisher setup.  So unless I'm mistaken, I believe we could just leave things as is (post the revert) and let publisher make the changes with the module (since that will update the primary cpm value that prebid operates off of).

Please share any feedback/concerns about the above.

**Comment by saitoukun** [comment]
Thank you!
