### ISSUE TITLE
Assistance Needed for IncrementX Instream Video Adapter Integration

### ISSUE THREAD

**Issue by Prebid-Vertoz** [prebid/Prebid.js#12118]
## Type of issue

Assistance Needed for IncrementX Instream Video Adapter Integration
## Description

Dear Prebid Team,

We are currently working on the Prebid video instream adapter for IncrementX. We have successfully integrated the necessary code into our existing adapter, and it is functioning as expected. However, we are encountering an issue where the ad is rendered, but pbjs.getAllWinningBids() is returning an empty result or not indicating a winning bid.

Could you please assist us in resolving this issue?

For your reference, we have created a test page where you can observe the scenario:

https://textfeed.howgeneric.com/Prebid/Instream/IX_instream.html

Thank you in advance for your support.

## Test page

https://textfeed.howgeneric.com/Prebid/Instream/IX_instream.html

**Comment by dgirardi** [comment]
I believe this is expected behavior. Prebid considers bids "winning" once they have been rendered, but has no general way to know when an instream video bid has been rendered (it depends on the player). 

Publishers can either manually call [markWinningBidAsUsed](https://docs.prebid.org/dev-docs/publisher-api-reference/markWinningBidAsUsed.html), or use the [video module](https://docs.prebid.org/prebid-video/video-module.html), which manages integration with the player.

**Comment by dgirardi** [comment]
@Prebid-Vertoz is this still an issue?

**Comment by Prebid-Vertoz** [comment]
> @Prebid-Vertoz is this still an issue?

We’ve tried integrating the Prebid Video Module as per [video module](https://docs.prebid.org/prebid-video/video-module.html) but it's not working. Could you advise on integrating it with the test page at (https://textfeed.howgeneric.com/Prebid/Instream/IX_instream.html)

**Comment by Prebid-Vertoz** [comment]
@dgirardi Any update on this?

**Comment by patmmccann** [comment]
@Prebid-Vertoz we recommend you join our community attend video committee meetings. This issue is not particularly specific; what isn't working? What happens, what do you expect to happen? Have you followed the documentation? "something doesnt work, we're not sure what' is not an issue we can provide continued support on.
