### ISSUE TITLE
Unit Testing for New Adapter

### ISSUE THREAD

**Issue by soman** [prebid/Prebid.js#12130]
## Type of issue
question

## Description
Can we use jest for prebid new adapter unit testing?

**Comment by dgirardi** [comment]
The project is not set up for jest. [Here's some previous discussion on the same topic](https://github.com/prebid/Prebid.js/issues/10806) which still applies: it's not a priority, but we welcome contributions.

If you're asking because you find the test suite too cumbersome to use, I recommend using
`gulp serve-and-test --file [your_spec_file]`.
