### ISSUE TITLE
Error parsing request: Invalid URL - S2S

### ISSUE THREAD

**Issue by SallyMennen** [prebid/Prebid.js#1230]
## Type of issue

Question

## Description

Testing the Prebid Server functionality and followed all instructions - loaded the page, filtered for 'auction' in the Network tab of development tools and see the following message where I'd expect to see bids:

`{status: "Error parsing request: Invalid URL x...yz.com"}`

I see the same behaviour on the demo link referenced by another contributor in another ticket:
https://github.com/prebid/Prebid.js/issues/1197#issuecomment-301346783

## Steps to reproduce

https://pastebin.com/wDS8Kyyv

## Platform details

v0.23.1, Chrome/Windows

**Comment by dmitriyshashkin** [comment]
I had similar problem when using gulp server: test page was running on port 9999, managed to fix that by switching to port 80 (no port number explicitly in page url).

**Comment by junyi-york-huang** [comment]
I hit the same issue when testing Prebid.js (with FAN configured as demand partner), and find out it might be caused by the code of prebid-server listed below:

https://github.com/prebid/prebid-server/blob/master/pbs/pbsrequest.go#L166-L170

Question: What is this "whitelist"? how can I add our website domain to this whitelist? Couldn't find any clue in the Prebid website

**Comment by mkendall07** [comment]
we have removed the whitelist for now so this should no longer be an issue.

**Comment by himtaklo** [comment]
I am still getting the same error when trying to test it with localhost:9999
`{"status":"Error parsing request: Invalid URL 'localhost:9999': publicsuffix: cannot derive eTLD+1 for domain \"localhost:9999\""}`

**Comment by mkendall07** [comment]
well localhost isn't a valid domain. Try spoofing localhost to a valid domain format.
