### ISSUE TITLE
Activity control: TCF2 denied 'accessDevice' for 'userId.sharedId'

### ISSUE THREAD

**Issue by basak-kurt-iqd** [prebid/Prebid.js#12373]
## Type of issue
Bug

## Description
Without making any changes to our current system and despite following the documentation, we have been unable to pass the ShareID to PreBid for the past two weeks. During testing, we observed that the ShareID cookie is set correctly. In the Bidder Settings, it shows that it has already been generated, but the pubcid.org ID does not appear in the User ID module. Additionally, in the Prebid Professor Extension, we receive an error message related to device access.

## Steps to reproduce
1. Go to the website
2. Open the Prebid Extension
3. Click on the User ID module
4. Click on Events to view the errors

## Test page
https://www.cicero.de/

### Expected results
The pubcid.org ID should be visible in the Prebid Professor Extension and successfully passed to PreBid

### Actual results
![image](https://github.com/user-attachments/assets/a1e380b8-ed09-4b6e-8165-af138f92967a)

## Platform details
![image](https://github.com/user-attachments/assets/1c76f51b-ecf4-4b84-bcd3-a1c07868c829)
Prebid.js v. 9.5.0
Browser: Chrome v. 130.0.6723.59
OS: Windows

## Other information
We are also receiving the same error for Agma Analytics on some sites.

**Comment by dgirardi** [comment]
This is due to https://github.com/prebid/Prebid.js/issues/10622

tcfControl now looks for publisher consent (or legitimate interest) for for first party activity such as sharedId device access. On that website, after clicking "accept all", there's neither , and we take it to mean that consent was denied.

```
{
  "consents": {},
  "legitimateInterests": {},
  "customPurpose": {
    "consents": {},
    "legitimateInterests": {}
  },
  "restrictions": [...]
```

My understanding is this is a CMP configuration problem - the default prompt does not ask/grant publisher consent. However I have never worked with CMP backends and can't offer any more help on that front.

If you are comfortable with ignoring publisher consent settings, you can also circumvent this by adding `sharedId` to [`vendorExceptions`](https://docs.prebid.org/dev-docs/modules/tcfControl.html#page-integration) in the `storage` rule configuration.

**Comment by patmmccann** [comment]
We've corrected the behavior at iabe suggestion. You must express publisher purpose consents in your CMP to pass the shared id, not just vendor purpose consents

**Comment by sorinspd** [comment]
Getting the same error on Prebid.js 10.22, even though the publisher consents seem fine (below). It works fine on 9.53.5. Other ID modules work fine on both v10 and v9. Any ideas how to troubleshoot this further? Thanks!

```
{
    "consents": {
        "1": true,
        "2": false,
        "3": true,
        "4": true,
        "5": false,
        "6": false,
        "7": false,
        "8": false,
        "9": false,
        "10": false,
        "11": true
    },
    "legitimateInterests": {
        "1": false,
        "2": true,
        "3": false,
        "4": false,
        "5": true,
        "6": true,
        "7": true,
        "8": true,
        "9": true,
        "10": true
    },
    "customPurpose": {
        "consents": {},
        "legitimateInterests": {}
    },
    "restrictions": {}
}
```
