### ISSUE TITLE
Prebid.js gives error on some iphone models such as 11

### ISSUE THREAD

**Issue by opskn** [prebid/Prebid.js#12500]
## Type of issue

Prebid.js gives error on some iphone models such as 11

## Description

Hello,
Prebid.js version created from prebid.org website gives error on some iphone models such as 11 or 8
When I try to debug error, I can't. Because I can not see in developer console. When I open by clicking error message, nothing happnes instead og going error source.
## Steps to reproduce

I created very basic blank page for testing.
https://pigeoon-native.b-cdn.net/common/v8/prebid.html
You can also create blank html page and paste belowed code into html page
<html>
<head>
    <script async src="https://pigeoon-native.b-cdn.net/common/v8/prebid9.20.0.js"></script>
</head>
<body>
</body>
</html>

If you test with "BrowserStack" on iPhone 11 chrome or safari you can see error on console

## Test page

https://pigeoon-native.b-cdn.net/common/v8/prebid.html

### Expected results
Gives error
SyntaxError: Unexpected token '?'

**Comment by opskn** [comment]
If anyone can help I would be very happy

**Comment by dgirardi** [comment]
To elaborate: the error is due to the browser not supporting some JS features; for example [??](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) is supported from IOS 13.4, and the iphone 11 available on Browserstack is running 13.1. I am not an iphone user so I don't know if that means that "real" devices are stuck on that version - an OS update would solve the issue.

We compile against browsers that have at least 0.25% market share and the earliest IOS version that passes that test is 15.6. You can adjust that as @patmmccann mentioned.

**Comment by opskn** [comment]
Thank you @patmmccann  and @dgirardi 

This was very helpful information. It works! 

Actually you're right. But one of our manager noticed this situation. 

Thanks a lot again
