### ISSUE TITLE
realtime data modules not initialising

### ISSUE THREAD

**Issue by AntonioGargaro** [prebid/Prebid.js#12519]
## Type of issue

Bug

## Description

A recent upgrade to v9.18 on our customer's site has stopped initialising the Permutive RTD module.
Site: https://www.techspot.com/community/?pbjs_debug=true

It is logged that our RTD module is not loading:
![Screenshot 2024-11-28 at 17 12 57](https://github.com/user-attachments/assets/f5151f9d-5f38-4baf-b856-10e176fde277)

The module is installed and included:
![Screenshot 2024-11-28 at 17 14 28](https://github.com/user-attachments/assets/6d840a57-1215-42ea-8b45-bf7dc3627cd0)

I performed some debugging of Prebid bundle and found that [this line](https://github.com/prebid/Prebid.js/blob/0b882c2a7d39dfffc31920ec2ead2b9a2307bb99/modules/rtdModule/index.js#L273) is the culprit as it is empty at the point [initSubModules()](https://github.com/prebid/Prebid.js/blob/0b882c2a7d39dfffc31920ec2ead2b9a2307bb99/modules/rtdModule/index.js#L252) is called on this line. 

The [attachRealTimeDataProvider()](https://github.com/prebid/Prebid.js/blob/0b882c2a7d39dfffc31920ec2ead2b9a2307bb99/modules/rtdModule/index.js#L427) appears to be called after the initialisation which I'm assuming is because it's an async hook?

I did a little more debugging and found that [registering of the submodule](https://github.com/prebid/Prebid.js/blob/0b882c2a7d39dfffc31920ec2ead2b9a2307bb99/modules/permutiveRtdProvider.js#L496) happens before the realtime data module inits, so I suspect that it should be registered but just is not. 

## Steps to reproduce

Visit site: https://www.techspot.com/community/?pbjs_debug=true

Observe the log that the submodule doesn't load.

### Expected results

Submodule should load

### Actual results

Submodule does not load

## Other information

Another [customer's site](https://nypost.com/2024/11/28/sports/grayson-murrays-dad-reveals-heartbreaking-last-conversation-with-golfer-before-suicide/?pbjs_debug=true) on Prenid v9.12 appears to load the submodule correctly.

**Comment by dgirardi** [comment]
This is caused by `processQueue()` being called too late. The current sequence of events appears to be:

 1. load prebid
 2. set up prebid (`pbjs.que.push(...)`)
 3. call `processQueue`.

Rearranging it so that it's either 2-1-3 or 1-3-2 should fix it; the issue is with setting up configuration in between. This is because prebid [patches `que.push`](https://github.com/prebid/Prebid.js/blob/f7e44cc0a63788711301ec5abcf673f7925453a2/src/prebid.js#L975) when loaded, but [runs initialization](https://github.com/prebid/Prebid.js/blob/f7e44cc0a63788711301ec5abcf673f7925453a2/src/prebid.js#L1007) on `processQueue`.

It looks to me like we should fix it within Prebid as well, but afaik this never would have worked; are you able to confirm if it's indeed related to the update to 9.18, or the order of events just happened to change with it? The working 9.12 example uses the "standard" approach of calling `processQueue` immediately after Prebid loads.
