### ISSUE TITLE
Prebid's iframe in AMP

### ISSUE THREAD

**Issue by rafaguerrero** [prebid/Prebid.js#1284]
## Type of issue
Performance Bug

## Description
I've implemented the solution that you propose for integrating AMP with Prebid and I found that my revenue are way lower than expected.

I think this might be related to this issue: https://github.com/prebid/Prebid.js/issues/880

Due to the increase in AMP traffic this is a major concern on my end.
Is there anything to do about it?

**Comment by bretg** [comment]
Some of the adapters support defining the referring URL, documented or not. e.g. Both Rubicon and AppNexus support passing bid.params.referrer from the AdUnit.

Perhaps you could check the code for the adapters you're using and try passing the referrer param for any that support it?

Instead of having to pass this in for each bidder, we should be able to add referrer to the standard bidRequest. It would still be up to the adapter to use it.

**Comment by bretg** [comment]
@rafaguerrero - any update on AMP? Were you able to try passing referrer?

**Comment by matthewlane** [comment]
Closing as stale, please reopen if there are updates
