### ISSUE TITLE
Bids are caps unclear/inconsistent

### ISSUE THREAD

**Issue by djlosch** [prebid/Prebid.js#13]
1) why are there different bid caps for granularity levels?  If the true bid is $10.37, the granularity levels look like they'll respond with $5, $10.30, and $10.37 respectively.  I'm not sure how is this useful, or why as a pub, we'd want this.  We just want the $10.37.

2) is there any particular reason why bids are hard-capped at $20?  We regularly break that limit on AdX meaning prebid.js would be handicapping itself regularly with non-competitive bids.

**Comment by prebid** [comment]
- The $10.37 is also available via bidResponse.cpm. (in fact it can be $10.3723)
- Granularity levels are helpful because each line item is assigned to a price (so that DFP can make header bidding line items compete with class 1 line items based on price). If the granularity is at $0.01, capped at $20, then you'd need 100*10=2000 line items. If you don't want to manage that many line items, set the granularity lower, say $0.50, then you'd have 2*10=20 line items.
- 99% of the bids are below $20 from our observation. We return the exact price in bidResponse.cpm as well, thus you can customize your granularity and cap.

**Comment by djlosch** [comment]
That makes a lot more sense.  This issue is effectively a documentation clarification request then.  I'd commit your response into the docs on prebid.org and make a pull request, but those docs aren't inside the repo.

> 99% of the bids are below $20 from our observation.

Certain audiences segments average well above $20 for IAB display.  Using just a % of bids doesn't provide any weighting for value.  For example, a single impression at $50 is worth the same as 1000 impressions at 5 cents.

**Comment by prebid** [comment]
Thanks for the suggestion! This is really helpful as we've heard the same feedback just over the weekend. I'll mark this ticket as a feature request and we'll get to it once a few other more urgent issues are fixed.

The Github doc is available at:
https://github.com/prebid/prebid.github.io

**Comment by prebid** [comment]
Closing the issue as there're no more action items left.

**Comment by hariakhil31** [comment]
So is the $20 cap now removed?

**Comment by hariakhil31** [comment]
> you can customize your granularity and cap.
How to customize the cap? Is there an API method?

**Comment by mkendall07** [comment]
@hariakhil31 
Take a look at release notes for 0.14.0 (Custom cpm bucket sizing) the cap can now be set explicitly:
https://github.com/prebid/Prebid.js/releases/tag/0.14.0
