### ISSUE TITLE
Verify all bidder adaptors are HTTPS compliant

### ISSUE THREAD

**Issue by prebid** [prebid/Prebid.js#136]
As a publisher, I'd like to send HTTPS only requests through Prebid.js, so that my HTTPS pages can serve header bidding ads.

**Comment by robert-kraemer** [comment]
This is in fact becoming more and more important since publishers are switching to HTTPS only inventory. For Rubicon in fact there is a call being made to a hardcoded http address (http://ads.rubiconproject.com/ad/%%RP_ACCOUNT%%.js) that could easily replaced by a secure call. Any plans to fix/support this in an upcoming release?

**Comment by prebid** [comment]
Thank you @robert-kraemer - we are adding Rubicon's latest API FastLane:
https://github.com/prebid/Prebid.js/pull/158

It is HTTPS compatible and we are launching it soon. Do you think you will be able to use FastLane, instead of the current older API? We are deprecating the older API as well, because it's much slower and requires building an iFrame.

**Comment by mkendall07** [comment]
This is fixed now that Rubicon is using HTTPS. https://github.com/prebid/Prebid.js/commit/9ee0650f77e9debe22061e326d9006bfd312b85d
