### ISSUE TITLE
How it is decided that bid request is timed out?

### ISSUE THREAD

**Issue by polapi** [prebid/Prebid.js#1365]
## Type of issue
Question

## Description
I've started using roxot's external prebid.js analytics tool and I was wondering how the bidder timeout is being calculated. I assume the analytics relays on events sent by prebid.js so that's why I think it's a right place to ask. I mostly wonder if requests which are somehow ad blocked are being shown as timed out. I mean I have high timeout rate and I am not sure if increasing timeout time would do any good.

Also while thinking about it, I thought it would be nice to be able to distinguish types of timeouts. I mean analytics should have information to know if request was timed out only because it came after PREBID_TIMEOUT or it did not ever give any response. That way people doing analytics software could somehow ignore bidders which are "blocked".

**Comment by mkendall07** [comment]
Timed out bids are bids that were received by prebid.js after the publisher defined `PREBID_TIMEOUT` value. Other types (no bid) etc should not be included in the timed out bids.

**Comment by alex-khar** [comment]
So there are 3 types of bidder responses for Prebid Analytics: bid, no bid ($0), and no response. No response means that there was no response from a bidder in the time specified in your PREBID_TIMEOUT. Hence, no response = timeout. Prebid Analytics doesn't know if a bidder's bid was late or a bidder didn't respond at all.

It'd be nice to distinguish types of timeouts; however, there are the following issues:
- Prebid Analytics relies on prebid.js events. There is no even for late bids. So prebid.js doesn't track if a bid was late or there was no response at all.
- More philosophical question: how long should we wait for a response after the timeout? 3 sec, 1 min, or an hour? What if a user closes the tab and we lose the data because of that?

Does it answer your question?
