### ISSUE TITLE
AnalyticsAdapter doesn't catch all events anymore

### ISSUE THREAD

**Issue by Yann-Pravo** [prebid/Prebid.js#1373]
## Type of issue
Bug

## Description
Hi,
I'm developing a new analytics adapter for Adomik.
Before the last month's Prebid refactoring, the track function of AnalyticsAdapter (the Prebid.js one src/AnalyticsAdapter.js) catched all events (init/end/response/request/winner) but after the refactoring, it only catchs Init and End events with my example and yours (pbjs_example_gpt.html).

Are you aware of that or am I missing something ?

## Steps to reproduce
Launch pbjs_example_gpt.html with ga, roxot or any existing analytics adapter and console.log(eventType) in the _track function.

### Expected results
Catch all events

### Actual results
Catch only Init and End events

## Platform details

Prebid.js version: 0.26.0-pre

**Comment by mkendall07** [comment]
@snapwich is going to take a look at this.

**Comment by snapwich** [comment]
Hi @Yann-Pravo, would you mind providing more testing information, or a sample test page with the proper configuration?  I am unable to replicate your issue. 

I did notice an issue with the Google Analytics adapter from the refactor which I have submitted a fix for (#1382).  However, the google analytics adapter does not use the AnalyticsAdapter.js, so I'd be surprised if it fixed the issue you are seeing.

The pbjs_example_gpt.html test page uses google analytics.  I did a test with the pubwise analytics adapter (since it is an endpoint analytics adapter that use AnalyticsAdapter.js with no configuration required) where I replaced it's track function with `console.log("track:", eventType);` as you have suggested but I seem to be seeing all the proper events firing:

<img width="206" alt="screen shot 2017-07-14 at 1 56 52 pm" src="https://user-images.githubusercontent.com/551085/28228735-ec5ad9a0-689c-11e7-9a62-960d9c631952.png">

**Comment by Yann-Pravo** [comment]
Hi @snapwich,
I tried again today and it works, I don't know if it's your fix but it's fine now. Thank to had a look at this anyway.
