### ISSUE TITLE
PubWise "code" Changed in Version 26

### ISSUE THREAD

**Issue by GLStephen** [prebid/Prebid.js#1417]
## Type of issue
In version 26 the "code" or "provider" for PubWise Analytics was changed from "pubwiseanalytics" to "pubwise". We will be staying with that going forward so as not to flop back and forth, but this is causing significant documentation issues with new users. Is there some way to codify these or to otherwise enshrine the codes used for adapters/modules?

**Comment by mkendall07** [comment]
@GLStephen 
This wasn't intentional, apologies for the mix up. Previously codes had been generated from the file name, however, with the introduction of modules that isn't the case anymore. Generally speaking, we won't be modifying your module files unless there is a urgent need to do so. Best thing to do is probably put a comment on the line that defines the code now and mention that it should not be changed: https://github.com/prebid/Prebid.js/blob/master/modules/pubwiseAnalyticsAdapter.js#L49

**Comment by GLStephen** [comment]
@mkendall07 totally understand, now that I know the source of the change based on existing process we'll definitely keep with the "pubwise" code. That way we won't be unnecessarily pushing against that convention. Thanks for the info.
