### ISSUE TITLE
Question: When will prebid 0.26.1 be available on http://prebid.org/download.html ?

### ISSUE THREAD

**Issue by headerbidding** [prebid/Prebid.js#1430]
When will prebid 0.26.1 be available on http://prebid.org/download.html ?

**Comment by robthehall** [comment]
Until then, is the recommended workaround to compile it ourselves? Is 0.26.1 considered as production-ready as 0.25.0 (the current version from prebid.org)?

**Comment by dbemiller** [comment]
Hey, sorry about this guys. The download page usually does lag the official latest release by a bit... but this one has been particularly slow. Updates to the download page are much slower than usual this release because of the change to the build for #1177. It's being worked on, but will probably be at least another week or so.

The 0.26.1 release is just as production-ready as 0.25.0. You can definitely compile it yourself with `gulp build --modules=bidderAdapter, bidder2Adapter,...`. The Prebid script will be output to `build/dist/prebid.js`. Make sure you run `git checkout 0.26.1` first, because commits made after that have _not_ been tested as thoroughly as the official releases.
