### ISSUE TITLE
gulp serve not creating the ./build/dev/prebid.js file

### ISSUE THREAD

**Issue by uditalias** [prebid/Prebid.js#1441]
## Description
When running `gulp serve` the `prebid.js` file is not located at the `./build/dev` folder as documentation says.

## Steps to reproduce
1. Clone the repo.
2. run `gulp serve` in the project root

### Expected results
The file `prebid.js` is located in the `./build/dev` folder.

### Actual results
The file `prebid.js` is NOT located in the `./build/dev` folder.

## Platform details

Node Version: 8.2.1
NPM Version: 5.3.0
MacOS Sierra 10.12.5 (16F73)

**Comment by GLStephen** [comment]
I submitted a related pull request here: https://github.com/prebid/Prebid.js/pull/1403

It seems logical that dev and dist are built together. Currently there appears to be no path to do so. My change allows it to be done explicitly. It seems like that should be the default behavior.

**Comment by uditalias** [comment]
@GLStephen  I just replaced my `gulpfile` with your solution and it worked. Thank you.

**Comment by philipwatson** [comment]
Didn't work for me. 

I'm working with the latest version on master (commit 7d717b5). Been working on an older version (early march version, commit de8bc31) without problem.

I no longer get the prebid.js file in ./build/dev when I run the command gulp serve as you would expect from reading the README.md

Instead I get a javascript and source map file for every adapter. I also get prebid-core.js.

Also I also seem to get all the adapters even when I use the --modules=xyzBidAdapter

Same result when I run gulp devpack or gulp build

Is this intentional and README.md still needs to be updated?

node version 7.10.0
npm version 4.2.0
CLI version 1.2.2
Local version 3.9.1

**Comment by uditalias** [comment]
@philipwatson I also cloned the master and I have the same issues as yours. When i replaced my grunt file with the one in @GLStephen PR i can now see the prebid.js file under build/dev folder

**Comment by philipwatson** [comment]
Thank you @uditalias but I tried replacing the gulpfile again and it didn't work. It makes total sense because the gulpfile change is about having finer control about what build directory gets cleared (all, dist or build).

However I did manage to get it to work in the end. I deleted the node_modules directory and did a npm install. Now everything works fine. So the problem must've been caused by one or more old node dependencies.

Time to start using yarn ;-)
