### ISSUE TITLE
Question: Would prebid.js hosted by a CDN improve latency

### ISSUE THREAD

**Issue by headerbidding** [prebid/Prebid.js#1515]
Question: 
Instead of each site hosting their own prebid.js, would a prebid.js (with all adapters included) hosted by a CDN  (or by Appnexus) improve latency (due to browser caching)?

**Comment by ptomasroos** [comment]
Its a good theory but the weight would probably be issue here compared to having their own version.
Plus another thing is that having a connection to host and using for instance http2 or spdy being able to reuse that connection and multiplex files actually benefits when fetching data from the same host instead of establishing new connections over and over again.

**Comment by dbemiller** [comment]
The main issue is that each "Prebid" is different, based on which adapters you build with.

AppNexus does host a few versions of Prebid on their CDN. A build with all the adapters is stored at `http://acdn.adnxs.com/prebid/not-for-prod/prebid.js`, and one with just the AppNexus & Prebid-Server adapters is at `http://acdn.adnxs.com/prebid/anx/prebid.js`. Version-specific builds with AppNexus & Prebid-Server are at versioned paths, like `http://acdn.adnxs.com/prebid/anx/0.26.0/prebid.js`

As you might have guessed by the `not-for-prod` path, we **don't** recommend that anyone use that build. Browsers, especially Mobile ones, take time to parse and execute javascript... so the latency improvements are lost during execution. If you happen to only use the AppNexus adapters, the version at `http://acdn.adnxs.com/prebid/anx/prebid.js` might help a bit.
