### ISSUE TITLE
How do I define an alias in modules.json?

### ISSUE THREAD

**Issue by joyofdata** [prebid/Prebid.js#1551]
This ...

```json
 {
   "appnexus": {
     "alias": "brealtime"
   }
 }
```

... used to do the trick in packages.json for previous versions. Now it's not working anymore.

I also tried ...

```json
 {
   "appnexusBidAdapter": {
     "alias": "brealtime"
   }
 }
```

... which doesn't work as well.

Any suggestions?

**Comment by dantarion** [comment]
I think you no longer have to. Aliases are now automatically active when you include the adapter it is based on. So including appnexus now includes all aliases. You can verify this by looking at the code at the end of https://github.com/prebid/Prebid.js/blob/master/modules/appnexusBidAdapter.js

I ran into this too after the build system change. If this information is incorrect then I am interested in the correct method as well. I think #1528 is asking the same question

**Comment by joyofdata** [comment]
Yes, it seems that aliases are now specified within the respective adapter's script. 

https://github.com/prebid/Prebid.js/blob/master/modules/appnexusBidAdapter.js#L224

This list is not extensive though - I added a line for "sekindo" and now it works.

By convention, though, software of same major version should not break compatibility.

**Comment by snapwich** [comment]
@dantarion is correct that aliases are now specified by the adapters themselves rather than in a .json configuration file.

@joyofdata Prebid.js has not reached a major version yet, hence you should still expect that breaking changes my arise.  Our versioning behavior is consistent with [semantic versioning](http://semver.org/) as you can see in rule 4.  We hope to reach a stable Prebid.js 1.0 soon and we do avoid backward incompatible changes where we can, but they will come up here and there and should be expected.
