### ISSUE TITLE
Prevent re-auction

### ISSUE THREAD

**Issue by orzilca** [prebid/Prebid.js#1557]
## Type of issue
Possible feature request?

## Description

I'm looking for a way to flag the page once an auction was sent, and then prevent the ability to re-send the auction.
I'm afraid some bots will try to run pbjs auction again and again.
Perhaps this functionality already exists and I'm missing it in the documentation...

### Expected results
Auction will be sent only ONCE per page no matter what.

Currently if one will run the following:
`pbjs.requestBids({
          bidsBackHandler: sendAdserverRequest
        });`
bid requests will be sent, again and again..

## Platform details

prebid 0.25

**Comment by protonate** [comment]
This is by design as some implementations want to call for another auction without a page reload, either to refresh ads or in a Single Page Application context. Each call to `pbjs.requestBids` will result in a new auction. Ad fraud detection would be an important consideration when selecting partners to bid on supply.
