### ISSUE TITLE
What is the way to know that some bid response was chosen as auction winner and was shown on the page?

### ISSUE THREAD

**Issue by EgArM** [prebid/Prebid.js#1642]
## Type of issue

Question

## Description

What is the way to know that some bid response was chosen as auction winner and was shown on the page? I want to write an analytics module that will allow me to know which bids was shown on the page, but when I look in logs on some sites which uses Prebid the event bidWon may be not fired at all. I know that i can inject my JS code into banners that will be shown in iframes or will be appended using appendChild function to track that bid was shown, but if someone will decide to show the ad not in iframe and just paste some image with link in dedicated div using innerHtml attribute i see no possibility to track that event, except sheduling some DOM tree searcher which sounds pretty insane. So maybe you could help me with this problem, please? I also don't want to be depended by 3rd party libraries like GPT or DFP

## Steps to reproduce

Go to http://dailycaller.com/?pbjs_debug=true and try to search bidWon in console log, it's not always there.

**Comment by aneuway2** [comment]
@EgArM this can be done by attaching an event to the `bidWon` event like the following:
```
pbjs.onEvent('bidWon', function(data) { 
    // A bid won in Prebid and in the DFP auction
    console.log(data);
});
```

The data object in that above example includes additional information like the div id, creative, size, etc

**Comment by aneuway2** [comment]
@rmloveland FYI on the above ^

**Comment by thewizarodofoz** [comment]
What about getting info for the winning bid in the `getUserSyncs` adapter function? I want to be able to return syncs based on the winning response.

**Comment by dbemiller** [comment]
@thewizarodofoz do you mean you want to return syncs based on which bid your server returned, or which bid won the overall prebid auction?

For the former, the second argument to that function is your server's responses. See [the docs](https://github.com/prebid/Prebid.js/blob/master/src/adapters/bidderFactory.js#L50).

For the latter, it's not supported (yet). We'd have to think about it.

**Comment by thewizarodofoz** [comment]
@dbemiller I'm talking about which bid won the overall prebid auction (in case it was one of my bids of course).

**Comment by dbemiller** [comment]
gotcha, ok.

By the [code of conduct](http://prebid.org/wrapper_code_of_conduct.html#data-and-transparency) bidders aren't allowed to get info about other bidders... so we can't just forward the winning bid from the auction.

That said, bidders _are_ allowed to know _if_ their bid won (as well as _which_ bid won, if they made multiple bids).

If you need that feature urgently, I'd recommend making a PR (separate from your adapter submission, and based against the 1.0 branch) for it. Otherwise someone will get to it as priorities allow.

**Comment by mkendall07** [comment]
@thewizarodofoz can you describe the use case in detail for wanting this information? (ie how it impacts the user sync behavior?).

**Comment by thewizarodofoz** [comment]
@mkendall07 Actually I got a bit confused. I apologize. 
Since Prebid.js allows me to put sync pixels, regardless of whether my bid won or not, I don't really care who won.

**BUT** (shifting the discussion a bit):
When the bid request shoots from the user's browser to our server, it will be sent with our cookie, containing relevant user info. If this is the first time we meet a specific user, he will not have our cookie, and we will not have his info. Only after the first bid request sent from this user's browser, we will be able to put our sync pixel in (through Prebid.js). This means we will always be un-synced the first time we meet a user. 

Could there be a way to sync before making the bid request?

**Comment by mkendall07** [comment]
@thewizarodofoz 
No, we want user syncs to happen later as to not add latency to the prebid auction. This was the reason we added the user sync module. Thanks.
