### ISSUE TITLE
Example Code Questions

### ISSUE THREAD

**Issue by ericperez** [prebid/Prebid.js#171]
In the Example code on the [main repo page](https://github.com/prebid/Prebid.js#example-code) it appears that there is an assumption that a 'head' tag/element will always exist. My understanding is that newer browsers will always make the head element available, even if it isn't explicitly in the markup but that some older browsers do not do that.

The line: `target.insertBefore(pbs, target.firstChild);` will throw an exception if 'target' comes back as undefined. Also, I'm not sure if it's worth a pull request but variable 'd' references 'document' in that script but on line 5, 'document' is explicitly referenced, not 'd.'

Lastly, does anybody have any thoughts on using protocol agnostic URLs for the script 'src' attribute: e.g. "//cdn.example.com/prebid.min.js" which will inherit the protocol of the current document instead of having to determine the protocol programmatically? I guess it depends on which browsers are being targeted as very old browsers like IE6 do not support this.

**Comment by mkendall07** [comment]
Thanks for the comment/issue. I think we can tweak the insert block to insert on itself (the script element) instead of the head to address concern 1. For the protocol decision, I'm not sure which browser support inheriting the protocol automatically. Currently Prebid.js is tested in modern browsers and IE9+. I think these probably support that, so it might be worth a change.

**Comment by mkendall07** [comment]
This is resolved.
