### ISSUE TITLE
response headers are required but missing in interpretResponse

### ISSUE THREAD

**Issue by francoroy** [prebid/Prebid.js#1742]
Hi, at:
https://github.com/prebid/Prebid.js/blob/be21952ee1ffa8f183f718f63d612b6cfdb84908/src/adapters/bidderFactory.js#L274
The response body is sent back to the adapter, while in some cases additional response data is required, for example - in mobfox adapter, the bid value is returned as a response header.

Any rejections to adding the response headers as a third parameter (so that it'd be optional and non-breaking for those who've already implemented their new adapter) ?

Thanks

**Comment by dbemiller** [comment]
This is a good point.

I chatted with @mkendall07 about this, and we agreed that it's so early that breaking the API to keep it clean is a good idea.

I'll work on this early today, and we'll try to rush a review so that we can merge it in later. There aren't _too_ many 1.0 adapters in yet... so it won't be hard to update them.
