### ISSUE TITLE
Out of page inventory/non-standard sizes

### ISSUE THREAD

**Issue by samuelhorwitz** [prebid/Prebid.js#1764]
## Type of issue
Feature

## Description
Is there any chance it would be possible to specify strings that do not conform to `<width>x<height>` syntax? Such as `out-of-page` sizes?

**Comment by mkendall07** [comment]
anyone know what the convention is here? How does DFP handle it?

**Comment by YOzaz** [comment]
Basically, it's an ad unit, which doesn't have size set - and has slightly different definition syntax: https://support.google.com/dfp_premium/answer/6088046, https://developers.google.com/doubleclick-gpt/reference#googletag.defineOutOfPageSlot.

Other than that, it's pretty much the same like in "general" `1x1` ad units - call to `display()` and `refresh()` works, size (after render) can be left untouched - as out-of-page ad units either don't need resizing, either will resize themselves.

Typically, video players are served into this - e.g. SpotX. And while it's compatible with `1x1` size, by definition it should be out-of-page.

Technically, Prebid.js can implement this by allowing to omit "sizes" array (I think), or declaring special value like "outofpage". Out-of-page ad units and general ones can't be combined into one bid, as GPT definitions are different.

The only caveat would be including this size into creative overrides - "Third party" creatives can't overwrite Out-of-page size, only "Custom" creatives can.

**Comment by EM-LuisGalaz** [comment]
Hi, so does this mean that currently there is no possibility of having 0x0 or 1x1 sizes (Out of page) with delivery on prebid?

**Comment by YOzaz** [comment]
@EM-LuisGalaz there is, I think. Technically they're not much of different from standard units - at least, from Prebid point of view.

**Comment by EM-LuisGalaz** [comment]
@YOzaz , thanks for the reply.

But how would the bidder need to set the inventory? 
What I mean is, at the moment of making the call to prebid you need to specify which slots you want to get the available inventory for, as in:
____
 var adUnits = [{
            code: 'home_adoop', <-- code on page
            sizes: [
             [320,100], [300, 250], [300, 600], [320, 50]
            ] <-- sizes that you want to get available inventory from the bidders,
            bids: [
                {
                    bidder: 'appnexus',
                    params: {
                        placementId: 7485715
                    }
                }, ...
____

Also, as I have been able to understand, the bidders will give you the params depending on the domain that the inventory is targeted for and the slots targeted (and thats why you specify the slots in the adUnits request).  

Assuming I am right, what kind of slot must the bidder use to specify the inventory, and what slot size would I be requesting?

I have a bidder that sent the params for some interstitial ads (Out of page) and I'm supposed to use the 0x0 slot size for them. However, no bids are returned:
...
            sizes: [ [0, 0] ], 
...
 {
                bidder: 'undertone',
                params: {
                    publisherId: 3374,
                    placementId: '3374001'
                }
            }
....

I have also made countless tests with other bidders, other slots (non out of page, like 728x90), and using parameters where I know the bidder got things right. All that works well. 

Am I totally wrong in my assumptions? Could you share any insight into what you think could be wrong?

**Comment by YOzaz** [comment]
Hi @EM-LuisGalaz! See my replies below:

> But how would the bidder need to set the inventory?

From DFP perspective, out-of-page ad units are delivered as `1x1` creatives, or doesn't have any size at all (therefore any size should work).
From Prebid.js perspective, I don't see that `sizes` array should have any impact for making bids or resolving creatives, so it totally depends on bidder adapter implementation. You should contact `appnexus` or `undertone` support what size you should send, as I believe that's their side which is not catching up creative size and not responding correctly. I would also double-ensure placement is compatible with HB process in general (had this issue with AdYouLike before, when was trying to re-use old non-HB placements with Prebid.js process).
But - after response, Prebid.js library does automatic creative resizing though, regardless what size it had before request in `defineSlot` or `defineOutOfPageSlot`  configuration: https://github.com/prebid/Prebid.js/blob/master/src/prebid.js#L67. So - again - it should work with standard and out-of-page ad units, as at the end - it's an IFRAME anyway.

> Also, as I have been able to understand, the bidders will give you the params depending on the domain that the inventory is targeted for and the slots targeted (and thats why you specify the slots in the adUnits request).

That is correct, that's why you're setting up different `placementId` variable value for every ad unit element (DIV) on a page, if you're serving through DFP.

> Assuming I am right, what kind of slot must the bidder use to specify the inventory, and what slot size would I be requesting?

Looking at your code - from my understanding, rules should be the same:
* `sizes` array should have `[1,1]` size declared,
* `code` should match `DIV` element ID or ad unit name - it should resolve in any case, unless you have multiple ad units with same name but different IDs on the page (for latter, you must use element ID then). See how it works in here: https://github.com/prebid/Prebid.js/blob/master/src/targeting.js#L42.
* `bids` should be standard like in "normal" case.
* Line Items with pbjs.renderAd() creative in DFP should target out-of-page inventory size.

Note: out-of-page creatives require custom HTML tag to be implemented, therefore you must fire impression trackers yourself: https://support.google.com/dfp_premium/answer/2376981#viewed.

> I have a bidder that sent the params for some interstitial ads (Out of page) and I'm supposed to use the 0x0 slot size for them. However, no bids are returned.

See above - I think you need to send `1x1` instead.
Additionally, make sure bidder is not responding at all - use debug function to see what bids are being returned. It is possible, that you don't have DFP creative set up for key-value targeting. This case is not documented well, but I think - in DFP line items for price buckets, you must create out-of-page creatives instead of `1x1` (as that's how your original ad unit is declared).

> Lastly, does the bidder need to set their inventory live in order for them to respond to the request from prebid with actual bids?

Unless bidder has a "test" mode implemented (like Sharethrough), usually they indeed need to set it live. Testing in Prebid.js is troublesome in general. Sharethrough has a way to force their bids return very high CPM value for testing (through Switcheroo Chrome plugin), not sure about others.

**Comment by EM-LuisGalaz** [comment]
@YOzaz , thank you very much for your quick reply.

I will contact undertone to see why they suggested using a 0x0 slot, there might be some confusion with their implementation since I think this is the first test of their bidder adapter. It could also be that the key value targeting is incorrect. 

Thanks, I have a lot of things to check for debugging this problem.
