### ISSUE TITLE
AST Adapter: Piggyback pixels not attached to native ad object

### ISSUE THREAD

**Issue by hlauinfo** [prebid/Prebid.js#1912]
## Type of issue
Bug

## Description
Piggyback pixels set up in the AN placement manager are not included in the native ad object.

## Steps to reproduce
Placement 12528217 has been set up as a test

## Test page
https://jsfiddle.net/samsarra/sp7yz9g8/ (AST not returning valid bids in jsfiddle)

### Expected results
Should include http://ib.adnxs.com/seg?add=10889912&t=2 (which is attached to the placement as a piggyback for the purposes of testing) in native object as an impression tracker

### Actual results
Piggyback pixel doesn't fire

## Platform details
0.33.0

**Comment by mkendall07** [comment]
Thanks for the bug report. I don't think the endpoint is returning us the piggyback pixels so we'll need to make a feature request to have the backend updated.

**Comment by mkendall07** [comment]
@hlauinfo 
Can you check placement `12528217` for the piggyback pixel? I don't see it.

**Comment by hlauinfo** [comment]
@mkendall07 that's weird. it disappeared. I've added it back in.

**Comment by hlauinfo** [comment]
@mkendall07 is there an update on this? thanks

**Comment by manigandham** [comment]
@mkendall07 

Is there an update or someone else we can contact about this bug? It's definitely not stale and I don't understand why the bot tagged as 'wontfix'

**Comment by mkendall07** [comment]
I'll take a look tomorrow

**Comment by manigandham** [comment]
Following up here, documenting the latest from our AppNexus case:

It seems the piggyback pixels for native placements have been added but there are new issues:

1. The pixel is being added to the `javascript_trackers` array in the prebid response, even though it is not a javascript tag but an image pixel.
2. The `javascript_trackers` array has now been turned into a single property for the pixel, which breaks any code that is looking for an array containing 1 or many pixels.
3. The `javascript_trackers` property is not accounted for at all in prebid.js so that wrapper will not fire these piggyback pixels at all.

**Comment by jsnellbaker** [comment]
This was fixed by https://github.com/prebid/Prebid.js/pull/2487

Closing this issue.
