### ISSUE TITLE
Creating empty bid objects for "No bids" responses

### ISSUE THREAD

**Issue by vzhukovsky** [prebid/Prebid.js#2035]
## Type of issue
Question

## Description
Hi guys. I have a question about handling empty bid responses.

In Prebid 0.X.X we had a functionality for creating empty bid objects for all "No bids" responses (`fillNoBids` method in `bidderFactory` module). But as I can see it has removed since Prebid 1.0 release. We used this feature to distinguish between available bids and no bids for collecting analytics.

Is there a way to replicate the old behavior in Prebid 1.0?

**Comment by snapwich** [comment]
We did this in an effort to simplify the adapter architecture.  Rather than submit no_bids for all possible slots to signal non-participation an adapter needs now to only do nothing.  Non-participation could still be inferred in analytics by hearing a `bidRequested` event for a bidder with no `bidResponse` from that bidder before the `auctionEnd` event (and not getting notification of a `bidderTimeout` with them included).

**Comment by matthewlane** [comment]
Closing as answered
