### ISSUE TITLE
Error processing command : Cannot set property 'innerHTML' of null TypeError: Cannot set property 'innerHTML' of null

### ISSUE THREAD

**Issue by PayteR** [prebid/Prebid.js#2113]
## Type of issue
Bug, i supose...

## Description
After `Invoking pbjs.getAdserverTargeting` in console there is this JS error:
`Error processing command : Cannot set property 'innerHTML' of null TypeError: Cannot set property 'innerHTML' of null`. I don't now why, i run out of options. Version is v0.34.2 with 2 adapters, and i don't have possibility to update, because i need to use **adform** and **criteo** adapters, which are missing in 1.\*.\* versions. 

![image](https://user-images.githubusercontent.com/1248565/35924979-cb7184d8-0c24-11e8-8530-f42289ed4702.png)

## Steps to reproduce
Please visit test link here http://isita.sk/prebid/webnoviny.html?pbjs_debug=true&dfpdeb, debug params are already included in url.

## Test page
http://isita.sk/prebid/webnoviny.html?pbjs_debug=true&dfpdeb

Thank you!

**Comment by matthewlane** [comment]
I think the issue is that there aren't any elements on the page with the id `container`, so 

```JavaScript
var container = document.getElementById('container');
```

sets `container` to null, and then

```JavaScript
container.innerHTML = JSON.stringify(targetingParams);
```

throws the error. Creating an element with an id of `container` should fix it. You can also check that `pbjs.getAdserverTargeting` is working by doing something like this and then looking for the `targetingParams` output in the console

```JavaScript
var targetingParams = pbjs.getAdserverTargeting();
console.log('targetingParams', targetingParams);
// var container = document.getElementById('container');
// container.innerHTML = JSON.stringify(targetingParams);
```

**Comment by PayteR** [comment]
Thank you @matthewlane, creating `<div id="container"></div>` helped, and i see targeting params there!

Is this a bug, or is this somewhere in documentation?

**Comment by matthewlane** [comment]
It's not a Prebid bug because `pbjs.getAdserverTargeting` was working as expected. The issue was due to `document.getElementById` referencing a non-existing element. That function is part of the standard web api, and a good resource for the web api is [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript). These pages will have documentation for the functions and properties you are using:
https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById
https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML

**Comment by PayteR** [comment]
Ok, this issue is not prebid.js related, closing. Thank you.

**Comment by mavirt** [comment]
I keep getting that error and I dont know what Im doing wrong

 function user1(name1, like1, dislike1,class1){
    document.querySelector(class1).innerHTML("Hi my name is "+name1+", and my favorite candy is "+like1+".");
    document.querySelector(class1).innerHTML("Hi, the name is "+name1+" and "+dislike1+" is terrible!");
  }
user1(".div1");

**Comment by wqi1972** [comment]
change the code to
```
document.querySelector(class1).innerHTML = "Hi my name is "+name1+", and my favorite candy is "+like1+".";
```

**Comment by mavirt** [comment]
only one line is printing out and I need both sentences to print

function firstUser(){
    document.querySelector(class1).innerHTML = "Hi! My name is "+name1+", and my favorite candy is "+like1+".";
    document.querySelector(class2).innerHTML = "Hi! My name is "+name2+", and my favorite candy is "+like2+"."
  }
firstUser(".div1");
firstUser(".div2");

**Comment by proxybee** [comment]
There are different possible cause as discussed would just like to add this for someone who might have the same issue as mine.

In my case I had a missing close div as shown below

```
   <!DOCTYPE HTML>
   <html>
   <head>
   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
   <title>Untitled Document</title>
   </head>
   <body>
   <div> //I am an open div
    <div id="hello"></div>
   <script type ="text/javascript">
       what();
       function what(){
          document.getElementById('hello').innerHTML = 'hi';
       };
   </script>
   </body>
   </html>
```

Missing a close div can result in disorganization of the transversal from child to parent or parent to child hence resulting in an error when you try to access an element in the DOM
