### ISSUE TITLE
Prebid 1.x+ - what happened to IndexExchange?

### ISSUE THREAD

**Issue by cwbeck** [prebid/Prebid.js#2162]
It would seem a major SSP is missing from Prebid 1.x+? Do we know when the IndexExchange adapter will make an appearance?

**Comment by chefbenjamin** [comment]
The latest I heard from the Index team them is that its on track for release in April.

**Comment by terebentina** [comment]
Do you have a list with the latest known status of all modules for 1.x? I am particularly interested in spotx but would be nice to know when/if we can expect them to upgrade their modules for 1.x.

**Comment by chefbenjamin** [comment]
@terebentina best way to do this is to look at the downloads page here http://prebid.org/download.html and choose the select Prebid version dropdown to 1.31. as of right now, spotx isnt listed on this page.  I would suggest reaching out to them and getting an ETA

**Comment by terebentina** [comment]
Oh, sure, I am even checking master every other day :) Great work with 1.x, btw! IndexExchange isn't there either so I was thinking that maybe you have more insider news for other modules, like with IE, above.

**Comment by mkendall07** [comment]
We are actively working with IndexExchange and others (Criteo) to get official support for Prebid 1.x soon. Thanks for your patience.

**Comment by cwbeck** [comment]
@mkendall07 it's not your fault they are being slow. We're just waiting now before we can upgrade. There is no major rush though.

**Comment by GeneGenie** [comment]
Index has their own HB wrapper, so they may slow down intentionally. Also prebid 1.x architecture requires bid request to be a valid XHR with JSON response, so index has to change their server solution as well, same goes for criteo. 

Anyway, @cwbeck, you can apply just a few changes to existing adapter to make it work in prebid 1.x 

1. callBids method is passing addBidResponse callback  that can be used instead of bidmanager.addBidResponse.
2. placementCode should be replaced with adUnitCode
3. bidResposne objects should contain all (newly) required properties: ttl,currency, netRevenue, creativeId, you can hardcode those on your own risk.

**Comment by eliseumds** [comment]
https://github.com/prebid/Prebid.js/pull/2496 was merged.
