### ISSUE TITLE
Bids are refreshing auto after 30 sec

### ISSUE THREAD

**Issue by yogeshadsparc** [prebid/Prebid.js#2178]
Hi,

Is anybody know, why my bids are refreshing after every 30 sec? is there any inbuilt functionality is included in prebid js? if yes then is there any way to increase the same?

Please help.
Regards,
Yogesh

**Comment by mkendall07** [comment]
Should not be any auto refresh functionality built into prebid.js. Make sure it's not DFP doing this.

**Comment by erdalmercan** [comment]
There are some "ad networks" which are supported nicely by some "ad exchanges" who is defining their selves as "European giant" or "Full Stack Technology Provider" are allowing such "legal within contract" activity of refreshing. 

May be you are working with one of the ad networks which is refreshing bids agressively? 

An example screenshot of Google Chrome's network tab attached to this post. For example it's been 150 SECONDS since page load, but there are still buyers on the page via prebid. Which is quite strange allowance by tech providers, DSPs or Ad Exchanges. There is not any limit for this ad network. Strange...

screen shot:
![image](https://user-images.githubusercontent.com/36709239/36505953-0e925052-174d-11e8-8a9a-d7787c23c32b.png)
