### ISSUE TITLE
uuid is undefined in prebid cache

### ISSUE THREAD

**Issue by Roffray** [prebid/Prebid.js#2253]
## Type of issue
Question

## Description
I've taken the videojs demo page from the documentation to test our own adapter (vuble).
The problem is, when the adapter sends back an ad for DFP to play, the uuid in prebid url cache is "undefined" : https://prebid.adnxs.com/pbc/v1/cache?uuid=undefined because the hb_uuid sent to DFP is undefined too.

## Steps to reproduce
Go in this link : http://demo.vuble.tv/headerbidding/videojs.vuble.html?pbjs_debug=true wich is setup to call our adapter.

## Test page
http://demo.vuble.tv/headerbidding/videojs.vuble.html?pbjs_debug=true

### Expected results
Whenever the adapter sends back an to play, we should be able to get DFP to get the vast from prebid cache.

### Actual results
The hb_uuid sent to DFP is undefined, therefore the prebid cache url set up in DFP is not able to get the vast.

## Platform details
I'm testing on Chrome 65.0.3325.146, with the latest prebid version (created with gulp serve).

Am I doing anything wrong or missing anything here ?

Thank you,
Geoffray

**Comment by Roffray** [comment]
You'll have the same issue here with this time the appnexus bidder : http://demo.vuble.tv/headerbidding/videojs.html.

Geoffray

**Comment by matthewlane** [comment]
Hi @Roffray, for the second example page with the appnexus bidder, you should be able to get a uuid by setting

```JavaScript
pbjs.setConfig({ 
  cache: { url: 'https://prebid.adnxs.com/pbc/v1/cache' },
});
```

and for vuble, it looks like a uuid isn't getting set because the vuble [bid response object](https://github.com/prebid/Prebid.js/blob/master/modules/vubleBidAdapter.js#L96) doesn't contain a `mediaType` field set to `'video'` ([docs link](http://prebid.org/dev-docs/bidder-adaptor.html#step-3-respond-with-a-vast-url-or-raw-vast-xml)). If you add that locally and it works out please submit a PR and we'll merge it

**Comment by Roffray** [comment]
Thank you for your answer :)

Here is the PR : https://github.com/prebid/Prebid.js/issues/2253
