### ISSUE TITLE
Allow bidders to subscribe to own timed out bid data

### ISSUE THREAD

**Issue by matthewlane** [prebid/Prebid.js#2254]
## Type of issue
- Feature request

Add a function to the bidder spec definition that is called when a `BID_TIMEOUT` event occurs. Similar to `pbjs.onEvent('bidTimeout', (data) => ... )`, but the payload contains only the timed out bids for the subscribed bidder rather than all timed out bidders.

**Comment by ruturajv** [comment]
Thanks for filing this.

This event could be called `adapterBidTimeout` where the data can be already filtered for the given bidder, So that it doesn't conflict with the existing event used by Analytics Adapters.

The callback could have following data points
- bidder timeout setting (`bidderTimeout`)
- adapter's bid / no-bid response time (could fire this event something like after `bidderTimeout`. ie.  `3580`. If response doesn't come through even after this window, perhaps a `null` or something that doesn't pollute when averaging out this number.)
- Bid Request's POST body

**Comment by vedantseta** [comment]
Hi all,
Instead of adapters registering to events via `pbjs.onEvent('adapterBidTimeout', (data) => ... )` , this can rather be a callback to a public function `logTimeouts` in bidder spec, similar to `getUserSyncs` with the params as mentioned by @ruturajv 

Let me know your thoughts @matthewlane @ruturajv ? 

will pick this up.

**Comment by matthewlane** [comment]
@vedantseta Right, i should have written the original description in a different way but was meaning that this would go in a bidder spec file just as you've mentioned, alongside the functions `getUserSyncs`, `interpretResponse`, `buildRequests`, etc, and receiving the same data as the `BID_TMEOUT` event but filtered for that particular bidder. Pull requests gladly accepted!

**Comment by vedantseta** [comment]
@matthewlane , along with data received in `BID_TIMEOUT` event, the publisher configured params for that bidder-slot combination should also be passed too.
