### ISSUE TITLE
Mutually exclusive label sets not working as expected

### ISSUE THREAD

**Issue by kelvin-chappell** [prebid/Prebid.js#2263]
## Type of issue
Bug

## Description
When applying two mutually exclusive sets of labels, the resulting bid request has an unexpected number of bids.

## Steps to reproduce
See below.

## Test page
https://gist.github.com/kelvin-chappell/1abc8d5ce7273aa932156c28745b1821

### Expected results
A single bid matching the ad unit whose labels are active.

### Actual results
Two bids, one matching the ad unit whose labels are active, and the other matching the other ad unit whose labels are not active. 

## Platform details
Prebid 1.6.0-pre

## Other information
N/A

**Comment by bretg** [comment]
@kelvin-chappell - the empty `labelAny: []` and `labelAll: []` may be the issue here.

Please try this example removing the attributes with empty arrays.

The semantics of an empty array here may be the issue -- apparently you're expecting empty to mean "ignore this attribute", but at least labelAll with an empty array could be interpreted as automatic inclusion.

**Comment by kelvin-chappell** [comment]
@bretg thank you.  You're quite right.  If I omit the `labelAll` value on ad unit _u2_ the failing test passes.

Would it be possible to give a warning if `labelAll` on an ad unit or bid is set to an empty array?
In fact, if it's never valid, perhaps an error?

**Comment by bretg** [comment]
Sure - will see if we can get someone to add that log entry and will update the documentation.

**Comment by kelvin-chappell** [comment]
Great! Thank you.

**Comment by bretg** [comment]
Closing issue as it's now documented.
