### ISSUE TITLE
Size mapping not working for outstream adunit

### ISSUE THREAD

**Issue by sajokj** [prebid/Prebid.js#2276]
## Type of issue
Bug

## Description
If we have 4 adunits on a page, in which 3 adunits are just banners and 1 with outstream, the Size mapping /sizeConfig will not work for outstream. When requesting for bid the outstream adunit is always ignored. If I remove the sizeConfig and labels it works fine.

## Steps to reproduce
Have a page with 2 adunits one with banner another with Outstream and enable Size mapping /sizeConfig

### Expected results
Both Outstream and Banners should work with Size mapping /sizeConfig

## Platform details
Prebid.js 1.4.0

**Comment by bretg** [comment]
Please post an example sizeConfig and AdUnits that illustrate the problem

**Comment by sajokj** [comment]
Here is the code:
https://jsfiddle.net/8L2n2v3j/1/

**Comment by jsnellbaker** [comment]
Hi @sajokj I have put together a fix for this bug.  Once it's reviewed and merged, it should be included in the next corresponding 1.x release.  

As part of the fix, you'll need to update your adUnit config so that `mediaTypes.video.playerSize` is using a syntax like `[[640, 480]]` instead of the previous `[640, 480]`.  This syntax update should allow the video adUnit to work with the Size Mapping functionality properly.  Please let me know if there are any questions.

**Comment by sajokj** [comment]
Thank you @jsnellbaker for the Fix

**Comment by sajokj** [comment]
@jsnellbaker is this live on production on the Prebid ver 1.6.0

I cant find the same on change log.

**Comment by jsnellbaker** [comment]
@sajokj This fix is still within a Pull Request (ie review) status and has not been implemented.  Once it's reviewed/merged into the master branch, it will available with the next prebid release.
