### ISSUE TITLE
Bug on requestBids trying to implement ad refresh for SPA

### ISSUE THREAD

**Issue by ialex** [prebid/Prebid.js#268]
You can see that the bid back handler function is executed just once for the last bid, so it will not load the bids for both ads at the same time:

http://jsfiddle.net/dovske0f/9/

**Comment by protonate** [comment]
I [updated](http://jsfiddle.net/dovske0f/10/) the jsfiddle to remove the pubmatic bidder on adUnit `div-gpt-ad-1438287399331-1`. It was set with placeholder params that resulted in a TypeError in bidmanager.js. 

Then, `refreshBid1()` and `refreshBid2()` are called on script load, and each function calls requestBids which calls `resetBids`, so the first `requestBids` response objects gets clobbered. These refresh functions work as expected as the button onclick handlers since only one bid request at a time is taking place.

A third function to request bids for both ad units on script load should address this I think. Improved SPA support is needed and on the roadmap. Let me know if this clears things up.

Here's the updated fiddle: http://jsfiddle.net/dovske0f/10/

**Comment by renebaudisch** [comment]
I contribute to #259 and just saw [this fiddle](http://jsfiddle.net/dovske0f/9/), but i don't like the fact that yo uhave to generate a function for each slot since you cannot pass variables to que.push-function and the only thing that changes is the sot-id. I would like to have a more generic way...

**Comment by ialex** [comment]
#338 should fix the issue described here as soon as it is merged.

**Comment by mkendall07** [comment]
This is resolved via a hard limit of 1 request running at a time. We opted not to allow concurrent request because of performance considerations. In the future we may allow multiple requests and queue them internally.
