### ISSUE TITLE
Prebid timeout of 10 seconds is still honored if gdprApplies:false is sent

### ISSUE THREAD

**Issue by tpottersovrn** [prebid/Prebid.js#2720]
## Description

The IAB CMP Stub is causing prebid to wait for the default timeout until loading ads. Even if gdprApplies is passed in before prebid is fired. We have verified that the CMP is passing the gdprApplies:false flag. It appears that prebid is ignoring the flag and only looking at the iab stub.

If we set the timeout to '0' then run an auction then gdpr is set to null on the first run.

## Steps to reproduce

Attach the IAB CMP Stub to the top of the <head> of the page and have the cmp on the next script loaded then load prebid and there is no CMP showing for a non-EU reader. The auction is not being held until the default timeout is reached. 
### Expected results
If the reader is not within the EU and gdprApplies is set to false then the auction should be held immediately with no timeout.
### Actual results
The auction is being suspended until the timeout is reached for CMP being detected on the page.

## Platform details

Prebid 1.11.0
Chrome V: 66.0.3359.139/ OSX 10.13.4
npm: 4.3.0

**Comment by jsnellbaker** [comment]
@tpottersovrn Thanks for reporting this issue.  I'll do some digging.  

If you have a test page with the CMP already setup to pass in false for `gdprApplies` for non-EU users, can you please share/link it here so I can be sure the fix is working in your scenario?

**Comment by tpottersovrn** [comment]
@jsnellbaker I'll see if I can get something that is external facing

**Comment by jsnellbaker** [comment]
@tpottersovrn I put together a fix that I believe should address the issue.  see #2723

I would still like to give it a try with your test page if possible; alternatively if you want to check out the branch and give it a try yourself - please let me know if it works.  

Please note - this depends on how the CMP is configured when the `gdprApplies` is passed in as `false`.  If the CMP knows to immediately respond to requests to its API with `gdprApplies` as `false` and the other consent fields as `null`, then this fix should help.  When the module sees `gdprApplies` is set to `false`, it will skip the checks we normally do on the CMP response and proceed as normal.

If the CMP is configured to wait for consent information before responding to any requests to the CMP API, then this fix won't address that workflow.  The module is reliant on the CMP to respond so that it can process the potential consent information for the end-user.  The CMP may be waiting because it thinks there may be a user interacting with the consent UI; thus it thinks it should hold any requests to its API in order to provide that pending consent information.

**Comment by tpottersovrn** [comment]
So I have tested this with the fix and it appears that it is still not picking this up. From what we are seeing it appears that if a pubs cmp is embedded into the page it could take up to 500ms to load. The reason that prebid is detecting a cmp is that the lab cmp stub is in the head of the page.

**Comment by jsnellbaker** [comment]
@tpottersovrn Were you able to put together a public-facing page that I can review?  I'd like to look into what you're seeing more.

The stub is meant to queue any CMP requests until the CMP is loaded.  After which it should promptly respond to those requests (assuming it knows what to respond with).
