### ISSUE TITLE
documentation for pbjs.setConfig.consentManagement

### ISSUE THREAD

**Issue by tsanders42** [prebid/Prebid.js#2745]
## Type of issue
Please add documentation for consentManagement to http://prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.setConfig

## Description
The use of 'cmpApi' isn't clear to me: what value should be used for a non-iab cmpApi?
Clearly this isn't the CMP id, but then what should it be?

**Comment by jsnellbaker** [comment]
Hi @tsanders42,

Thanks for reaching out.  Module-based config information is normally organized under the main page for that module.  In the consentManagement's case, it's this page:
http://prebid.org/dev-docs/modules/consentManagement.html

The `cmpApi` field represents what type of CMP API requests should be executed to communicate with the CMP on the page.  The `iab` code tells Prebid to execute IAB style CMP requests.  
For any potential future options, we will be sure to document them on the above page so you know what to use; `iab` is the only available option currently.

In regards to your case on using a non-IAB CMP, there is a [section](http://prebid.org/dev-docs/modules/consentManagement.html#publishers-not-using-an-iab-compliant-cmp) that may be worth a look (if you haven't looked already).  It basically covers the setup to create a local function that adheres to the IAB CMP standard and will act as a mediator between Prebid and the non-IAB CMP.

With this code sample, you can set the `consentManagement.cmpApi` object to `iab` since there will be an object available to interpret/handle the IAB CMP requests made by Prebid.
