### ISSUE TITLE
PBS index adapter and PBJS index adapter require different type for the same param

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/Prebid.js#2851]
## Type of issue
Bug

## Description
According to this https://github.com/prebid/Prebid.js/blob/master/modules/ixBidAdapter.md ix parameters include siteId that must have type string. PBS adapter for indexExchange requires parameter siteID (note the register of the last letter) that has type integer. Obviously, the requirements are incompatible

## Steps to reproduce
1) Add ix bidder under the alias of `indexExchange`, setup it to work with PBS.
2) Somehow prevent PBS adapter from sending the list of aliases to prevent https://github.com/prebid/Prebid.js/issues/2717
3) Run an auction

### Expected results
PBS sucessfuly processes request

### Actual results
```
Invalid request: request.imp[0].ext.indexExchange failed validation.
siteID: Invalid type. Expected: integer, given: string
```

**Comment by hhhjort** [comment]
Do we know if there are non-Prebid.js users of the current PBS `indexExchange` adapter? Especially if it is something like the mobile SDK, it could result in us needing to keep the old adapter around for a long time. Still it is likely a second adapter in PBS is the least horrible way of resolving this issue.

If we suspect that the old adapter will need to be supported long term, I would recommend coding the new adapter, then writing a wrapper for it to implement the old interface for the current adapter, so that we are not maintaining 2 instances of the adapter for the duration. If we can retire the old one before maintenance work is likely, then we shouldn't need to do the wrapper solution.

**Comment by mkendall07** [comment]
I'd prefer to fix this in prebid.js. Even if we add a s2s adapter for `ix` that only fixes it for Index, no other S2S aliases will work right. 
A short term fix would be to just add a copy of `ix` here: https://github.com/prebid/Prebid.js/blob/master/modules/prebidServerBidAdapter.js#L219

And the long term solution would be to add support for converting types in prebid.js for S2S aliases.

**Comment by mkendall07** [comment]
ah ok. I missed that detail - thanks for pointing it out.

**Comment by akira28** [comment]
Is there any news on this issue? Any reason why the PR with the workaround was closed? Any other workaround without having to modify Prebid code?

Thanks!

**Comment by bretg** [comment]
There's an issue over on Prebid Server -- https://github.com/prebid/prebid-server/issues/657

Suspect that's why the PBJS-based solution was closed

**Comment by bretg** [comment]
There's activity on the Prebid Server side that will solve this -- https://github.com/prebid/prebid-server/pull/712

**Comment by mkendall07** [comment]
@dmitriyshashkin 
FYI this went live today on AppNexus Prebid Server => http://prebid.adnxs.com/pbs/v1/info/bidders
