### ISSUE TITLE
Kargo adapter bug in bid to ad matching

### ISSUE THREAD

**Issue by andyblackwell** [prebid/Prebid.js#2873]
## Type of issue
BUG

## Description
When using a single placementId and more than one ad per auction, this adapter has no way to properly match a bid response to the correct ad from the request.

## Steps to reproduce
Use one placement id on multiple ads in an auction. Easiest way would be to alter the unit test to not use two unique placement on the two dummy ad calls.

## Test page
n/a

### Expected results
One placement Id could be used for multiple ads in an auction, and the resulting bids or no-bids be matched properly to the ads that requested them.

### Actual results
If using one placement Id with multiple ads, only one bid can be returned and it would only match the last ad in the auction.

## Platform details
all iterations of this adapter, from pre-1.0 introduction to the current version

## Other information
In the bid request api call, the only unique identifier used is their placementId.
On response they use only the placementId to match each bid to the proper ad, but the placementId is the key in that object so is unable to handle more than one bid per placementId.
If there are multiple ads in an auction and only one placementId used, then there is no way to properly match a bid response to ad. One will be matched, but it may not be the correct one and looks like it would probably always match the last ad in the auction.
https://github.com/prebid/Prebid.js/blob/1.16.0/modules/kargoBidAdapter.js

The unit test uses two ads and two unique placement ids, so the bug does not present itself.
https://github.com/prebid/Prebid.js/blob/1.16.0/test/spec/modules/kargoBidAdapter_spec.js

We brought this to attention of our Kargo rep during onboarding where we were only supplied a single placementId, and are awaiting more unique placements as a temporary workaround. But as of now this adapter only handles one ad per auction for us.

Looks like this bug has been around since this adapter was first introduced. https://github.com/prebid/Prebid.js/pull/1316

So far my only idea is to force the adapter to send an api request for every bid, unless there is a way to send and receive another unique identifier for each bid in the single request.

@samuelhorwitz do you know if this is a limitation in the API as-is?

**Comment by samuelhorwitz** [comment]
Sorry for the delay in a response. I've been preparing for a business trip/traveling for the last few weeks. I've reached out to our sales engineers about this, but I believe our solution which they also will start to communicate is to use our multiple placement ID solution. This was something we have set up already for other adapters but it appears we will need to use it for Prebid integrations as well.

This solution basically is very similar to what you propose but the idea is that the unique ID is the placement ID not a new request specific one. Internally, we have a system that maps unique placement IDs to a single placement. Then, we can have a practically limitless multiplexing system of unique IDs to placements which solves this problem, assuming one placement per page.

When initially setting up our adapters, I don't recall a system to allow the same placement multiple times per page supported by the adapter APIs themselves. However perhaps this has changed since we last researched. So our solution was to have multiple external-facing placements that do not require duplication on our end. Furthermore, this solution allows us to internally specify things like placement ordering and other configuration options that may come up based not on ad slot details but actual placement instance.

Let me know if that doesn't make sense. Also I believe our sales engineers are in contact with you for further clarification and onboarding. I'm responding here as well for posterity and in case any Prebid devs have any suggestions or input regarding this issue.

**Comment by andyblackwell** [comment]
Thanks for the response!

Your explanation makes sense for the current setup, but prebid does support one placement per page for adapters, is how it has always worked. You'll just need your api to support it as well one way or another. 

We've seen these two main scenarios with other adapters in order to support:
1) include the bidIds in the request and return them with the responses in order to match
2) make sure that bids are always returned in a response (even if no bids), and return them in the same order as sent in the request, and match by bidRequest/bidResponse array index. (super hacky, but used by several adapters)

There should probably be a note in the docs about this adapter if it isn't going to change.

For now I guess we'll continue waiting for the multi-placements you spoke of from our reps.

**Comment by samuelhorwitz** [comment]
We are currently working on a solution for this implementing #1 where we return by bidId versus placement ID. I will link back to this in a PR once our backend solution is complete and I can submit the adapter change for review.

**Comment by samuelhorwitz** [comment]
See #2958
