### ISSUE TITLE
Better Adaptor for Criteo

### ISSUE THREAD

**Issue by prebid** [prebid/Prebid.js#3]
Anyone with a Criteo pre-bid spec, would love to get the adaptor updated with the latest implementation!

**Comment by ialex** [comment]
does the adaptor included in prebid.js works or not?

**Comment by prebid** [comment]
Hey @ialex, the Criteo adaptor helps the page make the Criteo request. However, because Criteo doesn't return the price, it doesn't really work well with the prebid.js model. The bidResponse.keys do contain the Criteo responses such as: ["top600=1", "right300=1", ...]. But the publisher needs to setup separate line items. 

What do you think would be the best approach for Criteo?

**Comment by ialex** [comment]
I mean there is nothing we can do to make them return their prices and allow a callback per bid, i mean we can request them to change their API to see what happens, i was checking CasalMedia adaptor dont return the cpm either.

**Comment by jdelhommeau** [comment]
I think we should be able to manage criteo adapter in a better way.
Proposed solution: publisher get paid a fixed cpm for criteo impression. Publisher could enter the CPM value, which we would use to prioritise. Down side of the solution is that publisher expose it's CPM. 
Another solution from a publisher would be that prebid.js only helps with retrieving the bids, and they all get sent to the adserver (vs only the winning one). That way publisher can easily manage any bid (with or without CPM value) from the adserver

**Comment by MadisonWickham** [comment]
We are close to adding Criteo into our Prebid implementation. I'm curious to hear feedback on the strategy we're planning to use.

Since Criteo only returns "Yes" or "No" our plan is to manipulate the response before the header auction occurs, turning "Yes" into a CPM value. We are going to set a relatively high floor price for each placement, say $5.00. Then we will turn the Criteo "Yes" response into "5.00" so that it can compete with the other demand sources at a specific CPM rate. If it wins, it'll pass into DFP and activate the prebid line item with key-value "hb_pb = 5.00"

Not a perfect solution, but it will ensure 100% fill and semi-reliable pricing competition with other demand.

Any thoughts on this?

**Comment by BartVB** [comment]
@MadisonWickham check out 'alwaysUseBid' in the bidder settings. This way you can send both the CPM winner to your ad server and Criteo when they want to take the impression. This way an $8.00 AppNexus bid will compete with your Criteo floor. An added advantage is that you can manage your Criteo floor price in DFP.

**Comment by prebid** [comment]
@jdelhommeau , do you mind help us put up some docs around integrating with Criteo in the Prebid.org [examples section](http://prebid.org/dev-docs/examples/basic-example.html)? This would really help publishers as the `alwaysUseBid` param is hidden in the References page. Thanks!

**Comment by jdelhommeau** [comment]
@prebid: sorry guys, I just now see those messages. Sure I will update the to reflect this. I think I already made an example of this under bidderSettings, advanced behavior. I will also add on criteo adaptor.
