### ISSUE TITLE
CurrencyConversion Issue

### ISSUE THREAD

**Issue by SimoneCrespi** [prebid/Prebid.js#3056]
Hi,
I have a issue with currency conversion. 
My DFP currency is $ and there is a bidder that give me a bidcpm in €
At the moment i have this error and aby keyvalue are passed to dfp
WARNING: Returning NO_BID, getCurrencyConversion threw error:  : params :  Error: Specified fromCurrency 'usd' not found in the currency rates file

Test page https://www.gqitalia.it/sport/motori/formula-1/2018/08/29/gp-monza-2018-news-e-pronostici-le-possibilita-della-ferrari/?pbjs_debug=true

Any idea to resolve this issue ?

thanks
Simone

**Comment by bretg** [comment]
I don't see this page loading the currency rates file. In order to initialize the currency module, you need to set your ad server currency at a minimum. And a default rate is highly recommended:
```
pbjs.setConfig({
    "currency": {
       "adServerCurrency": "USD",
       "rates": { "USD": { "EUR": 0.85 }, "EUR": { "USD": 1.15 }}
    }
});
```
I think this may work with Prebid-provided currency conversion file, but if not, you'll need to settle for a constant default rate or provide your own conversion file.
