### ISSUE TITLE
Question from 33Across: User Sync in Safari

### ISSUE THREAD

**Issue by curlyblueeagle** [prebid/Prebid.js#3095]
## Type of issue
Question

## Description
Is user sync not supported for Safari? In our tests and live publisher pages we find no logs related to it in the console, nor when looking at network traffic. Also, this line of code suggests that user sync has been deliberately turned off https://github.com/prebid/Prebid.js/blob/0c4b815542c3b7dc166a8d3f961c8284518d294c/src/userSync.js#L268 If so, can we know the rationale for doing so?

**Comment by mkendall07** [comment]
It is turned off for safari yes. Safari has long blocked 3rd party cookies by default and with the latest ITP that is built into Safari any workarounds to store data in a 1st party context is also blocked. You can read more about ITP here if you want: https://webkit.org/blog/8311/intelligent-tracking-prevention-2-0/

So in summary we prevent user syncs because they wouldn't work in Safari anyway.
