### ISSUE TITLE
Post bidding Help

### ISSUE THREAD

**Issue by ialex** [prebid/Prebid.js#315]
I have been reading the Getting started page but there are no instruction on how to setup the line items on DFP to enable this, would you mind to help to understand this and also what does Class 1 Line items means?

http://prebid.org/overview/what-is-post-bid.html

**Comment by mkendall07** [comment]
@ialex 
Class 1 line item just means a standard line item in DFP. You put the whole placement and configuration into DFP.

**Comment by mkendall07** [comment]
@ialex were you able to get post bidding setup?

**Comment by ialex** [comment]
Hello @mkendall07 i still havent figure it out how to setup the line item that will contain the third party tag, if you can elaborate would be great and i will make a video for future implementers 😸

**Comment by prebid** [comment]
- Post-bid is a 3rd party tag creative you setup in your ad server. For each ad unit of your site, create one line item in DFP targeting that ad unit. This line item's creative will contain the below code.
- If your ad unit supports multiple sizes, create multiple Post-bid creatives for each size.
- There is no need for per-price-bucket-per-line-item setup, because the post-bid creative is chosen after the ad server has chosen the line item.
- This post-bid creative supports passback. See more info on passbacks in the below line-by-line explanation.

Reference: http://prebid.org/dev-docs/examples/postbid.html

**Comment by ialex** [comment]
From comments above this line item will be Standard but then the what should we set the cpm value and if we set to a fixed cpm do we lose the ability to track the revenue in DFP?

**Comment by ialex** [comment]
You have to set a standard line item and then pick a cpm based on what you think Headder bidding cpm will be on average the thing is if cpm changes you will have to update the cpm so it can compete fairly with ADX. thanks for the help.
