### ISSUE TITLE
Native ad key-value pairs passed to DFP contain values with characters that are not supported by DFP

### ISSUE THREAD

**Issue by nanek** [prebid/Prebid.js#3155]
## Type of issue
Bug

## Description
Native ad key-value pairs passed to DFP contain values with characters that are not supported by DFP. 
https://support.google.com/admanager/answer/1697712?hl=en under `Rules and limitations around key-values in GPT ad tags` indicates `The values of key-values cannot contain any of the following special characters: " ' , = ! + # * ~ ; ^ ( ) < > [ ] `

This mostly effects hb_native_icon, hb_native_image, hb_native_linkurl as these are URLs.

Here is an example of the query string passed to DFP:
`hb_native_icon=http%3A%2F%2Fpix.us.criteo.net%2Fimg%2Fimg%3Fh%3D200%26m%3D0%26p%3D1%26partner%3D11251%26q%3D100%26r%3D0%26u%3Dhttp%253A%252F%252Fstatic.va.us.criteo.net%252Fdesign%252Fdt%252F11251%252F140512%252F408541.jpg%26v%3D3%26w%3D200%26s%3DO2ovyPbGi0R6QCPl_UVvDu3e`

This decodes to `http://pix.us.criteo.net/img/img?h=200&m=0&p=1&partner=11251&q=100&r=0&u=http%3A%2F%2Fstatic.va.us.criteo.net%2Fdesign%2Fdt%2F11251%2F140512%2F408541.jpg&v=3&w=200&s=O2ovyPbGi0R6QCPl_UVvDu3e` which contains `=` which is not a valid character for a key-value value field.

In a custom Prebid native creative, if I console log out these values, hb_native_icon, hb_native_image, and hb_native_linkurl are rarely rendered if ever. However hb_native_brand, hb_native_body, hb_native_title render fine as text:
````
console.log('hb_native_icon', %%PATTERN:hb_native_icon%%');
console.log('hb_native_image', '%%PATTERN:hb_native_image%%');
console.log('hb_native_linkurl', '%%PATTERN:hb_native_linkurl%%');
console.log('hb_native_brand', '%%PATTERN:hb_native_brand%%');
console.log('hb_native_body', '%%PATTERN:hb_native_body%%');
console.log('hb_native_title', '%%PATTERN:hb_native_title%%');
````

I've tested setting different values to key-value pairs and confirmed the `=` characters are causing the issues with this working with the custom native ad.

I'm using Prebid.js 1.16, however I have also tested Prebid.js 1.25.0 and confirmed the issue remains.

**Comment by wqi1972** [comment]
We got the same problem about 2 months ago when setup native ad. And the problem is more than just ```=```, ```;``` is also an issue if you want to use DCM url as landing page url.
Current workaround we use is: enter encoded values inside APN console (for url, you need keep the domain as it is, and only encode the query string part, otherwise it won't pass APN validation), and inside the dpf native template decode it before using it.
We plan to add some change inside library, which will automatically encode the values having special characters ```" ' , = ! + # * ~ ; ^ ( ) < > [ ]```, so the value can pass through dfp key/value.
Keep one thing in mind, the change we plan to make is NOT a full solution, since we encode these special characters, (either manually or automatically), inside dfp native template, it needs decode these macro values before using them.

**Comment by nanek** [comment]
Thanks, I'm also trying to encode in prebid and decode in the creative. However in the custom native ad creative, I don't see a macro for decode? How do you decode in the creative? Do you have an example?

**Comment by wqi1972** [comment]
oh, there is no macro for it, you have to do it all by javascript, something like:
```
<script>
var linkUrl = '%%PATTERN:hb_native_linkurl%%';
linkUrl = '%%CLICK_URL_UNESC%%' + decodeURIComponent(linkUrl);
document.getElementById('myLink').href = linkUrl;
</script>
```

**Comment by wqi1972** [comment]
Our production team just found some clients want to include ```' and !``` inside hb_native_body field, which is pretty nature. I will work on a change next week, it will check and encode all native related fields, if it contains: ```" ' , = ! + # * ~ ; ^ ( ) < > [ ]```, to make sure the value passes through to dfp.
Inside dfp native template, whether need decode them will be a case by case story. 
But due to this reality, I think simply decode all native macro field inside template before using them might be a good practice.

**Comment by haroldpussat** [comment]
Hi,
FYI, we were facing the same issue with special characters (see #2854 ). That's why I add a special encoded function in targeting.js for function setTargetingForGPT
`slot.setTargeting(key, key.includes('_native_') ? utils.fixedEncodeURIComponent(value) : value);`

The fixedEncodeURIComponent function is like : (if I'm not mistaken in the version code I delievered)
`return encodeURIComponent(str).replace(/[!',()*]/g, function(c) {
    return '%' + c.charCodeAt(0).toString(16);
  });`

And in our native style on DFP, I also add a decodeURIComponent for each native targeting key received like :
`var hb_native_linkURL ='%%CLICK_URL_UNESC%%%%PATTERN:hb_native_linkurl%%';
	var hb_native_brand=decodeURIComponent('%%PATTERN:hb_native_brand%%');
	var hb_native_title=decodeURIComponent('%%PATTERN:hb_native_title%%');
	var hb_native_body=decodeURIComponent('%%PATTERN:hb_native_body%%');
    var hb_native_image=decodeURIComponent('%%PATTERN:hb_native_image%%');`

Then I used a document.write with declared variables and proper HTML in order to display the ad with our native style.
This workaround is live in PRODUCTION since at least 2 weeks on our 5 sites and it seems work well. We have 1 native ad per site for 4 sites, and 2 native ad for our main site. I didn't receive any wrong feedback about native not correctly displayed, even if we still pay attention to a DFP limit about URL size passed to DFP from site with linkURL, image and that cause no ad to be displayed at all (see #2902)

**Comment by wqi1972** [comment]
Thanks, this is exactly I plan to do. Please create a PR for it.
btw, not quite understand code: ```return encodeURIComponent(str).replace(/[!',()*]/g, function(c) { return '%' + c.charCodeAt(0).toString(16); });```, why does it need do string ```replace``` after ```encodeURIComponent```, these chars will get encoded to %[number] format by ```encodeURIComponent```, do I misunderstand something?

**Comment by jkpindahbc** [comment]
Still an issue, preventing the use of Prebid for us.
