### ISSUE TITLE
There are two EMX Digital adapters in  http://prebid.org/download.html

### ISSUE THREAD

**Issue by headerbidding** [prebid/Prebid.js#3267]
There are two EMX Digital adapters in  http://prebid.org/download.html to chose from.
Is this by design? 
If so, what is the difference?

**Comment by SliriK** [comment]
Hi @headerbidding 

If I am not mistaken, the two adapters are meant to be there by design. The first one that was available for a while is the alias in the AppNexus adapter for EMX Digital (formerly known as bRealTime) - that is the one with biddercode='emxdigital'. The other one is a newly submitted EMX Digital adapter that was released with Prebid.js v1.31.0 - the one with biddercode='emx_digital'.

In terms of differences my guess is that there is perhaps some extra demand with the new EMX adapter, as well as possibly some better performance, but I cannot confirm that.

**Comment by EMXDigital** [comment]
Correct, the two adapters are there by design. And our new EMX adapter provides access to the EMX marketplace, providing more demand that is unavailable through our aliased adapter. We will also be sunsetting our aliased adapter in the coming months.

**Comment by EMXDigital** [comment]
Correct, the two adapters are there by design. The plan is to migrate all of our prebid integrations to the new EMX adapter which will provide our publishers with more access to quality demand.

**Comment by patmmccann** [comment]
Can they run simultaneously during transition testing?
