### ISSUE TITLE
Analytics Adapter is unable to get original bid values

### ISSUE THREAD

**Issue by jrosendahl** [prebid/Prebid.js#3281]
## Type of issue

Bug?
## Description

As far as I know, the first chance Analytics adapters have at getting bid response information is at the BID_ADJUSTMENT event.  

However, since the event system is synchronous, it matters what order events are added to the event stack.  

Currently, the actual bid adjustment is/ can be called the analytics adapter is called.  Therefore, the analytics adapter only sees the adjusted bid values.  

It would be nice if the original bid values could be seen as well

**Comment by jsnellbaker** [comment]
@jrosendahl This is overall per design, since in the larger scheme - these adjusted bids are the items that get added to the auction.  There's a subsequent event BID_RESPONSE that actually represents the finalized bid being added to the auction.  So this isn't really a bug.  

This would be more of a feature request to add a new event that would trigger when we originally receive the response.  I know you indicated it would be helpful to have this additional data point, but do you have definite use-case that would rely on this new event's data?

**Comment by jrosendahl** [comment]
The use case is to improve publisher analytics by allowing an Analytics Adapter to collect the actual bid values instead of the only adjusted bid values.  

One use for this data would be to determine what the win rate for a specific bidder would be under different adjustment criteria.  Depending on the how advanced uses of bid adjustments is, it may not be straight forward to recreate the original bid values.  In these cases it would be beneficial to see the original bid data.

It can also aid in debugging bid adjustment configurations.

If you are interested in a PR to support this feature - I am happy to provide one, either by changing the event order, or creating an ORIGINAL_BID event.

**Comment by GLStephen** [comment]
@jrosendahl IMO, an "original_bid" value on the existing bid_response event would be the best approach.

**Comment by mkendall07** [comment]
I agree, I thought we already had this tbh
