### ISSUE TITLE
Losing revenue from Appnexus

### ISSUE THREAD

**Issue by ZackDugow** [prebid/Prebid.js#336]
Hi,

We are experiencing a decrease in overall revenue for our sites when using Appnexus HB.  It takes away more value from our other bidders and the other Daisy Chain tags we run after Header Bidding then the value that it ads. 

Anyone have experience with this?

**Comment by mkendall07** [comment]
Hi @ZackDugow 
Mind posting information about your setup? ie, how you have integrated prebid.js in your site(s) and what bidder configuration looks like?

**Comment by jchandler6** [comment]
Hi @ZackDugow - We have also seen a **massive** drop in revenue for our sites from AppNexus since the 14th of April.

We are seeing this message in our consoles (using the string ?pbjs_debug=true):
'No prebid response from AppNexus for placement code' + placement code.

**Comment by prebid** [comment]
@ZackDugow in principle, header bidding should never "take away" value from other bidders. This is true for all header bidding partners. Do you have a test site?

**Comment by mkendall07** [comment]
closing this as I haven't heard back from OP. If you have any new info to share that would be helpful

**Comment by ericsson66** [comment]
Hi,
I have a very basic implementation > prebid chooses the winner and send to DFP

However, I noticed that when Appnexus returns no bid, it seems that it totally breaks the auction for the placement... No ad is displayed. It could have been a coincidence since other partners can also return no bid at all... but this is systematic. The other bidders are getting ridden off, or prebid.js simply breaks;

Is there any setting that could solve this issue? Because I'm I feel I'm losing a lot of value... Next step would be to remove Appnexus, but it I can get some insight first, it won't hurt ;)

Thanks

[Log] MESSAGE: No prebid response from AppNexus for placement code div-gpt-ad-1472271255756-1 (prebid_20160826214326.js, line 3)

**Comment by mkendall07** [comment]
@ericsson66 
Do you have an example page?
