### ISSUE TITLE
(question) what's the dependance of Prebid.js on GPT?

### ISSUE THREAD

**Issue by piotr-yuxuan** [prebid/Prebid.js#3406]
_(this is a question)_

I'm quite puzzled by Prebid.js reliance on GPT.

> The Google Publisher Tag (GPT) is an ad tagging library for Google Ad Manager that can dynamically build ad requests. GPT takes key details such as ad unit name, ad size, and custom targeting, builds the request, and displays the ad on web pages. 
> — https://developers.google.com/doubleclick-gpt/

In my humble opinion Prebid is able to dynamically build ad requests on its own. In [Getting Started example](http://prebid.org/dev-docs/getting-started.html) ad units are defined in the page, requests are built by each adapters and so on.

What's the reason of Prebid.js dependency on GPT?

Thanks a lot in advance for your replies.

Piotr

**Comment by manigandham** [comment]
Prebid doesn't rely on GPT, it's just using it as the adserver which holds and renders the creatives.

Remember that Prebid / header bidding is about having a unified auction across multiple demand partners *in addition* to your own direct campaigns in your adserver. Prebid runs the auction and then sends the resulting info to your adserver which then picks the winning ad based on rules you setup.

Doubleclick is just the most common adserver used and that's why it's in the examples, but you can use whatever adserver or custom code you want.
