### ISSUE TITLE
bidTimeout event seems to be broken after 1.24

### ISSUE THREAD

**Issue by bjorn-lw** [prebid/Prebid.js#3583]
## Type of issue
With version 1.24 and up until the latest version it seems as if the analytics event "bidTimeout" is broken.

## Description
If one bidder times out, all bidders that do not bid are included in the bidTimeout event, even if they in fact responded in time.

In 1.23 and before that, only the bidder(s) that actually timed out is included in the array passed into the analytics adapter.

## Steps to reproduce
Setup a prebid auction with several bidders. Force one bidder to timeout. I used Fiddler in Windows to set a latency for one of the bidder endpoints to above the auction timeout.

### Expected results
Only the bidder that actually timed out should be included in the list of bidders sent in the bidTimeout event.

### Actual results
Bidders that responded in time gets included in the list.

## Platform details
prebid.js >= 1.24

## Other information
This was the major change that was introduced in 1.24. Not sure if it's related but seems to be a prime suspect:
https://github.com/prebid/Prebid.js/pull/3024

If this is not a bug, but intended behavior, please explain how to collect information about timed out bidders. Can I count on events being fired in sequence? If so I could use the "bidderDone" event that seems to be fired before the "bidTimeout" event for all bidders that didn't actually timeout.

**Comment by thewizarodofoz** [comment]
The way an auction knows which bids timed out is by comparing bid requests to bid responses.
When a bidder yields no bids from its ad server (not due to a timeout, but simply an empty response), from the perspective of the auction it is the same as if there was no response at all. This is due to the fact that a bidder will only notify auction regarding its response using `auction.addBidResponse` **for valid bids only**. If there are no bids in the response, the bidder tells the auction nothing, so the auction thinks it did not respond in time at all.

One way to differentiate between *no bids* to *no response in time* is to add empty bids to the auction and mark them as empty and not usable. Perhaps we can add another [bid status](https://github.com/prebid/Prebid.js/blob/master/src/constants.json#L93).

By the way, the way `auction.js` is finding timed out bids [is a bit outdated](https://github.com/prebid/Prebid.js/blob/master/src/auction.js#L702). It checks `doneCbCallCount` which as far as I see is not used anywhere else in the code. This is not a problem because the filter will always return true, but I guess it should be removed to remove clutter.

**Comment by bjorn-lw** [comment]
Thanks for looking into this! I have some objections to what you describe and please let me know if I didn't get what you said correctly.

1. Putting how the code works aside, I strongly disagree that an empty response is the same as a timeout from an analytics perspective.

2. It's very confusing to even have a timeout event if you can't tell what it means and it fires irrationally.

3. The scenario I describe only happens if one or more bidders timeout. Otherwise the bid timeout event doesn't fire and doesn't drag along other bidders.

4. It did work just as expected with 1.23 and below. If it did work before as one would expect I see no reason shy it shouldn't continue to work unless there is an actual bug here.

**Comment by thewizarodofoz** [comment]
Sorry, I did not mean to suggest that this is accepted behaviour, I simply tried to understand why the code does what it does currently. More importantly, I missed the fact that you are referring to an older version (I researched the current master branch which is obviously much different from 1.23 and 1.24).

I believe I better leave this discussion for someone more authoritative than me, since I don't know what the main authors wish to do about issues in older versions.

**Comment by bjorn-lw** [comment]
Thanks :) I re-read your reply and understood that you were simply trying to describe the current behavior, not defending what it actually does.

Just to be clear though: This is *not* an issue in an older version - that is where it actually works. It is in the current versions we have the problem.

**Comment by mkendall07** [comment]
we won't be making any changes to the 1.x version going forward. All dev should be in current master. Sounds like it's still broken so that's ok.

**Comment by mkendall07** [comment]
@thewizarodofoz 
do you think this is something you can fix in 2.x ?

**Comment by thewizarodofoz** [comment]
@mkendall07 I will work on a pull request. Do you think adding empty bids with a new bid status is a good way to go?

**Comment by mkendall07** [comment]
We've previously not wanted to add "no bids" into the auction. We may need to rethink that a bit. Perhaps just maintaining a list of bidders that have not responded by the time this event happens.

**Comment by bjorn-lw** [comment]
@thewizarodofoz Thank you very much for looking into this! This is preventing us from upgrading so I'm very happy this is being worked on.
