### ISSUE TITLE
Logging not showing the prebid version at start

### ISSUE THREAD

**Issue by belezebu** [prebid/Prebid.js#3700]
## Type of issue
Bug 

## Description
After the Prebid version 2.0 the prebid version is not being logged at the beginning.

## Steps to reproduce
Import the project as suggested in the example available in http://prebid.org/dev-docs/examples/basic-example.html
and notice that e.g.`INFO: Prebid.js v2.8.0 loaded` is not showing.

**Comment by jsnellbaker** [comment]
@snapwich Could you take a look into this issue?  It seems to be indirectly caused by the changes to the hook implementation that was added during the 2.0 changeover.

During the `utils.logInfo` call for the prebid version, it gets to this line [here](https://github.com/prebid/Prebid.js/blob/master/src/utils.js#L359).  This call to `config.setConfig` goes to the hook package (looks like a `setTrap()`?), but never gets processed/executed later.  

This stalled config update causes the subsequent `return config.getConfig(...)` to return a `false`, which prevents the log line from being written to the console.

The first `logInfo` call I see in the console is when we call `pbjs.addAdUnits`, which I believe happens because the hook.ready() has executed so everything is setup and any calls to `config.setConfig` get immediately processed.  

Can you check to see if there may be something going wrong in the `fun-hooks` package?  Or do we have to tweak the logic in prebid or move the `logInfo` call somewhere else?

**Comment by andyblackwell** [comment]
The fix was reverted, so the problem still exists, can this be re-opened?
