### ISSUE TITLE
Issue with responsive ads and sizeConfig

### ISSUE THREAD

**Issue by Jrex90** [prebid/Prebid.js#3740]
I have issues with responsive adunits using sizeConfig. At the moment I cannot make Admanager/DFP stick to the rules defined in sizeConfig.

I have an ad unit which runs across all devices and I would like it to be responsive depending on what device it's being seen on (Desktop: 930x180, Tablet: 728x90, Mobile: 320x160). 

I have a fallback lineitem in Admanager in case prebid returns noBid and it appears it is completely random what size Admanager delivers.

My implementation of prebid with sizeConfig looks like this:

           var adUnits = [{
                    code: '/13349164/HBTest_930x180',
                    mediaTypes: {
                        banner: {
                            sizes: [[728, 90], [930, 180], [320, 160]]
                        }
                    },
                    labelAny:["desktop, tablet, phone"],
                    bids: [{...}]
                }];

-------- 
             sizeConfig: [{
                           'mediaQuery': '(min-width: 1025px)',
                           'sizesSupported': [[930, 180]],
                           'labels': ['desktop']
                       }, {
                           'mediaQuery': '(min-width: 768px) and (max-width: 1024px)',
                           'sizesSupported': [[728, 90]],
                           'labels': ['tablet']
                       }, {
                           'mediaQuery': '(min-width: 320px) and (max-width: 812px)',
                           'sizesSupported': [[320, 160]],
                           'labels': ['phone']
                       }]

A live example: adserving.densoumedia.com/Borsen/basic.html

Am I doing something wrong here? Or does sizeConfig not work this way?

Thanks!

**Comment by jsnellbaker** [comment]
Hi @Jrex90 

Just to confirm something on your setup, did the values in `labelAny` parameter use one long string (ie `["desktop, tablet, phone"]`) or separate string values (ie `["desktop", "tablet", "phone"]`)?

If you did happen to use the former (as shown in the example above), can you try to update it to the latter and see if it works then?  

I don't see anything else wrong off-hand with the setup from what you described.  The test page you linked has the `sizeConfig` settings but not the labels; if you can update it again, I'll be happy to take a look if you're still having issues.

**Comment by Jrex90** [comment]
Hi @jsnellbaker 
Thanks a lot for replying. I have tried both ways with the string values, but the result seems to be the same

**Comment by jsnellbaker** [comment]
Hi @Jrex90, I made a copy of your test page and added the `labelAny` setting to the 930x180 adUnit (I added `labelAny: ['desktop', 'tablet', 'phone'],` between `mediaTypes` and `bids`).

When I loaded the page and enabled the prebid console logs (by appending `?pbjs_debug=true` in the page URL), I saw that prebid was properly adjusting the bid sizes to match the `sizeConfig` settings depending on the screen size.

I attached a screenshot of the console logs in question:
<img width="1418" alt="Screen Shot 2019-04-11 at 10 55 34 AM" src="https://user-images.githubusercontent.com/31102355/55967487-65648d00-5c48-11e9-8b8f-05d8da45c669.png">

There were a few things I observed about the test page (from a Prebid perspective) that you may want to adjust:
- the other adUnit `/13349164/DensouHBTest_300x250` uses a size that's not included in the sizeConfig.  As a result, this adUnit is being filtered out from the auction - since it's seen as not using a size that's valid per the matching sizeConfig rules.  If you want to always include this adUnit regardless of the screen size, you could add `[300, 250]` to each of the `sizeConfig` rules.
- two of the sizeConfigs overlap each other in their mediaQuery settings.  The `tablet` has a min of `768px` whereas the `phone` has a max of `812px`.  For the `sizeConfig` logic to work appropriately, there should only be 1 config active for a given screen-size; so you'll ideally want to adjust one of these min/max settings so that they're setting a proper boundary.


In regards to the behavior you mentioned with your back-up line-items, I believe that's expected behavior if all the creatives exist under the same line-item.  There are different delivery/rotation settings to influence how creatives are chosen (eg CTR) and I don't think they're influenced by the current screen-size.  

I'm not aware of any settings in the adserver that would give you a similar logic to only choose certain creatives in certain scenarios.  I suppose you could try to adjust the sizes you pass into the DFP tag config by some custom logic on the page (so that you'd pass the 'right' ad size based on what you detect screen-size is), but that's something you'd have to investigate/experiment if you'd want to give it a try.

**Comment by Jrex90** [comment]
Thanks @jsnellbaker I also got the same results as you in the console log but as I'm getting noBids and only able to see the DFP creative I didn't think it was working properly :) 

I did have one lineitem for all 3 sizes at the beginning, but I tried to divide them into 3 separate lineitems but with no better result. I suppose with DFP own sizeMapping it would make DFP choose the correct size, but there is no way to have "both" DFP and Prebid sizing active, right? 

Your observations are much appreciated!

**Comment by jsnellbaker** [comment]
Hi @Jrex90 Did you make the changes I suggested to the page?

When I tested each of the size configs, the only time I saw a bid return from the appnexus bidder (for the 930x180 adUnit) was when I used the 2nd config and saw a 728x90 bid return back.

However even though it returned and was passed to DFP, I didn't see it appear on the page.  I attached a copy of the console logs when the targeting keys were generated for this bid (as well as the 300x250 adunit).  Perhaps there's something in the targeting that's not causing your prebid line item to win?  

<img width="1123" alt="Screen Shot 2019-04-11 at 1 29 59 PM" src="https://user-images.githubusercontent.com/31102355/55978979-17a74f00-5c5f-11e9-9250-4e396a172d65.png">

Additionally, a colleague of mine pointed me to a page on how you may be able to configure size mapping with DFP.  It seems to be mostly done on the tag side, rather than in the adserver.  Perhaps you could take a look and see if it may work (though I would suggest to prebid serving consistently first so that you iron that part out).
https://support.google.com/admanager/answer/3423562?hl=en

**Comment by Jrex90** [comment]
Hi @jsnellbaker 

Yeah I did. I do have high CPM prices within DFP (to mirror a live setup) so I suppose it does make sense prebid returns noBid. As for the Appnexus bid I am not sure quite, the DFP lineitem is straight forward with a hb_pb keyvalue and targeted ad unit, so I'm a little puzzled by that actually.
Don't mind the 300x250, I will fix this later on.

I did try to implement the sizeMapping from DFP since I have used it before (but not in combination with Prebid), although I wasn't successful as I kept getting an error. I am unsure as to where I should place the sizeMapping in the Google code. I have updated my live example:
https://adserving.densoumedia.com/Borsen/basic.html

Perhaps you are able to spot where I'm messing up? You can find the sizeMapping by searching for "mapping"

I do believe that this would solve the problem as I know how sizeMapping works with DFP.

Thanks for all your help so far!

**Comment by Martin468** [comment]
Hi @Jrex90  How did you solve mentioned issue?

I guess, I have the same problem with size mapping as you did. I know how to implement size mapping in regular GPT tags but it doesn't work with prebid setup. I tried to use prebid solution: [http://prebid.org/dev-docs/prebid-1.0-API.html](http://prebid.org/dev-docs/prebid-1.0-API.html) , but the size mapping does not work in case prebid returns noBid and the ad units are filled with adsense ads.

Thanks!
