### ISSUE TITLE
Any tips for debugging tests?

### ISSUE THREAD

**Issue by rhythmonebhaines** [prebid/Prebid.js#3799]
...aside from console.log()?

I've got Karma Server starting the headless Chrome browser with the arguments:

`'--remote-debugging-port=9223', '--wait-for-debugger'`

...Chrome starts and waits, but a port's never opened for remote debugging.

Are there other approaches to debugging tests?

**Comment by jsnellbaker** [comment]
Hi @rhythmonebhaines 

Sorry for the delay on this question...

I use the following when I need to debug some tests:
- add the following line of code somewhere in the unit test I plan to check: `debugger; //eslint-disable-line`
- run the following gulp command `gulp serve --watch --browsers=Chrome`

This command should launch a new headless Chrome and open the Karma debug page under `http://localhost:9876/debug.html`.  Once it has loaded, you can open the browser console and reload the page.  During the reload, it should catch at the `debugger` statement in the unit test - which would allow you to manually debug the code.

In addition to the above, you can also temporarily modify the test file so that only certain unit tests run - which would greatly speed up the gulp commands as you wouldn't have to wait to rerun all the other working tests.  To do this - in either the `describe` or `it` function for your unit test, you can append a `.only` (eg `describe.only('test description here', function() {...`) to have Mocha only run those respective tests.  If you put with the `it`, it will only run that test; if you put it with the `describe` it will run all the `it` tests under that `describe`.

I hope the above suggestions help; please let me know if you have any questions.

**Comment by rhythmonebhaines** [comment]
Awesome. Worked the first time. Thanks!
