### ISSUE TITLE
Proposal: Standardizing UserId module OpenRTB format

### ISSUE THREAD

**Issue by adxcgcom** [prebid/Prebid.js#3900]
## Type of issue
Discussion

## Description
After evaluating 3 different manuals for UserId module or similar functionality we see, that we have 3 different definitions of how data should be written in OpenRTB format.

If Prebid can put together and in future merge all ideas, it would benefit all the community and simplify daily AdOps and development in OpenRTB community.

prebid: 
WHO :user.ext.tpid[].source
WHAT:user.ext.tpid[].uid

unifiedId/tradedesk (adsrvr.org):   
WHO :user.ext.eids[].source
WHAT:user.ext.eids[].uids[].id

Advertising-ID-Consortium
WHO :user.ext.eids[].source
WHAT:user.ext.eids[].uids[].id

At the moment we have only 9 modules using pubCommon / unifiedId/tradedesk, but with a planned future updates for this in many Bid Adapters maybe it's right time to have one standard.

Current main difference is that we have different field names (tpid, eids) and field only (uid) or array of values (uids). Also some field properties could be standardized (tdid or adserver.org), tdid or TDID (upper or lowercase,...)

## Steps to reproduce
http://prebid.org/dev-docs/modules/userId.html

```
{
  "user": {
    "ext": {
      "tpid": [{
        "source": "tdid",
        "uid": "19cfaea8-a429-48fc-9537-8a19a8eb4f0c"
      },
      {
        "source": "pubcid",
        "uid": "29cfaea8-a429-48fc-9537-8a19a8eb4f0d"
      }]
    }
  }
}
```

https://www.thetradedesk.com/assets/general/Unified-ID-Adoption-Guidelines-for-SSPs-v1.5.pdf

```
{
    "user": {
        "id": "W13bZtHM5KUAAEQRVFsAAAAL",
        "ext": {
            "eids": [{
                "source": "adserver.org",
                "uids": [{
                    "id": "43f888e1-2941-4b9f-8dc9-1ffb631b7786",
                    "ext": {
                        "rtiPartner": "TDID"
                    }
                }]
            }]
        }
    }
}
```

https://github.com/Advertising-ID-Consortium/IdentityLink-in-RTB
```
{
    "user": {
        "buyeruid": "example_buyer",
        "id": "example_id",
        "ext": {
            "eids": [{
                    "source": "liveramp.com",
                    "uids": [{
                        "id": "XY1000bIVBVah9ium-sZ3ykhPiXQbEcUpn4GjCtxrrw2BRDGM",
                        "ext": {
                            "rtiPartner": "idl"
                        }
                    }]
                },
                {
                    "source": "adserver.org",
                    "uids": [{
                        "id": "6bca7f6b-a98a-46c0-be05-6020f7604598",
                        "ext": {
                            "rtiPartner": "TDID"
                        }
                    }]
                }
            ],
            "gdpr": 0
        }
    }
}
```

https://github.com/digi-trust/dt-cdn/wiki/OpenRTB-extension

### Expected results
One common format defined

**Comment by bretg** [comment]
Would have been nice to have this feedback during the (lengthy) comments period on https://github.com/prebid/Prebid.js/issues/3046, but I guess better late than never. :-)

Overall, I agree with you that we should adopt the user.ext.eids[] approach since that seems to be a standard we were unaware of. (I only referenced the OpenRTB spec while writing the original issue.)

> At the moment we have only 9 modules using pubCommon / unifiedId/tradedesk

Unclear that we need to change anything on the Prebid.js side -- adapters are reading the values out of bidrequest.userid, which is a JSON structure that contains all available IDs.

The only two changes we would need to make for this are:
1) update prebidServerBidAdapter to pass user.ext.eids[] instead of user.ext.tpid[]
2) update Rubicon's Prebid Server-side adapter to read from eids instead of tpid. I believe we're the only ones that have implemented this on the server side and we can support this change pretty quickly.

**Comment by bretg** [comment]
Since we're about to work on DigiTrust, looked it up and found their standard is different. https://github.com/digi-trust/dt-cdn/wiki/OpenRTB-extension

I don't see a standard for how PubCommon ID is supposed to be represented in OpenRTB. @pycnvr - any pointers? (Asking because you seem quite involved in the pubcommon effort) 

So here's a full OpenRTB example for TDID, PubCommon, and DigiTrust -- we'll start making the changes.
```
{
    "user": {
        "ext": {
            "eids": [{
                "source": "adserver.org",
                "uids": [{
                    "id": "111111111111",
                    "ext": {
                        "rtiPartner": "TDID"
                    }
                }]
            },
            {
                "source": "pubcommon",
                "id":"11111111"
            }
            ],
            "digitrust": {
                "id": "11111111111",
                "keyv": 4
            }
        }
    }
}
```

And as we add more (couple more on the way), I'll make them pony up the OpenRTB spec.

**Comment by pycnvr** [comment]
Hi @bretg, agreed.  This doesn't sound like it will affect prebid.js user id module, but prebid-server instead.  My understand is that example in [UserId Module](http://prebid.org/dev-docs/modules/userId.html) is just a suggestion.  Not all bidders use OpenRTB, and the IDs can be repackaged accordingly.  The UserId and its submodules does not dictate or use OpenRTB formats.  

The user.ext.eids approach looks good. It's a good bridge between 2.5 and 3.0.  Pubcommonid should also use an array for uids just to be consistent. That is the direction we are going with.  

```json
{
   "user":{
      "ext":{
         "eids":[
            {
               "source":"adserver.org",
               "uids":[
                  {
                     "id":"111111111111",
                     "ext":{
                        "rtiPartner":"TDID"
                     }
                  }
               ]
            },
            {
               "source":"pubcommon",
               "uids":[
                  {
                     "id":"11111111"
                  }
               ]
            }
         ],
         "digitrust":{
            "id":"11111111111",
            "keyv":4
         }
      }
   }
}
```

**Comment by bretg** [comment]
Thanks @pycnvr. Noted.

Also - we discussed in the Prebid Server committee last week and approved this change.

**Comment by bretg** [comment]
This was done with https://github.com/prebid/Prebid.js/pull/3935
