### ISSUE TITLE
Currency module issue with EUR

### ISSUE THREAD

**Issue by nikkoi** [prebid/Prebid.js#3945]
## Type of issue

Error caused by the currency module.

## Description
We're seeing and error being thrown when updating from Prebid 1.4 to the latest 
(2.2) using the currency module. Earlier everything worked as expected, now we see the following error:

![currency-error](https://user-images.githubusercontent.com/1727721/60165521-20440600-9808-11e9-94d7-cd7d9fd60029.png)

Removing this makes the error disappear:

`"currency": {
"adServerCurrency": "EUR",
"granularityMultiplier": 1,
 "defaultRates": { "USD": { "EUR": 1.13 }}
}`

Also if I change the adservercurrency to USD, then everything works as expected and no errors are thrown.

## Steps to reproduce
Use the latest prebid with currency module, set adservercurrency to EUR

### Expected results

No errors.

### Actual results

Errors.

**Comment by nikkoi** [comment]
Tested backwards, and first version where I don't get this is 2.17.0. I assume this has to do with this: https://github.com/prebid/Prebid.js/pull/3845 , but can't seem to understand why.

**Comment by snapwich** [comment]
Is this within a custom analytics adapter?  I can't see any obvious issue that would cause that error with the public analytics adapters, but since that commit changed from using a closed over variable to a property on `this` that error _could_ be caused by calling `getCpmInNewCurrency` directly or using as a callback somewhere.  If that's the case, the calling code should be updated to bind to the bid.

**Comment by snapwich** [comment]
@nikkoi did this pull-request fix your issue? #3996

**Comment by bretg** [comment]
@nikkoi - as you pointed out, #3845 was the cause of this -- fixed in 2.18. May we close?
