### ISSUE TITLE
Question: is there a way to use prebid with native GPT lazy loading?

### ISSUE THREAD

**Issue by racc-oo-n** [prebid/Prebid.js#3962]
## Type of issue
Question

## Description
I know we can do lazy loading with prebid [example](http://prebid.org/dev-docs/examples/adunit-refresh.html). And it works great.
But there is a new feature in GPT how to do [lazy loading natively](https://developers.google.com/doubleclick-gpt/reference#googletag.PubAdsService_enableLazyLoad). And adOps tell that this method will increase fill-rate and it's better than manual lazy loading.
So is there a way we can use prebid with that `enableLazyLoad` native method?

## Other information
[GPT.enableLazyLoad documentation](https://developers.google.com/doubleclick-gpt/reference#googletag.PubAdsService_enableLazyLoad)
[GPT example of enableLazyLoad](https://support.google.com/admanager/answer/4578089)

**Comment by GLStephen** [comment]
@racc-oo-n As far as I know the answer is no. There is no hook into the lazy load logic to insert the auction. There are ways that get close (like run all auctions early and have them ready for the lazy load), but none are predictable or without major downsides (like creating a race condition and creating a major overbid situation). In our PubWise integration scripts our answer was to create an API and behavior very similar to the GPT lazy load so that we could get similar behavior, particularly variable behavior on mobile.

**Comment by racc-oo-n** [comment]
That’s what I thought 😔 
Thanks a lot for your answer!
