### ISSUE TITLE
Appnexus outstream should not check if renderer is defined server side

### ISSUE THREAD

**Issue by xavierleune** [prebid/Prebid.js#4025]
## Type of issue
Bug

## Description
When creating a placement through the API on appnexus, no renderer is associated to this placement. This is the field ad_types on the placement.
When using this placement on a bid request with an outstream media type, no renderer is defined in the server bid response. Appnexus adapter actually checks only if a renderer has been defined on server side to add the relevant information in the bid response sent to prebid.

So, if no renderer has been defined server side but one is defined on client side, the bid response does not contains the needed "adResponse" field.

This test is located in the adapter here: https://github.com/prebid/Prebid.js/blob/master/modules/appnexusBidAdapter.js#L403-L415

In my opinion, the check should be completed, checking the adunit too.

Thanks for your help.

PS: for those who are stuck with the API, here is a valid ad_types field:

```
[{"id":2,"name":"video","display_name":"Video","renderer":{"id":2,"display_name":"AppNexus Outstream Video Renderer","config":"{\"playOnMouseover\":false,\"audioOnMouseover\":true,\"autoInitialSize\":true,\"nonViewableBehavior\":\"mute\",\"aspectRatio\":\"16:9\",\"playerTechnology\":[\"html5\",\"flash\"],\"playVideoVisibleThreshold\":50,\"expandTime\":1000,\"fixedSizePlayer\":false,\"delayStartUntilNotified\":false,\"showMute\":true,\"showVolume\":false,\"showPlayToggle\":false,\"showProgressBar\":true,\"disableTopBar\":false,\"allowFullscreen\":false,\"disableCollapse\":{\"enabled\":true,\"replay\":true},\"adText\":\"Publicit\u00e9\",\"controlBarPosition\":\"over\",\"vpaidTimeout\":15000,\"terminateUnresponsiveVPAIDCreative\":false,\"delayExpandUntilVPAIDInit\":true,\"delayExpandUntilVPAIDImpression\":false,\"enableInlineVideoForIos\":true,\"preloadInlineAudioForIos\":false,\"waterfallTimeout\":15000,\"waterfallSteps\":-1,\"playerSkin\":{\"topBarColor\":\"#e9edf0\",\"topBarTextColor\":\"#939da3\",\"dividerColor\":\"#cccccc\"},\"skippable\":{\"enabled\":false}}"}}]
```

**Comment by xavierleune** [comment]
This is still an issue.

**Comment by jsnellbaker** [comment]
@xavierleune 

Sorry for the delayed response on this issue.  

When you're using PBS (Prebid Server) to serve outstream video, Prebid expects that the `renderer` object should be defined within the associated adUnit.  

PBS is not capable of handling the renderer object in the same manner as it's done through normal client-side adapters (where the Prebid.js adapter is able to directly read it from their  response object and set it within the bid object directly for use later).  Prebid.js receives the very basic information about the video bid, which is why we rely on the `renderer` object to already be defined in the overall setup to allow this to work.

Because of this configuration, this is why certain checks are not done for PBS responses that would be done inside a bid adapter (such as checking if the `renderer` object exists in the bid); in addition it's why certain objects aren't created inside the bid object (such as the `adResponse` object in the `appnexus` adapter).  The PBS adapter operates in a different framework, so it has different requirements and why it has its own adapter that operates largely independently from the client-side adapters who happen to be available on PBS.

In regards to having the right information to pass to the renderer to allow the returned ad to show (eg having a `bid.adResponse` object for the `appnexus` renderer), you can define these values within the adUnit's `renderer` function.  Most of the crucial data points for the ad should be available (from within the bid's other properties or in the adUnit) to allow the ad to show*.  If you want some idea for this type of setup, there is an example under the Prebid Server bidder section:
http://prebid.org/dev-docs/bidders.html#prebidServer

* If there's some property that's required for the renderer and doesn't seem to be available please let me know and we can take a look.

I realize there's quite a bit of feedback here, so please let me know if you have any questions and I'll be happy to help.

**Comment by xavierleune** [comment]
Hi @jsnellbaker,
Thanks for your feedback. Actually the workflow you describe for appnexus does not reflects how things are implemented, this is the point of the actual issue.
This issue applies to appnexus specifically. The adapter actually checks if a renderer has been defined in the server (here: the appnexus server) response bid and totally ignores the renderer defined in the adunit. It does not check if it's defined.

Definining a renderer on the adunit client side, if no renderer has been defined on the placement level in the appnexus server, will not work The adapter does not receive the "renderer" in the appnexus server bid response, and so does not define the "bid.adResponse" in the returned object. This prevents the outstream bid to be displayed.
So defining an outstream adunit actually requires some extra work (not documented anywhere) in the appnexus server, to have the whole setup working.
I'm not sure if I'm being very clear here, please tell me if not.

**Comment by jsnellbaker** [comment]
@xavierleune Do you have a test page available with this setup so I can review and see where it may be going wrong?

**Comment by xavierleune** [comment]
@jsnellbaker Yes, I just created a copy of [the demo page](http://prebid.org/examples/video/outstream/outstream-no-adserver.html). I changed the placement (line 26) and added the renderer (lines 33-41) and  debug option (line 45) so you can reproduce the issue with [this gist](https://gist.github.com/xavierleune/f72d4e34db0b8a2ea264afbcbd97aebf).

Here is the error: 
![image](https://user-images.githubusercontent.com/2320425/63947178-bef21a80-ca76-11e9-93c0-4a961a3a9bed.png)

The issue comes from this lines: https://github.com/prebid/Prebid.js/blob/099a723aa38e4fe57095fbc27876cb12e2272af6/modules/appnexusBidAdapter.js#L501-L513

The if cannot be evaluated to true, because it only checks if a renderer has been defined in the appnexus console at the placement level. This should not be a requirement.

**Comment by xavierleune** [comment]
@jsnellbaker friendly ping before the stale bot wants to close it ^_^

**Comment by jsnellbaker** [comment]
Hi @xavierleune 

Thanks for the details and the test page. 

I created a PR that should address the issue.  Please let me know if you have any questions.

Thanks,
Jason

**Comment by xavierleune** [comment]
Thanks for the pull request. I think we can close this issue.
