### ISSUE TITLE
Uncaught TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#4035]
started getting this in v 2.20 onwards, not a clue what it is:
Uncaught TypeError: Cannot read property 'map' of undefined
    at Object.getUserSyncs (prebid2.25.0adyjs.js:4)
    at Object.p [as registerSyncs] (prebid2.25.0adyjs.js:3)
    at prebid2.25.0adyjs.js:26
    at Array.forEach (<anonymous>)
    at prebid2.25.0adyjs.js:26
    at prebid2.25.0adyjs.js:26
    at Object.success (prebid2.25.0adyjs.js:26)
    at XMLHttpRequest.onreadystatechange (prebid2.25.0adyjs.js:3)

**Comment by snapwich** [comment]
What bidders are you using?  This is a specific error inside of a bid adapter.

**Comment by spormeon** [comment]
![workspace-sts-3_8_3_RELEASE_-_Java_-_prebid-header-bidding_prebid_timhanlon_tweaktownhjgjhg756676_js_-_Spring_Tool_Suite](https://user-images.githubusercontent.com/8503167/62076228-09496700-b23f-11e9-84b8-2955fcb2138f.png)

![workspace-sts-3_8_3_RELEASE_-_Java_-_prebid-header-bidding_prebid_timhanlon_tweaktownhjgjhg756676_js_-_Spring_Tool_Suite-2](https://user-images.githubusercontent.com/8503167/62076236-0ea6b180-b23f-11e9-868e-d34185157ef5.png)

**Comment by snapwich** [comment]
Given those bidders I would have to guess the issue stems from the recent changes to the `33acrossBidAdapter` in #3944 

Specifically the unsafe access of `adapterState.uniqueSiteIds.map` [here](https://github.com/prebid/Prebid.js/blob/master/modules/33acrossBidAdapter.js#L321).

You can try removing that bidder to see if that fixes your issue.

cc: @curlyblueeagle

**Comment by spormeon** [comment]
ye, it was 33across, any fix for it?

**Comment by snapwich** [comment]
The immediate fix would probably be adding safe lookup to check for an `undefined` property, however the bug highlights a more serious code smell in that shared state is being stored outside `buildRequests` and `getUserSyncs`. This pattern could lead to unexpected behavior depending on run order (in this case I think you may be using prebid-server so `buildRequests` is never called since there are no client requests?) but also could cause edge case bugs around concurrent auctions.

The code should probably be refactored to only operate on function parameters instead of shared closure state. I cc'd @curlyblueeagle as this is a fix they'd probably have to make.

**Comment by spormeon** [comment]
ok, yes using prebid-server.   One other odd thing noticed,  is 33accross makes bids on S2S and is quite often the highest bidder but it never wins a bid or renderers an ad

**Comment by curlyblueeagle** [comment]
@snapwich we could fix the bug in the short-term by adding a safe lookup check. But we are forced to use shared state because we require parameters from all bid requests during user sync. I believe the utils library used to expose a method to obtain this during pre v1 days, but no longer. We tried to do user sync during `interpretResponse` #2024 , but that wasn't the ideal solution since we wanted to delink usersyncing from auction for the sake of performance. So we implemented the shared state in #2899.

Do you have a recommendation on how we can obtain params to bidrequests safely via a function?

**Comment by snapwich** [comment]
I believe most bidders return custom sync urls in their bid responses if they require custom sync data (beyond cookie data). You could do the same.

**Comment by curlyblueeagle** [comment]
copying @thomas-33across since he will be following up on this issue.

**Comment by curlyblueeagle** [comment]
hmm @thomas-33across says he is unable to add comment to this thread. Why?

**Comment by thomas-33across** [comment]
Hello @spormeon can you tell me your prebid.js setup page so I can try to reproduce the issue and make the code change?  Thank you

**Comment by spormeon** [comment]
@thomas-33across   unfortunately not, as its on test pages behind logins, where i test out new prebid releases not live sites
