### ISSUE TITLE
When getting native ads, adserverTargeting is ignored

### ISSUE THREAD

**Issue by sgagnier-l3g3media** [prebid/Prebid.js#4045]
## Type of issue
Bug

## Description
When having a native ad, adserverTargeting is ignored

## Steps to reproduce
Get a native ad, set key { key: 'hb_native_linkurl', val: function (bidResponse) { return ""; } }, and it will still return original

### Expected results
I expected the return of 0

### Actual results
original data

## Platform details
Any

## Other information
Reason why I am doing this is to avoid too long request to GAM. links can be very long, and if you get 3-4 on the same request, it can bust your GAM request causing a trunc=1 param.
I am using postMessage to get the whole bid to the client iframe, I'd like only the minimal required native ad params to be sent to GAM, so setting all hn_native to "" or null to have them removed from the call. When the creative gets displayed, the postMessage will get the whole bid info.

**Comment by jsnellbaker** [comment]
Hi @sgagnier-l3g3media 

Currently this is expected behavior; the `adserverTargeting` part of the `bidderSettings` only covers the base keys that are sent with each bid (like `hb_adid`, `hb_bidder`, `hb_pb`).

There are some alternative features that may help you with the keyword limit issues you're experiencing with native bids.  I provided some links below if you want to look at them further:
- http://prebid.org/dev-docs/publisher-api-reference.html#setConfig-targetingControls
- http://prebid.org/dev-docs/show-native-ads.html#sending-asset-placeholders

Additionally, there are other open issues that are looking into the amount of keys Prebid is using and exploring more alternatives (outside of the options above).  If you want to review the items and join in on the conversations, it would be a help to hear additional feedback.
- https://github.com/prebid/Prebid.js/issues/3366
- https://github.com/prebid/Prebid.js/issues/3899

**Comment by sgagnier-l3g3media** [comment]
Thanks @jsnellbaker this helps a lot. I will have a look.
