### ISSUE TITLE
3.0 list of deprecated APIs/functions internal/external

### ISSUE THREAD

**Issue by mkendall07** [prebid/Prebid.js#4118]
This issue tracks the items to be deprecated as part of 3.0 release of Prebid.js

**following is for external functions/API**

**several items in the userSync API**

- `iframeEnabled`
- `pixelEnabled`
- `enabledBIdders`

`adUnit.sizes`

`pbjs.loadScript() `

**following is for internal functions**

- adloader.loadScript()

5 domain/referrer type functions in utils:

- `getTopWindowLocation()`
- `getTopFrameReferrer()`
- `getAncestorOrigins()`
- `getTopWindowUrl()`
- `getTopWindowReferrer()`

**Comment by pm-harshad-mane** [comment]
Hello @mkendall07 ,
if we are going to deprecate ```iframeEnabled``` does that mean adapters does not need to check this config or we are not going to allow iframe-based syncup?

**Comment by jsnellbaker** [comment]
Hi @pm-harshad-mane,

Iframe based syncs will still be allowed in 3.0.  The public API for the `userSync` feature will no longer have the boolean field `iframeEnabled`, so that would affect publishers.

For adapters, the plan is to have the call signature of the `getUserSyncs` function to remain the same; it will continue to use the `iframeEnabled` and `pixelEnabled` boolean fields within a `syncOptions` object set as the first param.

Prebid will derive which types of syncing are allowed (for that auction) and will then pass that info via the `syncOptions` object parameter so adapters can quickly check what syncs they should register.

I hope this makes sense, please let me know if you have any questions on the above.

Thanks,
Jason

**Comment by pm-harshad-mane** [comment]
Thank you @jsnellbaker for the explanation.
One more question, How Prebid will derive which types of syncing are allowed (for the auction)?

**Comment by jsnellbaker** [comment]
There's some logic [here](https://github.com/prebid/Prebid.js/blob/master/src/adapters/bidderFactory.js#L333) that does the resolution.  

It's currently using both sets of variables that would be involved (the deprecated fields and the future fields), so this may be tweaked a bit as part of the 3.0 release.

**Comment by thewizarodofoz** [comment]
Hello @mkendall07 , I hope this is the right place for this question.
In the Release notes for v3.0 it says that adapters maintainers should "Verify adapter reads sizes from mediaTypes.banner.sizes [because] we are telling pubs that they need to confirm that their adUnits define sizes in mediaTypes.banner.sizes instead of just sizes.".

In the ["Add a New Bidder"](http://prebid.org/dev-docs/bidder-adaptor.html#building-the-request) docs it says that a in the call to `buildRequests `, `validBidRequests` has a `sizes` property and not a `mediaTypes` property. So will this be updated? or should we still use `validBidRequest.sizes`?

**Comment by mkendall07** [comment]
@thewizarodofoz  For now you can continue to use `validBidRequest.sizes` since the core will copy the sizes from the `mediaTypes` object.
