### ISSUE TITLE
Getting More Formal Support

### ISSUE THREAD

**Issue by millieone** [prebid/Prebid.js#428]
We implemented Prebid on one portion of the site and like the results.  We then implemented it on our homepage and expected to see better results. However, we see header bidding doing worse here.

We do not see errors in the debugging but get a lot more responses with 0 bids. Right now it seems getting any formal support or guidance on what is going on with prebid is not feasible. Have there been thoughts of creating a support system? or more debugging tools? 

What issues can be going on to significantly impact performance when there aren't formal errors going on with the debug?

So I am asking if there are plans for a more formal support system or at least a forum where users could pos their issues.

*** 
Separately we would be willing to pay for support to improve performance, contact me if you know of some resources.

**Comment by brk212** [comment]
Hi millieone, 

I think you or someone on your team reached out on this same issue on reddit/r/adops/ this week where I was able to help resolve the problem, which ended up being a technical / implementation issue.  The root cause was that while you were correctly calling your bidders and getting valid responses, you were calling the setTargeting functions before getBidResponses function on your homepage, so that the responses were never passed into your ad call.  By removing the non-prebid GPT call it looks like you were able to resolve your immediate issue.  You could see this in the debug not as a formal error message, but by observing that no bid keyvalues were being set despite getting valid responses from your bidders.  

On support, you can continue to reach out to the community here, or through other industry channels like reddit which prebid folks monitor.  I'd call your attention to the support resources listed here: http://prebid.org/support/support.html  

Hope that helps! 
Ben
