### ISSUE TITLE
[Question] Using custom renderer for InPage ads

### ISSUE THREAD

**Issue by derdeka** [prebid/Prebid.js#4312]
## Type of issue
Question or Feature Request

## Description
Currently it is possible to set a custom renderer per `AdUnit` (see [renderer docs](http://prebid.org/dev-docs/publisher-api-reference.html)) register an renderer in an `BidAdapter` implementation. This is indended to use for `outstream ads` (see [Outsteam documentation](http://prebid.org/dev-docs/show-outstream-video-ads.html)).

We would like to interpret the bid response in an callback function and set an custom renderer to create a kind of creative wrapper. Ideally this should be possible without modifiing several BidAdapters.

## Steps to reproduce
The renderer logic is currently implemented here:
https://github.com/prebid/Prebid.js/blob/3965d3afe7c99b6da40e72bccd8a4a6c2412f6cd/src/prebid.js#L314-L357

AFAIK there is no way to inspect bids and switch the renderer this way!?

**Comment by bretg** [comment]
What's the use case -- some kind of rich media?  How would the renderer be defined -- in the bid response or by the publisher? If by the publisher, what if there were competing renderers for different types of richmedia? We need to understand the big picture of what you're trying to do before recommending an approach.

**Comment by derdeka** [comment]
Yes, the idea is to create rich media ads for special deals, based on dealId or any other criteria provided when receiving the bid. We tried the existing renderer implementation for this by hardcoding the renderer name in a bidder implementation. Ideally we would not need to modify the bidder implementation. The only part which is missing is a dynamic way to switch the renderers at runtime.

**Comment by derdeka** [comment]
I suggest to add a kind of `interpretBid` method to be implemented by the publisher which allows to modify the bid, e.g. just setting the renderer.

**Comment by bretg** [comment]
Sorry, but I'm not sold on this.

Please explain why you need Prebid.js support for richmedia. Why not just send the renderer code in the body of the creative?

I thought about this request in a couple of different ways:

1) do as you suggest -- 'interpret the bid response in a callback function and set a custom renderer to create a kind of creative wrapper'. This doesn't make sense to me because you don't know whether you've won or not. Currently, a renderer is defined at the adunit level and utilized for whichever bid wins. i.e. not just if a certain richmedia type wins. So what you're talking about here is not a renderer in the current sense at all, but rather some kind of special richmedia support.

2) Allow the publisher to define some global `renderer` objects. allow bid responses to identify a renderer by some kind of code. This is awkward because someone would have to track conventions for the codes used by richmedia renderers. Otherwise there would be collisions. Prebid.org has no desire to get involved in mediating or documenting the world of richmedia.

3) allow bid adapters to specify a 'renderer' object in the bidResponse. This side-steps the 'global renderer code' namespace problem, but begs the question: why not just build the 'renderer' into the creative body in the first place?

**Comment by patmmccann** [comment]
I just want to point out that this is somewhat related to https://github.com/prebid/Prebid.js/issues/2668

Adapters often serve outstream as display because of the inflexibility of the prebid framework.

**Comment by derdeka** [comment]
With #4538 I did an example implementation to demonstrate one option to adjust a bid, e.g. setting a renderer. In combination with that, this is the way i currently adjust a bid, based on a `bidAdjustment` function which was set in the `bidderSettings`:

```ts
$$PREBID_GLOBAL$$.bidderSettings = mergeDeep({}, $$PREBID_GLOBAL$$.bidderSettings, {
  [BidderCode.YIELDLAB]: {
    bidAdjustment: (bidResponse: prebid.BidResponse): prebid.BidResponse => {
      const myCrazyConditionWhenTheRendererShouldBeUsed = ...;
      if (myCrazyConditionWhenTheRendererShouldBeUsed) {
        const renderer: prebid.Renderer = new Renderer({url: 'https://my-domain/url-to-my-renderer.js'});
        renderer.setRender(b => $$PREBID_GLOBAL$$.ext.renderer.exampleRenderer(b));
        bidResponse.renderer = renderer;
      }
      return bidResponse;
    }
  },
});
```

This allows a publisher or an ad network to enrich normal display ads with an custom renderer, independent from an adUnit renderer configuration or bidder response with an renderer attribute.

**Comment by piwowarczyk** [comment]
> Sorry, but I'm not sold on this.
> 
> Please explain why you need Prebid.js support for richmedia. Why not just send the 'renderer' javascript in the body of the creative?
> 
> I thought about this request in a couple of different ways:
> 
> 1. do as you suggest -- 'interpret the bid response in a callback function and set a custom renderer to create a kind of creative wrapper'. This doesn't make sense to me because you don't know whether you've won or not. Currently, a renderer is defined at the adunit level and utilized for whichever bid wins. i.e. not just if a certain richmedia type wins. So what you're talking about here is not a renderer in the current sense at all, but rather some kind of special richmedia support.
> 2. Allow the publisher to define some global `renderer` objects. allow bid responses to identify a renderer by some kind of ID. This is awkward because someone would have to track conventions for the codes used by richmedia renderers. Otherwise there would be collisions. Prebid.org has no desire to get involved in mediating or documenting the world of richmedia.
> 3. allow bid adapters to specify a 'renderer' object in the bidResponse. This side-steps the 'global renderer code' namespace problem, but begs the question: why not just build the 'renderer' into the creative body in the first place?

To me the suggestion makes absolutely sense. Moreover I would like to elaborate further on point #1 of your response. The demand side wouldn’t decide how the payload of the creative is rendered but rather the publisher on the supply side who can place various effects (i.e. related to outstream, scrolling, stickiness or overlay) on a simple static, animated or even video creative winning a bid. That would happen in close coordination with a demand partner who agrees that their creatives get displayed in this special way, thus the suggestion of dealids as outlined by @derdeka .

I agree on point #2 as rich media rarely follow standards and if it does such standards get quickly outdated (i.e. the IAB Rising Stars Ad Units from 2013) or lack industry wide adoption.

Regarding #3 the reason why a special way to render a creative in a consistent, technically stable but visually appealing way becomes a necessity is because of the lack of widely adopted standards for rich media creative code. If standards get defined by the IAB or other bodies they mostly refer to the assets required from creative agencies and the display but ignore different ad call infrastructures and in general the inability to provide the same level of ad code quality across the rich media vendor and creative agency ecosystem that would ensure correct rendering of rich media across various publishers.

**Comment by bretg** [comment]
Please treat me as if I don't know anything about your business or the intriciacies of creative display. Which is mostly true. 

My goal is to keep Prebid.js simple and general. Why would a renderer need to be a separate function? Please provide a specific example where you can't just build the rendering code into the ad-markup in the first place.

The only time it makes sense to globally set a rendering function on a per-bidder basis is if the only thing that bidder returns is 1 particular kind of richmedia all the time. OR if the rendering function is smart enough to know about the N kinds of richmedia that bidder could possibly return. That seems twisted and overly complicated.

Assuming that you convince us that a rendering function external to the creative body is required, there are two separate problems:

1) Who should define the rendering function? The richmedia provider ought to supply the code that parses their payload, but it's arguable that the publisher should inspect and approve the code.

2) How should the appropriate rendering function be triggered? Say there are 3 different rendering functions defined. What signal from a bidder triggers the right one? I don't think it's reasonable to assume that one bidder is limited to one type of richmedia. Does `myCrazyConditionWhenTheRendererShouldBeUsed` include being able to sniff the ad-markup? What does this condition look like and why should it be in `bidderSettings`? 

Maybe this could be modeled as an array of rendering functions. At render time, the system calls each one in turn -- the first job of the function is to determine if it knows how to display the winning creative . If it doesn't, then it returns 'false' and the next renderer is given a chance.

e.g. pbjs.registerRenderFunction(function). Before just writing out the ad-markup as if it were HTML, the `renderAd()` function loops through any registered functions. Those functions get passed the entire winning bid response so they can filter by bidder, sniff the ad-markup, etc.

But again -- I'm still not grokking why a separate function is needed in the first place. Seems to me that creatives can already be javascript -- so why not just package up the rendering function with the data needed by that function?

**Comment by bretg** [comment]
Ok, I had a separate conversation where a solid reason for separate rendering code was offered: security. Getting javascript code out of creatives is a noble long term goal because it's not always clear where creatives actually originate.

One can imagine a world where a publisher could choose from a set of 'richmedia rendering functions' built by trusted sources (themselves, the IAB, a trusted vendor, maybe a prebid module?). Creatives then become just JSON data feeds.

However, I'm not sure how practical such a vision is -- will vendors get behind such a thing? Or is ultimately the pub's choice?

In any case, I agree the answer to `Who should define the rendering function?` is "the publisher". But the answer to `How should the appropriate rendering function be triggered?` is still open. Until there's a standard of some kind, an array of rendering functions seems a reasonable approach.

Open to other ideas, but I don't particularly care for the bidderSettings approach because a given bidder may respond with several different types of creatives and multiple bidders could possibly want to use the same rendering code. 

A good solution will:
- avoid duplicate code in all scenarios
- eliminate bidder-specific logic, or keep it to an absolute minimum amount of configuration
- be a hook we can grow with

@mkendall07 - looking for your thoughts here.

**Comment by piwowarczyk** [comment]
> Ok, I had a separate conversation where a solid reason for separate rendering code was offered: security. Getting javascript code out of creatives is a noble long term goal because it's not always clear where creatives actually originate.
> 
> One can imagine a world where a publisher could choose from a set of 'richmedia rendering functions' built by trusted sources (themselves, the IAB, a trusted vendor, maybe a prebid module?). Creatives then become just JSON data feeds.
> 
> However, I'm not sure how practical such a vision is -- will vendors get behind such a thing? Or is ultimately the pub's choice?

Hi @bretg , security is definitively a good reason. IAB SafeFrame is a great piece of technology allowing basic rich media and providing some level of security via sandboxing but this requires vendors and publishers to adapt to a standard that unfortunately also limits the creativity around new rich media formats (basically only allowing expandable ads in 1.0). Whereas the concept where the publisher or ad network brings the renderer logic and the demand side only the creative (be it HTML, JSON or XML) allows full access to the page DOM with its geometry.

I don't think rich media vendors will like this concept as it puts them out of the business but overall this could be a way out of the decline of rich media (caused by the lack of widely adopted rich media standards as mentioned in my previous comment).

**Comment by bretg** [comment]
Here's were I think we are with this:

1) PBJS needs more flexibility in defining what code should render a creative
2) Rendering code could come from the ad response, the bidder's adapter, a richmedia module, or the publisher's page
3) there could be multiple different types of renderers defined on a given page
4) a given bidder could return creatives requiring different rendering functions

The strawman proposal for debate is the one I mentioned above:

```
We should create a pbjs.registerRenderFunction(function). Before just writing out the ad-markup as if it were HTML, the renderAd() function loops through any registered functions. Those functions get passed the entire winning bid response so they can filter by bidder, sniff the ad-markup, etc.
```

Here's how this solution supports each of the various scenarios:

1) the renderer is defined on the pub's page (like in the bidderSettings example). Pseudo-code:

```
pbjs.registerRenderFunction(function(winningBidResponse, doc) {
    // determine whether this function knows how to render the winner
    if winningBidResponse.bidder!="BidderA" || winningBidResponse.ad !contains "identifying pattern"
       return false;
    }
    // write stuff into the provided doc
    return true;
})
```

2) If a bid response (or a bid adapter) comes with a built in rendering function, a bid adapter can add a function pointer to bidResponse.renderingFunction. If a publisher trusts javascript from that source, they can enable it with something like this pseudo-code:

```
pbjs.registerRenderFunction(function(winningBidResponse, doc) {
    // see if there was a renderingFunction on the 
    if !winningBidResponse.renderingFunction exists or !winningBidResponse.bidder in [trusted,bidder,array]
       return false;
    }
    // invoke winningBidResponse.renderingFunction 
    return true;
})
```

3) A richmedia rendering module, if included in the PBJS package, could call this themselves.

```
pbjs.registerRenderFunction(function(winningBidResponse, doc) {
    // determine whether this function knows how to render the winner
    if winningBidResponse.ad !contains "identifying pattern"
       return false;
    }
    // richmedia code wrotes to 'doc'
    return true;
})
```

**Comment by patmmccann** [comment]
How would bid response supplied render function be referred to within scenario one?

**Comment by bretg** [comment]
> How would bid response supplied render function be referred to within scenario one?

Here's where we need an engineer to confirm the details of my proposal, but I think I've got a bid response supplied render function covered in scenario 2.

1) All the examples I suggested are anonymous functions
2) pbjs.renderAd() finds the winningBidResponse and loops through the array of render functions, calling each in turn with winningBidResponse and the destination where the HTML is to be written.
3) The first job of each render function is to determine whether or not it knows how to render the provided winningBidResponse and return false if it doesn't.

**Comment by mkendall07** [comment]
@bretg I like the direction of the proposal, however, I'm concerned about taking a completely hands off approach from the core framework in terms of deciding what renderer to use. For example, what order would you call the renderer functions (assuming multiple) - if multiple types are specified and each can render a given type of bid. Feel like this might be too easy to mess up from an implementation perspective. 

I'll write a different proposal for having a bit more control on the core side while giving the same flexibility to the publisher.

**Comment by GLStephen** [comment]
@mkendall07 @bretg we are seeing definite needs for something along these lines. Primarily enriching various creative with advanced publisher specific functionality like refresh, etc. We'd like to run bidders who support this functionality in their delivered ads alongside bidders which allow us to enrich the functionality clientside. PubWise will contribute dev work on this.
