### ISSUE TITLE
smartRTB not building in 2.36.0

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#4340]
it seems smartRTB wont build for 2.36.0 on the download page, someone else has told me it does but for me it doesn't ( in uk if makes any difference)

**Comment by bretg** [comment]
The problem is that your doc file has the alias listed backwards. 

This file:
https://raw.githubusercontent.com/prebid/prebid.github.io/master/dev-docs/bidders/smartrtb.md

Contains this line: `aliasCode: smrtb`

That causes the download page to refer to `modulecode="smrtbBidAdapter"`

Which doesn't exist.

I'll fix this by removing the aliasCode, but you should confirm what you want to do with the alias. If 'smrtb' is just a shortcut alternate name for your adapter that you want pubs to know about, then just put it directly in the file. Otherwise, if `smrtb` is a different brand and you want a new doc file entirely, then _that_ one would need to refer to `aliasCode: smartrtb`

**Comment by bretg** [comment]
Fixed.
