### ISSUE TITLE
Count winning bids in a bid adapter

### ISSUE THREAD

**Issue by alexkh13** [prebid/Prebid.js#4384]
Hi,

I need your support for a planned PR on improving Cedato adapter.

I'm looking for a legit approach on how to get not only the number of `bidRequestsCount` per adUnit, but also how many of these requests actually won.

I know there is the `onBidWon` handler which seems like the only place to know about wins. The problem is that in order to use this handler to count the wins, I'll have to keep a map as a global variable.

I found this quote from the "How to Add a New Bidder Adapter": 

> Support multiple instances: All adapters must support the creation of multiple concurrent instances. This means, for example, that adapters cannot rely on mutable global variables.

http://prebid.org/dev-docs/bidder-adaptor.html#planning-your-adapter

So, the question is: Are global variables on the adapter scope considered bad practice?

Example:

```
onBidWon: function(bid) {
        this.wins[bid.adUnitCode]++
}
```

**Comment by bretg** [comment]
> Are global variables on the adapter scope considered bad practice

Yes, bad practice because some pubs run multiple wrappers. In addition, many pages don't last past the first auction, so keeping a counter like this seems to have limited value.

@alexkh13 - what are you really trying to do here?

Are you aware that your adapter will only receive `onBidWon` when you win? i.e. you don't get notified when another bidder wins.

It's come to our attention that loss-notification is a possible feature of interest. Is that what you're working on?

**Comment by alexkh13** [comment]
@bretg - we're trying to adjust the CPM by knowing how many times we won the same spot on the website.

A thing that should probably be handled by our server, since it receives the winning notifications. But this process is currently very slow in the backend and we're willing to improve that by giving it as much info as we can. 

Even if this number is going to be inaccurate in some situations, it's still better than nothing.

I didn't look at the implementation behind `bidRequestsCount`, but isn't it possible to maintain the same count only for bid requests that ended up winning eventually?

**Comment by bretg** [comment]
We discussed this and are willing to allow it to happen because it does not strictly break the code of conduct. It will need to be done in a technically acceptable way with the lightest possible browser impact.

Looking in the modules directory, I see other modules storing things on 'this'. Go ahead and open a PR and the engineers can debate the technical correctness.

**Comment by bretg** [comment]
Closing this issue -- feature now tracked in the PR.
