### ISSUE TITLE
Dependence on DFP as ad server?

### ISSUE THREAD

**Issue by tr-coull** [prebid/Prebid.js#449]
We've been using Prebid.js with DFP as the ad server successfully for a while now but our layer of logic on top of the library is quite comprehensive so decided to do some tests just rendering the ads directly when the winner is decided rather than doing a request to DFP for the Line Item & Creative.

It seems to work quite well, as we have our own reporting and helps reduce requests and processing in the user's browser. Most of the documentation here and with the bidders we're working with seem to assume DFP will be used, but is this simply because most companies are already dependent on it for organising their ads and reporting rather than anything else? Would we be shooting ourselves in the foot just to drop it?

**Comment by mjacobsonny** [comment]
@tr-coull 
Even though most of the documentation specifically refers to DFP, you should definitely be able to implement Prebid.js without an adserver by implementing a custom bidsBackHandler function to directly insert the winning creative(s) into the appropriate slots.

**Comment by djlosch** [comment]
@tr-coull you can use it without DFP in the manner that @mjacobsonny described.  The problem that you get is that you lose reconciliation if you're not using an independent, third party, IAB certified ad server (which DFP is).  Every one of your partners is going to have a trafficking discrepancy, and it's not equal across the board.  Long term, your HB stack will want to accommodate for this (Prebid.js has bid scaling) because a $10 bid from a partner with 90% discrepancy is worth less than a $9.50 bid from a partner with 95% discrepancy.

**Comment by craigsteger** [comment]
Outside of the discrepancy mentioned here.  Are there any other adservers that you can use prebid.js successfully?

**Comment by mkendall07** [comment]
@craigsteger 
Prebid.js is adserver independent. As long as the adserver supports keyword/value pair targeting it should work fine.
