### ISSUE TITLE
"error":"Prebid file not built properly"

### ISSUE THREAD

**Issue by combs** [prebid/Prebid.js#4679]
## Type of issue

Bug

## Description
The Prebid download form here:
http://prebid.org/download.html

Fails if you choose the "Yieldbot" adapter:
`{"error":"Prebid file not built properly","requestId":"49ac40fe-1764-41ba-8b98-f5d31b84b1bf"}`

## Steps to reproduce
http://prebid.org/download.html
choose Yieldbot

## Test page
http://prebid.org/download.html

### Expected results
Prebid download

### Actual results
93-byte json error

## Platform details
n/a

## Other information
n/a

**Comment by JulienVerkest** [comment]
I've the same error message.

**Comment by jsnellbaker** [comment]
Hi @combs & @JulienVerkest 

Sorry for the small delay.  To confirm on something, were you trying to include this adapter on a 3.x build?

If so, that adapter is not part of the 3.x versions of Prebid.js (at least so far).  It was removed from the project as part of the 3.0 release as they were not compliant with some changes that were introduced to the major release.

If you were trying to make a 2.x build, then that build request should work.  Can you provide a list of the modules and the build version you were attempting in this case?

**Comment by combs** [comment]
Yes, 3.x. That reason makes sense. I feel that ideally the wizard would not let me choose in impossible configuration, or provide more information about why the build failed. Thank you @jsnellbaker

**Comment by JulienVerkest** [comment]
@jsnellbaker 

I run the following snippet (devtools > Sources > Snippets) to the download page and it works fine for me when I choose the 2.44.1 version but it fails with 3.x version.

```
(function() {
  if (document.location == 'http://prebid.org/download.html') {
    document.querySelectorAll('[modulecode="consentManagement"]')[0].checked = true;
    document.querySelectorAll('[modulecode="dfpAdServerVideo"]')[0].checked = true;
    document.querySelectorAll('[modulecode="slimcutBidAdapter"]')[0].checked = true;
    document.querySelectorAll('[modulecode="rubiconBidAdapter"]')[0].checked = true;
    document.querySelectorAll('[modulecode="ixBidAdapter"]')[0].checked = true;
    document.querySelectorAll('[modulecode="teadsBidAdapter"]')[0].checked = true;
    document.querySelectorAll('[modulecode="appnexusBidAdapter"]')[1].checked = true;
    document.querySelectorAll('[modulecode="criteoBidAdapter"]')[0].checked = true;
    document.querySelectorAll('[modulecode="smartadserverBidAdapter"]')[0].checked = true;
  }
})();
```
Is there an adapter among these is wrong ? 

Thanks

**Comment by saileshd** [comment]
I tried downloading the following modules and I'm getting the same error. Is there anyone of them that is not supported yet?

modules[]: appnexusBidAdapter
modules[]: ixBidAdapter
modules[]: lkqdBidAdapter
modules[]: oneVideoBidAdapter
modules[]: openxBidAdapter
modules[]: pubmaticBidAdapter
modules[]: pulsepointBidAdapter
modules[]: rubiconBidAdapter
modules[]: spotxBidAdapter
modules[]: telariaBidAdapter
modules[]: tremorBidAdapter
modules[]: schain
modules[]: userId
version: 3.2.0

**Comment by jsnellbaker** [comment]
@JulienVerkest 
If your code is using the default 'latest' version of Prebid.js, then it's likely the `smartadserverBidAdapter` that's causing you the trouble.  That's adapter is still not currently part of the 3.x versions.

@saileshd 
I think the issue for you is tied to `tremorBidAdapter`.  I had to do a bit of digging on this one.

In the 0.x versions of Prebid.js, there used to be a dedicated module file for `tremor`, however with this PR https://github.com/prebid/Prebid.js/pull/2924 it seems they changed their name to `telariaBidAdapter`.  They have `tremor` listed as an alias, so you can still use it as a bidder and it would refer to the `telariaBidAdapter`.  

If that's what you are doing, then you can simply drop the `tremorBidAdapter` from your list since it's really referring to a module you already have (and it doesn't exist as a set of files in the newer versions of the project).

Please let me know if that makes sense.  If you were seeing that list work with older versions of Prebid.js (ie 2.x), please let me know which versions specifically so I can check further.

**Comment by saileshd** [comment]
@jsnellbaker after removing the tremorBidAdaptor I was able to download the prebid3.2.js file with no issues. Thank you

**Comment by jsnellbaker** [comment]
I'm going to close out this issue at this time.  

If there are any further questions directly related, please feel free to comment and reopen the issue.
