### ISSUE TITLE
Safeframe interface

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#4796]
## Type of issue
Feature Request

## Description
Safeframe interface

The IAB safeframe committee has suggested we include guidance to bidders if their ad will end up in a safeframe. For us, this is dependent on the bidder, not just the slot. For each slot, we would need some sort of setConfig that listed the bidders that should expect to be rendered in a safeframe. Adapters could then gather this information from the interface and pass along to their endpoints if so desired. The prebid server call should also pass this information. It should be dependent on format. 

For example:  {
  "outstream": [
    "bidderA",
    "bidderB"
  ],
  "native": "none",
  "banner": "all"
}

would tell all display bidders they are going to be rendered in a safeframe, that all the native demand would not be and that of the outstream bidders, only bidderA and bidderB would be in a safeframe. This config should be able to vary by slot for a single page.

**Comment by Jlaw007** [comment]
We started prebid with the universal creative before 1.23 listed http://prebid.org/adops/step-by-step.html and all our creatives come from before this version. We would likely need to update to the new universal creative then to support such a feature, but we can plan on making this update in order to support.

**Comment by patmmccann** [comment]
So we're thinking we need to add safeframe version to the spec as well as a default of 'undisclosed'.

**Comment by bretg** [comment]
I don't really see this as a breaking change. It's another in the growing list of standard conventions that bidders ought to be aware of and should take advantage of.

A few things need to be fleshed out about the proposal.

1) The setConfig:
```
pbjs.setConfig({
  "safeframe": {
    "video": [
      "bidderA",
      "bidderB"
    ],
    "native": "none",
    "banner": "all"
}
});
```

2) The values for video/banner/native can be:
- "none": no bidder's creatives will be placed in a safeframe
- "all": all bidders creatives will be placed in a safeframe
- array: the named bidders' creatives will be placed in a safeframe

3) Because we don't like bidders to get details about any other bidder, PBJS core needs to process this setConfig and add it to each adunit:
```
  mediaTypes: {
    banner: {
      sizes: [ ... ],
      safeframe: true
    },
    video: {
      ...
      safeframe: false
    },
    native: {
      ...
      safeframe: false
    }
  }
```
4) Bidder adapters would need to be updated to read the new adunit flags

@patmmccann - what would you expect bidders to actually do -- just not return any creative that tries to break out of a frame?

**Comment by patmmccann** [comment]
That's really helpful; and yes the thought is that bidders would pass it
along to buyers so that noncompliant or nonfunctioning demand doesn't end
up just filtered out. One thing of note is there should be a version on the
safeframe when true. Gam currently returns a version 1.1 safeframe, but
version 2.0 is coming soon and might not be compatible. I think the ideal
scenario would be the publisher would say what versions they are willing to
accept, that gets added to the openrtb standard and passed on all bid
requests, and the creatives get marked with which versions they are
compatible with in the bid response.

**Comment by katiestroudpro** [comment]
Bret, thanks for fleshing this out. To Patrick's comment on version, that is something we'll need. SafeFrame 2.0 won't be compatible with v1.1. 

This feature will go a long way to supporting SafeFrame and encouraging wider adoption. I'll work with IAB Tech Lab on adding support in OpenRTB and anywhere else we need it.

**Comment by AskRupert-DM** [comment]
I have a question - apologies if its covered/basic - but will prebid core handle writing out adapters respective renderers to the safe-frame document as opposed to the parent document or will adapters/renderers require updating to handle this ?

**Comment by lucas-sm** [comment]
I second @AskRupert-DM 's question. I would love to hear how outstream video would be working with safe-frames and if there are any roadmap plans around it.

**Comment by bretg** [comment]
If there aren't any volunteers to finish fleshing this out, @gglas will have to find one. I'm not a candidate - don't grok either safeframes or outstream renderers.

**Comment by katiestroudpro** [comment]
Apologies for dropping off the thread here. We're looking at using Intersection Observer to support page-scroll. For outstream video, I can bring it up in today's (7/1/2020)meeting. I'll let you know what is discussed. Also, I'll see what I can do about finding someone to flesh this out.

**Comment by gglas** [comment]
Thanks so much Katie!  Let's definitely discuss - but I believe the next
PMC meeting is on 7/8 not 7/1 -- look forward to chatting with you then.

**Comment by patmmccann** [comment]
@AskRupert-DM rendering scripts being attached inside frames is part of the new prebid code of conduct but is not yet implemented.

**Comment by AskRupert-DM** [comment]
Thanks @patmmccann - are there any proposed timeframe for when that implementation may be done ? 

Also is there a place that I can read up on for the 'code of conduct'  you mention anywhere ?

**Comment by patmmccann** [comment]
https://github.com/prebid/Prebid.js/issues/5239
