### ISSUE TITLE
Consent management using custom Cmp

### ISSUE THREAD

**Issue by gchicoye** [prebid/Prebid.js#4865]
## Type of issue
GDPR Consent Management

## Description
We try to pass the consent delivered through a homemade cmp. However, although we're following your documentation, we struggle to get consent sent to SSPs

## Steps to reproduce
I've made a copy and paste of the code below
[consentManagement.html](http://prebid.org/dev-docs/modules/consentManagement.html)

## Test page
https://test.cleoma.fr/cambium/rustica-consent.html 
There is no auction here as it is blocked by `allowAuctionWithoutConsent: false`
If I turn to true, the consent string is still not attached.

### Expected results
Auctions with consent string sent to SSPs

### Actual results
No Auctions

## Platform details
Prebid 3.6

**Comment by jsnellbaker** [comment]
Hi @gchicoye 

I think the issue here is how the `getVendorConsents` object in the `pbjs.setConfig` is populated.  

Below is a copy of the gdpr data used in the setConfig call (at least this appears to be used when the auction starts when I loaded the test page):
```
{
  "gdpr": {
    "cmpApi": "static",
    "allowAuctionWithoutConsent": false,
    "consentData": {
      "getConsentData": {
        "gdprApplies": true,
        "hasGlobalScope": false,
        "consentData": "BOOgjO9OOgjO9APABAENAi-AAAAWd7_______9____7_9uz_Gv_r_ff_3nW0739P1A_r_Oz_rm_-zzV44_lpQQRCEA"
      },
      "getVendorConsents": {
        "metadata": "BOOgjO9OOgjO9APABAENAi-AAAAWd7_______9____7_9uz_Gv_r_ff_3nW0739P1A_r_Oz_rm_-zzV44_lpQQRCEA"
      }
    }
  }
}
```

The return object of the `getVendorConsents` only contains 1 property.  The normal object returned by a CMP usually contains many properties that describe the choices made by the user.

Part of the logic we have in the `consentManagement` module is a bit basic but it expects this object to have at least more than 1 property.  

I would recommend if you're going to use this static approach long term to try and accurately populate the getVendorConsents object here with the normal values (for any bidders that happen to read and use the data in this object).  If you know that the bidders you work with don't rely on this field, then you could try to add another field (like `gdprApplies`) and I think it should allow the auction to proceed.

Please let me know if you have any questions.

**Comment by gchicoye** [comment]
Hi @jsnellbaker ,

Thanks to you explanations, I finally found the fix. I just needed to add gdprApplies as property of the getVendorConsents object.
I suggest you update the documentation with this fix.

getVendorConsents = {
				metadata: consentString,
				gdprApplies: true,
			}

Thanks again for your prompt reply!

Gabriel
