### ISSUE TITLE
FAN error response: Publisher ID is not set on the web request

### ISSUE THREAD

**Issue by theighost** [prebid/Prebid.js#4871]
Hello,

I'm trying to send bid requests from client-side Prebid 3.7.1, the bidder is configured as per the documentation:

```
{
    bidder: "audienceNetwork",
    params: {
        placementId: "763716885013290_76311706400997"
    }
}
```

I get the following response from facebook:

```
{
   "request_id": "759765351150255992",
   "errors": [
      "Publisher ID is not set on the web request"
   ],
   "bids": {
      
   }
}
```

What Publisher ID is missing and where should it be added?

Thank you and best regards

**Comment by bretg** [comment]
Sorry, we cannot support parameter questions for individual adapters. You will need to work with your audiencenetwork account rep to determine the issue here. Note that the audiencenetwork adapter is going to be removed in April of this year due to FaceBook's announcement that they're only going to support app inventory.

**Comment by theighost** [comment]
Thank you bretg
