### ISSUE TITLE
Instream bids not cached?

### ISSUE THREAD

**Issue by godoggie** [prebid/Prebid.js#4979]
## Description
Trying to get a handle on INSTREAM video caching with the GAM. Seems to work fine for some bidders but not others.  My tests are based on the videojs &  [Show Video Ads with Google Ad Manager sample](http://prebid.org/dev-docs/show-video-with-a-dfp-video-tag.html#notes-on-prebid-cache) 

Line items are configured per [Setting up Prebid Video in GAM](http://prebid.org/adops/setting-up-prebid-video-in-dfp.html) and using the `https://prebid.adnxs.com/pbc/v1/cache?uuid=%%PATTERN:hb_uuid%%` creative

All winning bids are passing back a valid videoCachKey and vastUrl (some vastXML too) but some are failing to render ads due to a 404 from the videojs-vast-vpaid plugin (`VastClient.requestVastXML` error).
Upon examining the network call it appears as though there is nothing in the cache.
IE. GET call to `https://prebid.adnxs.com/pbc/v1/cache?uuid=QVVDVElPTl9JRD.....`
results in:  `No content stored for uuid=QVVDVElPTl9JRD....`

video cache is being set
```
pbjs.setConfig({
        cache: {
            url: 'https://prebid.adnxs.com/pbc/v1/cache'
        }
    });
```
and `pbjs.adServers.dfp.buildVideoUrl` being called correctly.

So who/what is supposed to cache the vastUrl/vastXML?   per the [notes on prebid](http://prebid.org/dev-docs/show-video-with-a-dfp-video-tag.html#notes-on-prebid-cache)...
`If pbjs.setConfig({cache: {URL}}) is defined and the bidder responds with bid.videoCacheKey, Prebid.js will not re-cache the VAST XML.`

What is meant by "_**will not re-cache the VAST XML**_"?  Seems that bids are cached for some bidders but not others. Is this the issue?

Does this mean we would need unique LineItems per bidder with a creative that references the vastXML (not preferable)

Any insight would be appreciated. Thanks!

## Platform details
Prebid 3.5+

**Comment by bretg** [comment]
Correct @godoggie - some bidders cache the VAST on their own servers rather than AppNexus'. The two known bidders that do this are Rubicon and SpotX. It makes sense from the perspective that these companies want to be responsible for their own caches and don't want to burden APN from having to be the cache for the entire internet.

The recommended approach is to create new line items, but we've recently tested creative-level targeting and that seems to work ok, but to be safe, you want to have your "default" creatives target away from the 'special' bidders. e.g.

- VAST creative 1: target away from hb_bidder=specialbidder1 or hb_bidder=specialbidder2
- VAST creative 2: target towards hb_bidder=specialbidder1
- VAST creative 3: target towards hb_bidder=specialbidder2

To find the VAST cache URLs in use by Rubicon, SpotX, or others, you'll need to work with their account team or solutions engineer. They don't want to publicize those URLs because they don't want folks randomly utilizing their caches. We should take a moment to recognize the cost that APN bears by hosting this public commons.

This all said, I agree that the documentation isn't great in this area. Will put it on my list to flesh it out some in the coming weeks.

**Comment by godoggie** [comment]
Thanks for the response but I am still unclear about what process does the caching in cases that are not SpotX or Rubicon.   
Also are these two (Spotx/Rubicon) what you are referring to as "special" bidders? (those that cache there own vast).

The reason for asking this is that the cache url passed back by the` pbjs.adServers.dfp.buildVideoUrl `call results in the noted 
`No content stored for uuid=..bidder...videoCacheKey....` message when trying to access the `videoUrl `returned from 
```
var videoUrl = pbjs.adServers.dfp.buildVideoUrl({
	adUnit: videoAdUnit,
	params: {
		iu: '/xxxxx/prebid_cache_video_adunit',
		output: 'vast'
	}
});
```

btw, I'm assuming what you meant by "target towards hb_bidder=specialbidder1" refers to this creative ref?
```
   https://prebid.adnxs.com/pbc/v1/cache?uuid=%%PATTERN:hb_uuid_BIDDERCODE%%
or
   [other bidder cache location]
```

thanks again!

**Comment by bretg** [comment]
> about what process does the caching in cases that are not SpotX or Rubicon

For bidders that return VAST XML, you need to configure pbjs.setConfig({cache: URL}) as described in http://prebid.org/dev-docs/show-video-with-a-dfp-video-tag.html and http://prebid.org/dev-docs/publisher-api-reference.html#setConfig-vast-cache

> Also are these two (Spotx/Rubicon) what you are referring to as "special" bidders? (those that cache there own vast).

right

> I'm assuming what you meant by "target towards hb_bidder=specialbidder1" refers to this creative ref?

- creative1 targets hb_bidder not spotx or rubicon and defines whatever VAST URL you place in setConfig. (probably AppNexus')
- creative 2 targets hb_bidder=spotx and defines spotx's VAST URL
- creative 3 targets hb_bidder=rubicon and defines rubicon's VAST URL

**Comment by bretg** [comment]
@godoggie - I updated http://prebid.org/prebid-video/video-getting-started.html to mention the vast-cache. Is there another document you feel should be more clear on the topic of vast caches?

**Comment by cham-kim** [comment]
Hello, once you set up a rubicon cache endpoint in GAM for instream preroll units, do protocol configurations or placement id setups need to request a specific type of vast file? I'm still seeing errors where the vast url errors out: 
[1].vastUrl: "https://pg-prebid-server-aws-usw2.rubiconproject.com:443/cache?uuid=91ebb03c-11f8-4504-b8e8-937ceffd8ad5"

**Comment by bretg** [comment]
@cham-kim - we may need more detail to be able to debug this... e.g. a test page and a description of what to look for.

Please note that items are cached server-side for only a short period -- default is 15 minutes for video. After that time period, the cache entry is deleted.

So the obvious things to check are:
1) make sure the read is less than 15 mins after the write, or contact your Magnite account rep to discuss raising how much time your account can cache items.
2) make sure that the host name and uuid are not hard-coded in the GAM creative. Given the example URL you give, I'm concerned this may be the case. GAM does not accept variables in the host name, so your GAM creatives would need to refer to https://prebid-server.rubiconproject.com/cache?uuid=%%SEEBELOW%% -- it would be incorrect to hardcode pg-prebid-server-aws-usw2 into your GAM creatives because we have 6 regions. 
3) make sure you're using the correct UUID macro. If you're using send-all-bids mode, then the macro would be %%PATTERN:hb_uuid_rubicon%%. If you're using send-top-bid, then %%PATTERN:hb_uuid%%
