### ISSUE TITLE
Make net / gross configurable in PubMatic

### ISSUE THREAD

**Issue by ptomasroos** [prebid/Prebid.js#5023]
## Type of issue
Feature request

## Description
In the PR #2011 NET_REVENUE was first true, then removed to become fixed as false see following commit https://github.com/prebid/Prebid.js/pull/2011/commits/d81bf1cf3f2b2726a6d4230a00f0a41f2cd70810 by @pm-manasi-moghe 

It would be great if this could be configured by the publishers as many other adapter are allowing, aka choose if net or rev should be returned. 

### Expected results

Expecting my bids to be returned in net

### Actual results

Bids are being returned in gross

## Platform details
Prebid.js

## Other information
#2011

**Comment by mike-chowla** [comment]
@ptomasroos PubMatic can return your bids as either gross or net.  This is controlled by a backend setting.  You can reach out to your account manager to find out what your account is currently set to and get it changed if necessary.

Unfortunately, the net revenue flag we return isn't accurate today since we currently don't know at the adapter how individual accounts are set when it comes to net vs gross revenue.  The majority of accounts are set for net bidding and our default setup for new accounts is net.  But we have older accounts were bidding is still set to bid gross.

**Comment by ptomasroos** [comment]
Thanks for the feedback @mike-chowla 
Will close then!
