### ISSUE TITLE
prebid floor price moduleの導入

### ISSUE THREAD

**Issue by kobayashi-kyohei** [prebid/Prebid.js#5095]
http://prebid.org/dev-docs/modules/floors.html
https://github.com/prebid/Prebid.js/blob/master/modules/priceFloors.js
https://github.com/prebid/Prebid.js/blob/master/modules/priceFloors.md
アドユニット別、サイズ別で実施してみたい

https://headbidder.net/faq/prebid-floor-price-the-solution-is-available-for-all-headbidder-users
bidderごと設定することも可能、、、？

**Comment by jsnellbaker** [comment]
@robertrmartinez  I believe this is a translation of the question, can you take a look?
```
I want to implement by ad unit and size.

It is also possible to set bidder?
```

@kobayashi-kyohei If the above is not accurate, can you please repost your question in English please?

**Comment by robertrmartinez** [comment]
Hello @kobayashi-kyohei,

Thanks for the question.

I'll answer in two parts:

> I want to implement by ad unit and size.

This is currently possible without any extra work needed.

You simply would build a floors object similar to this (substituting and values and adding or removing any rules you want:

```json
{
            pbjs.setConfig({
                floors: {
                    enabled: true,
                    data: {
                        schema: {
                            fields: ['adUnitCode', 'size']
                        },
                        values: {
                            'adUnitCode-1|300x250': 0.8,
                            'adUnitCode-1|300x600': 1.2,
                            'adUnitCode-1|728x90': 1.8,
                            'adUnitCode-1|*': 0.51,
                            'adUnitCode-2|300x250': 1.8,
                            'adUnitCode-2|300x600': 2.2,
                            'adUnitCode-2|728x90': 2.8,
                            'adUnitCode-2|*': 1.51,
                        }
                    }
                },
            });
}
```

Of course there are many ways you can have your `values` object represented. The combination can be whatever your ad unit name is and any size to match.

You can utilize the `*` field which matches anything.


> It is also possible to set bidder?

This is more tricky. While it is possible by using the `additionalSchemaFields` hook, we do not recommend having different floors for different bidders.

The way the Price Floors module works is that it takes into account your `bidCpmAdjustments` when flooring.

So if you pick a universal floor of 1.2

Then it will compare each bidders CPM with that floor AFTER the bidCpmAdjustments are made.

So if you have a bidder who bids in GROSS and you want it to be marked down to NET,

The price floors module will run your adjustment BEFORE comparing with the floor..

This allows you to have a single unified floor across all bidders that takes into consideration whatever your cpmAdjustments may be.

So if you have a two bidders
Bidder A: 1.2 CPM (NET)

Bidder B 1.2 CPM (GROSS)

And you have a cpmAdjustment for Bidder B to take into account their fee:

`Bidder B CPM * 0.8`

And the floor module chose a floor of 1.0

Bidder A would compare with 1.2 to 1.0 floor

Bidder B would compare with 1.2 * 0.8 to the 1.0 floor
And after adjustment this would be 0.96 to 1.0 and it would not meet the floor.

Thus, your 1.0 floor is actually honored and Bidder B must bid more in order to meet the floor because they are NET!

I hope I have clarified some of this to you.

Please let me know if you have anymore questions.

- Robert

**Comment by robertrmartinez** [comment]
Closing this since no response.

please reopen or create a new issue for further questions.
