### ISSUE TITLE
Using prebid.js in integration tests in a CI environment

### ISSUE THREAD

**Issue by zshnr** [prebid/Prebid.js#5305]
## Type of issue
Question

## Description
We have an SDK that. allows integration with prebid. In the integration tests for our SDK, we essentially load it on a page along with any other external scripts we need, access the page via puppeteer and make different assertions. 

We're using the example from the [Getting started](http://prebid.org/dev-docs/getting-started.html) guide as is without modifications.

Essentially we test that when the bids are won, we can track it. So if you imagine if a bidWon event is emitted we increase a count by 1. 

This works fine locally on our dev machines. However, in our CI environment (currently running on travis-ci), we notice that even though the bidderDone event is emitted, no bidWon event ever occurs.

To debug this, I load the page with `?pbjs_debug=true` and print the contents of the puppeteer page's console instance to the terminal to see if there is any message with "bidWon" in its text.

I was wondering whether prebid/appnexus/travis-ci block one another? Can anyone confirm this to be the case? I've searched a lot online and couldn't find anything that sheds light on this.

Also, just FYI, we add an alias for localhost in `/etc/hosts` so that we can access the page like `http://ouralias:portnumber` (as opposed to `http://localhost:portnumber`)

Thanks!

## Platform details
Prebid.js version: 3.20.0
Browser / OS: Linux (Ubuntu 16.04.6 LTS) -- HeadlessChrome/77.0.3835.0
Node: 12.17.0
CI: Travis-CI

**Comment by jsnellbaker** [comment]
Hi @zshnr 

Can you confirm from looking at the console logs if the auction is completing with an actual bid (ie do you see the log lines that describe the targeting keys getting set)?  They should look something like the following:
<img width="983" alt="Screen Shot 2020-06-01 at 10 43 36 AM" src="https://user-images.githubusercontent.com/31102355/83420530-c626ca00-a3f4-11ea-92e8-39be7bb9e46a.png">

The `bidWon` event triggers during the rendering part of the process, so it's possible that the auction isn't finishing with a bid b/c the bidder didn't return a bid (which sometimes happens for the appnexus bidder in automated environments due to some checks that are performed on the ad server to see if it's a 'valid' page).
