### ISSUE TITLE
Insticator adapter causing build error

### ISSUE THREAD

**Issue by spenser-roark** [prebid/Prebid.js#5380]
## Type of issue
* Bug

## Description
Attempting to download prebid.js with insticator causes an error message, the other bidders I've attempted seem to work fine

## Steps to reproduce
* Select Insticator as a bidder adapter
* Attempt to download

## Test page
* N/A

### Expected results
* Download prebid.js

### Actual results
* Error message: {"error":"Prebid file not built properly","requestId":"8f46c215-ca50-4f1a-a0bd-9acf964b2c85"}

**Comment by bretg** [comment]
This is an interesting one. 'insticator' was one of the aliases of serverbid, which was not ported to Prebid 3.x as noted in https://github.com/prebid/Prebid.js/issues/4650

I don't know specifically what aspect of 3.0 they didn't conform to -- the list is at https://github.com/prebid/Prebid.js/pull/4580 - probably related to deprecation of functions in utils.js

Adapters not ported were still left on the Download page while versions of 2.x were still being supported, but we only support the most recent 20 versions of Prebid.js on the Download page, so serverbid and all of it's aliases are now unavailable since no 2.x option can be built there. Note that anyone who wants to build them can still use the command line.

I've gone ahead and removed the following adapters from prebid.org: answermedia, automatad, buysellads, insticator, serverbid. They can be restored if the serverbid adapter is ported or the aliases find another host adapter.

As FYI - adding github accounts that touched the serverbid adapter in 2.x: @Saigredan , @micha , @prebid-pubnx , @jcswart, @jgrimes
