### ISSUE TITLE
TCFv2 - Fallback to getTCData

### ISSUE THREAD

**Issue by kirly-af** [prebid/Prebid.js#5554]
Hi,
Inside #4801 I could read from @harpere comment: 
>before (or in addition to) adding the eventListener, shouldn't we call the API with getTCData to see if the eventStatus is already tcloaded or useractioncomplete, meaning that the consent data is already in a state that's ready to be used? The concern is that the TC String may not change and therefore never fire an event. don't need to do this because:

I disagree it is not necessary because the module may not be ready when the event (tcloaded for example) is triggered. getTCData being synchronous, it does not seem to be a big deal to add a call as a fallback.

**Comment by jsnellbaker** [comment]
As part of the IAB spec, the CMP is supposed to immediately respond to the addEventListener registration with the current status of the TC Data.  

If the data was incomplete because the CMP was still partially loading, Prebid would get an idea that something is in the works and (in that case) ignore that temporary data and wait until a proper event is triggered.  

If the consent data was already loaded (ie in the tcloaded state), then CMP would provide the TC Data using the tcloaded event status in that immediate registration response.  This sequence would ideally be near-instant timing-wise and Prebid would go to process that result without the need for further calls to the CMP.

So if the CMPs are to spec, I don't see the need to make a separate call using the getTCData in the overall sequence of things here.

**Comment by chrispaterson** [comment]
The [public libraries ](https://github.com/interactiveAdvertisingBureau/iabtcf-es) never utilize the `"loading"` state, in fact within the commit group there's a motion to [remove it entirely from the spec](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/pull/225)

As far as the `'addEventListener'` vs `'getTCData'` I agree is @jsnellbaker `'addEventListener'` is the right way – In my opinion – to do it in PreBid.  I outlined how I would imagine the logic [on this other pull request](https://github.com/prebid/Prebid.js/pull/5564#issuecomment-670099583).
