### ISSUE TITLE
Passing additional data to dynamic floor provider 

### ISSUE THREAD

**Issue by pnhegde** [prebid/Prebid.js#5595]
## Type of issue

Feature Request / Question 

## Description
In this example, is there a way to send additional data to a 3rd party floor provider's endpoint apart from appending params to the url? 
```
pbjs.setConfig({
    floors: {
        enforcement: {
           floorDeals: true
        },
        auctionDelay: 100,
        endpoint: {
            url: 'https://floorprovider.com/a1001-mysite.json'
        }
    }
});
```

**Comment by bszekely1** [comment]
Hi @pnhegde, the http fetch to 3rd party floor provider's endpoints only supports the GET method. Since that is the case, the only way to pass data is through a query parameter.

If you like, you can submit a proposal for review to support POSTs and work on a PR once the community has approved a design.

**Comment by ChrisHuie** [comment]
closing issue please refer to answer provided on the nature of the Prebid interface
