### ISSUE TITLE
Is it possible to run two versions of Prebid in parallel?

### ISSUE THREAD

**Issue by GeorgiaREdwards** [prebid/Prebid.js#5596]
## Type of issue
Question

## Description
Is it possible to run two versions of Prebid in parallel? I can't find any documentation that references it as being possible.

**Comment by mkendall07** [comment]
I don't think it's technically supported (as in we test to make sure there are no problems) but in theory I think it should be fine if your name the PBJS global differently for each instance (https://github.com/prebid/Prebid.js/blob/master/package.json#L20)

**Comment by bretg** [comment]
@mkendall07 is correct in that it's technically possible, but to give a little more detail, we don't recommend doing this:

- the code isn't small. for performance reasons you don't want to run two versions if you can help it
- we don't test concurrent versions
- we won't specifically support debugging problems caused by running two concurrent versions. We'll take PRs if someone finds an issue

I'll add a FAQ entry.

**Comment by bretg** [comment]
http://prebid.org/dev-docs/faq.html#can-i-run-multiple-different-versions-of-prebidjs-concurrently

**Comment by GeorgiaREdwards** [comment]
@mkendall07 @bretg Thank you both for your responses! I'm trying to gather a bit more information as we are currently running JW Player VPB alongside our own Prebid setup. The JW Player's set up is done in a very similar way as they include PBJS, and have renamed the global name. Preferably, we would like to have them both working alongside.
