### ISSUE TITLE
How to disable consentManagement module for specific countries?

### ISSUE THREAD

**Issue by Sir-Will** [prebid/Prebid.js#5667]
## Type of issue

question
## Description
How do you disable the consentManagement module for specific countries?
I saw that you can set `gdprApplies` to false somewhere, but I was unable to find out where you are supposed to set that.

**Comment by GLStephen** [comment]
The recommended approach to disable the module is to send *no* Consent Management config at all.

The config you are referencing however is in the consentManagement config and is called "defaultGdprScope". More info here: https://docs.prebid.org/dev-docs/modules/consentManagement.html

```
consentManagement: {
"gdpr": {
  "cmpApi": "iab",
  "timeout": 8000,
  "defaultGdprScope": true
},
"usp": {
  "timeout": 100
}
}
```

**Comment by Sir-Will** [comment]
Currently, I'm not sending a config but it seems like prebid is sending that there is no consent from the user to the bidders resulting in almost no bids compared to older prebid versions.

**Comment by GLStephen** [comment]
Is this happening in non-GDPR countries? Do you have a test page?

**Comment by Sir-Will** [comment]
So it's always enabled for GDPR countries? Is it possible to disable it programmatically without the iab cmp?

**Comment by bretg** [comment]
Prebid.js doesn't have any concept of the geographic region where it's running. It's up to the CMP and/or publisher to configure Prebid.js correctly. Here are some options for discussing with with your lawyers, engineers, and CMP provider:

In these scenarios PBJS config can be the same across all geos:
1) The CMP does the geo-detection and passes 'gdprApplies: true/false' as appropriate. 
2) The CMP removes its in-page function when GDPR doesn't apply. 

In these scenarios, the publisher has to be aware of the geo and tell Prebid.js what to do:
3) When in the EEA, the page sets consentManagement config, but when not in the EEA, the page avoids setting the consentManagement config. GDPR enforcement is thus off.
4) When **not** in the EEA, the page sets consentManagement config with defaultGdprScope=false so that if the CMP is slow to respond then enforcement is off.

**Comment by bretg** [comment]
Closing this issue -- the concise answer to the original question is that Prebid.js doesn't provide a way to disable consentManagement module for specific countries.

As a result of this and other questions, we've started a page to serve as a repository of CMP best practices. https://docs.prebid.org/dev-docs/cmp-best-practices.html -- the community is encouraged to contribute there.
