### ISSUE TITLE
Bug CMP Prebid

### ISSUE THREAD

**Issue by salvoaranzulla** [prebid/Prebid.js#5792]
## Type of issue

Bug

## Description

I have updated my Prebid to Prebid 4.9.0. I have also added a new bidder (Triplelift). After the update, Prebid.js has stopped to bidding. If I see the JS Console, I see this error:

DEBUG-TRIPLELIFT.html?tl=true&pbjs_debug=true:454 next is not a function, probably a vendor invoked __tcfapi with parameter null. 
    at c.n [as callback] (https://www.aranzulla.it/DEBUG-TRIPLELIFT.html?tl=true&pbjs_debug=true:454:85847)
    at c.o.invokeCallback (https://www.aranzulla.it/DEBUG-TRIPLELIFT.html?tl=true&pbjs_debug=true:454:27761)
    at c.o (https://www.aranzulla.it/DEBUG-TRIPLELIFT.html?tl=true&pbjs_debug=true:454:27910)
    at c.a [as constructor] (https://www.aranzulla.it/DEBUG-TRIPLELIFT.html?tl=true&pbjs_debug=true:454:27494)
    at new c (https://www.aranzulla.it/DEBUG-TRIPLELIFT.html?tl=true&pbjs_debug=true:454:161556)
    at i.apiCall (https://www.aranzulla.it/DEBUG-TRIPLELIFT.html?tl=true&pbjs_debug=true:454:57415)
    at Object.iab (https://www.aranzulla.it/_adv/prebid4.9.0.js:5:2012)
    at Object.h (https://www.aranzulla.it/_adv/prebid4.9.0.js:5:3724)
    at u (https://www.aranzulla.it/_adv/prebid4.9.0.js:3:47040)
    at Object.r [as apply] (https://www.aranzulla.it/_adv/prebid4.9.0.js:3:47218)

The problem seems to be:

http://matteo.colucci.s3.iubenda.com/Screen-Shot-2020-09-28-11-54-20.png

The problem seems to be generated by this line inside Prebid:

http://matteo.colucci.s3.iubenda.com/Screen-Shot-2020-09-28-11-54-08.png

## Steps to reproduce

https://www.aranzulla.it/DEBUG-TRIPLELIFT.html?tl=true&pbjs_debug=true

## Test page

https://www.aranzulla.it/DEBUG-TRIPLELIFT.html?tl=true&pbjs_debug=true

**Comment by bretg** [comment]
@Fawke - can you take a look at the "next is not a function, probably a vendor invoked __tcfapi with parameter null" error?

@salvoaranzulla - what version are you upgrading from? I'd bet it's 3.x.

I see in your page that you're not specifying any parameters when initializing consentManagement:

```
                        consentManagement: {
                            cmpApi: 'iab',
                            timeout: 500
                        }
```

A very important change between 3.x and 4.x is that the default enforcement of TCF2 changed from yes to no.

Here are the references you should know about:

- https://docs.prebid.org/dev-docs/modules/gdprEnforcement.html
- https://docs.prebid.org/dev-docs/cmp-best-practices.html

**Comment by salvoaranzulla** [comment]
@bretg Hi,

I have upgraded from 4.6 to 4.9 but the bug is also at 4.6 version.

We are not using "GDPR Enforcement Module", but just GDPR module with this setting: "consentManagement:{cmpApi:'iab',timeout:500}})".

The error "next is not a function, probably a vendor invoked __tcfapi with parameter null." is shown just after:

"Prebid MESSAGE: Emitting event for: requestBids
Prebid INFO: Invoking pbjs.requestBids Arguments(1)"

The bidding doesn't start.

Prebid.js has not any problem to read the consent string: "INFO: Received a response from CMP" shows the right consent string from CMP.

**Comment by Fawke** [comment]
Hi @salvoaranzulla,

I tried to debug your page, but I could not see any problem with the place that you've highlighted. `adUnit.bids` is defined and is an array.

Can you tell me how to got this error? http://matteo.colucci.s3.iubenda.com/Screen-Shot-2020-09-28-11-54-20.png

Also, for me, after refreshing your test page a few times, I saw that the auction took place and I got bid responses. This makes me think that the way the cmp is getting loaded into your page is not consistent with "the recommended way." (Recommended way is - first loading a cmp stub synchronously, then asynchronously loading cmp code and the prebid code.)

Also, this error, `next is not a function, probably a vendor invoked __tcfapi with parameter null.` , it's originating from js code loaded on this page, `DEBUG_TRIPLELIFT.html`. Since this piece of code is not part of prebid.js, it will be helpful for us to know when this error is thrown. (I don't know if this error is thrown my the cmp you use, or it is some proprietary code that you wrote)

**Comment by salvoaranzulla** [comment]
Hi @Fawke,

The error "next is not a function, probably a vendor invoked __tcfapi with parameter null" is generated by CMP when:

- a vendor calls the function __tcfapi with parameter null (instead of "undefined" as IAB specs) 

- when the callback generated an error (for example __tcfapi('getTCData', 2, function(tcData) { notExistingFunction(); }) ).

To reproduce the error, you can do this:

1) Open a new window in incognito mode in the browser and open Javascript console

2) Click on button "Accetta "

If you want, you can add a conditional breakpoint at this line of Prebid.js http://matteo.colucci.s3.iubenda.com.s3.eu-central-1.amazonaws.com/Screen-Shot-2020-09-30-18-19-27.png before clicking on "Accetta".

3) You will see the error in the Javascript console


Tell me if you see the error.

Salvatore

**Comment by Facens** [comment]
Hi @Fawke,
I work for iubenda, the company that provides the CMP used by @salvoaranzulla's website.
Here are some additional details on the issue:
- the exception is not surfaced because the IAB's SDK catches it and invokes the callback in a way that makes our code log "next is not a function", that's why you need to set the conditional breakpoint to see that `i.bids` is undefined (I'm going to open an issue on the SDK's repo about that)
- the value of `i` when `bids` is undefined is:
    ```json
    {
      "pubstack": {
        "adUnitName": "ad-in-article-20",
        "adUnitPath": "/1018461/enablelazyload-25-ad-in-article-20"
      },
      "mediaTypes": {
        "banner": {
          "sizes": [
            [300,250],
            [336,280]
          ]
        }
      },
      "sizes": [
        [300,250],
        [336,280]
      ]
    }
    ```
- the callback of `__tcfapi` is invoked synchronously as per TCF's spec.

**Comment by Fawke** [comment]
Hi @Facens, @salvoaranzulla,

Yes, I can see what you're talking about. I was able to capture a screenshot of the adUnits, when requestBids is called.

<img width="1680" alt="Screenshot 2020-10-01 at 3 12 33 PM" src="https://user-images.githubusercontent.com/14229985/94794193-2ce6df00-03f9-11eb-8593-7eac123cfa39.png">

As you can see, we have the object `adUnit.bids` defined for all the ad units except the one with the code, `ad-in-article-20` which make me think that this particular placement was not defined correctly. @salvoaranzulla can you check the setup for this ad unit once?

Still, on the Prebid side, we should have a check in place to see if adUnit.bids is defined and then process the bids. I'll include this check.

**Comment by salvoaranzulla** [comment]
@Fawke @Facens I have updated the debug page removing "ad-in-article-20": Prebid.js does all auctions without "ad-in-article-20", but I still see the CMP warning " [IUBCS|WARN]: next is not a function, probably a vendor invoked __tcfapi with parameter null. "

**Comment by matita** [comment]
@salvoaranzulla it's again pubmatic that's explicitly invoking `__tcfapi` via `postMessage` by passing `parameter: null`, so probably it's not related to Prebid http://matteo.colucci.s3.iubenda.com/Screen-Shot-2020-10-05-10-05-18.png

**Comment by Fawke** [comment]
@salvoaranzulla We would like to close this issue if your problem is resolved. (It looks like it is, your test page no longer threw the cmp warning message when I tested it today.)

Let us know if you need any more help.
