### ISSUE TITLE
Under Monetized & Impression Loss - Headerbid Expert Page Analysis

### ISSUE THREAD

**Issue by ktmcc** [prebid/Prebid.js#589]
Fair warning, I know enough to be dangerous, but we are implementing prebid sans developer. Lots of issues and questions are coming!

We continually receive the following errors. How do we resolve them? Here's our [test page](http://www.suncycler.com/work_docs/Untitled-4.html?pbjs_debug=true).
![screen shot 2016-08-31 at 10 23 13 am](https://cloud.githubusercontent.com/assets/21362995/18132504/2093cce0-6f65-11e6-85a9-dad551e64816.png)

**Comment by mkendall07** [comment]
@ktmcc 
The headerbidd expert tool is useful to see what's going on but it doesn't necessarily mean something is broken. I would expect Rubicon to be loaded later because they have an extra hop (to load their library) before bid request is sent out (see this thread for a way to mitigate this: https://github.com/prebid/Prebid.js/issues/545)

The time to send out DFP request is dependent on the timeout and also on what else is going on in the page. What is the timeout set to?

**Comment by mkendall07** [comment]
Closing this out. Please re-open if you have more concerns.
