### ISSUE TITLE
User Id optout

### ISSUE THREAD

**Issue by jdwieland8282** [prebid/Prebid.js#5939]
## Type of issue
feature request

## Description
Today user id modules set user ids in cookies in the 1st and 3rd party, for those cookies set in a first party context we rely on the publisher to add the proper opt outs and privacy language in their T&Cs.  This arms length approach needs to mature especially as privacy advances made by the IAB and WC3 become more important.  As technology providers for publishers we have a responsibility to give publishers easy to use configurable tech that meets their needs.  Simplifying opt out, reducing publisher liability, and most importantly respecting users right to opt out should be a goals of the user id module and its sub adapters.     

### Expected results
Opt out messaging on the publisher page needs to be highly configurable by the publisher, we propose a basic optout treatment consisting of some general text, a checkbox, and a submit button. All of which would be part of the UserId module not individual sub adapters and turned off by default. A publisher could choose to turn this feature on and configure its styling as desired. 

When a user signals their opt out, all user id sub adapters are prevented from pushing their ids to bid adapters. 

Finally, an opt out cookie is set as a first party cookie in the users browser.  Each time the UserId module loads it should check for this cookie and act accordingly.

**Comment by smenzer** [comment]
@jdwieland8282 how does this align with IAB Tech Lab initiatives like TCF and USP? How should a publisher that already has a CMP on page use this proposed feature?

**Comment by jdwieland8282** [comment]
I see consent and optout as similar but in need of separate treatments, TFC doesn't apply globally but in almost all jurisdictions users have the legal right to declare an optout preference. 

If Pub.com has the id5 user id subadapter installed and a CMP, traffic from the EEA engages the CMP opt**in** work flow, while non EEA traffic engages the opt**out** work flow. In the latter case, we are talking about blocking user ids when a user optsopt, and setting a pub.com specific opt out signal in a 1pc.

**Comment by smenzer** [comment]
@jdwieland8282 ok so you would defer to the frameworks when they apply, but where there's not a framework then this becomes relevant, is that right? seems reasonable to me.

i also wonder if users will really know what it means to opt out of "the user id module" rather than understanding what user ids are _used for_ (targeting, measurement, frequency capping, retargeting, etc) - this is the complexity that exists in the TCF to give users "human readable choices" rather than asking if they want to allow "pbjs user id modules" to operate or not.

to be very clear, i completely agree we need to make user choices simple, transparent, and understandable and that prebid has an opportunity to help here - i'm just questioning whether we should be adding another "framework" to the list that publishers need to implement rather than what the techlab is working on with the global privacy framework (@alextcone may be able to provide more insights here)

**Comment by jdwieland8282** [comment]
> @jdwieland8282 ok so you would defer to the frameworks when they apply, but where there's not a framework then this becomes relevant, is that right? seems reasonable to me.

Right. 

> i also wonder if users will really know what it means to opt out of "the user id module" rather than understanding what user ids are _used for_ (targeting, measurement, frequency capping, retargeting, etc) - this is the complexity that exists in the TCF to give users "human readable choices" rather than asking if they want to allow "pbjs user id modules" to operate or not.

I'd phrase the opt out as something like "optout of tracking for advertising purposes" but I'm not an attorney.  We do have an attorney now who we can get language from. I'm not proposing an alternative to TCF, but just a way for publishers to offer an optout to their users.  We have a lot of userid modules in play now, and it's not clear to me how I would signal from pub.com that id do not want id5, sharedid, etc to track me. 

I'm not opposed to integrating against a Global TCF, I'd see this as a stop gap while that framework is defined.

**Comment by smenzer** [comment]
got it ok. i think the future state we agree on and i agree with the sentiment about giving pubs the opt-out offering to their users in some way.

**Comment by alextcone** [comment]
To be clear, you are suggesting that when ePrivacy, the GDPR or CCPA do not apply to an impression use this opt out? Have you spoken to NAI, DAA, DAAC or EDAA? More importantly, is your lawyer aware that whatever is done here will need to have some level of consensus among entities in the supply chain otherwise this will just become another DNT signal and cause similar industry backlash?

**Comment by jdwieland8282** [comment]
@alextcone I'm suggesting that publishers give users the same opt-out choices companies like Magnite provide. For example if I go to https://rubiconproject.com/privacy/consumer-online-profile-and-opt-out/ I can signal to Magnite that I do not want to be tracked. Now that 3rd parties are helping publishers address users, we need to port some of the opt-out functionality from vendor to publisher.

**Comment by gglas** [comment]
@jdwieland8282 hey Jeff -- we have a method for this in Prebid -- https://docs.prebid.org/dev-docs/modules/userId.html#publisher-first-party-opt-out -- I get the feeling this is "half" of what you're asking for, but is this a solution for the most part?  Historically, Prebid stays out of user-based interactions and leaves those to companies like CMPs, and we would assume that Publisher's have their own processes in place to handle this.

**Comment by jdwieland8282** [comment]
optout suffices
