### ISSUE TITLE
Add Prebid GVL ID to PubCommon and SharedID User modules

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#5964]
## Type of issue
Enhancement

## Description
Prebid now has a TCF vendor ID that we can use in the user ID modules owned by the organization.

Please add GVLID 887 to both modules.

I believe there are two aspects to this:
1) the call to `getStorageManager()` should pass in GVLID and the name (PublisherCommonId)
2) the spec passed to submodule() should contain gvlid.  (pubCommonId.js doesn't call submodule()?

**Comment by jdwieland8282** [comment]
@bretg line 24 [here](https://github.com/prebid/Prebid.js/blob/master/modules/pubCommonIdSystem.js) references  "pubCommonId" not "PublisherCommonId", do you know which is correct?  While we are thinking about it the GVLID is tied to prebid.org, instead of 

`const storage = getStorageManager(null, 'pubCommonId');

Should it be?

`const storage = getStorageManager(887, 'prebid.org');

**Comment by smenzer** [comment]
> Should it be?
> 
> `const storage = getStorageManager(887, 'prebid.org');`

It needs to be the same as the module name, which according to https://github.com/prebid/Prebid.js/blob/master/modules/pubCommonIdSystem.js#L161 is `pubCommonId`

so line 24 should be

`const storage = getStorageManager(887, MODULE_NAME);`

or better yet, set your GVLID as a variable since you'll need it later in the definition of `pubCommonIdSubmodule`

**Comment by SKOCHERI** [comment]
In SharedId user id submodule, the storageManager.js is not used as it is just generating the id value and relying on index.js (userid module) to set the value in cookie/localstorage based on the configuration. SharedId submodule doesn't set any additional cookies like other modules like indentityLinkIdSystem has retry set in cookie, id5 has id5id.1st_{Partner_id}_nb
