### ISSUE TITLE
video playerSize width and height wrong way around

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#6018]
prebid 4.15.0

something is making the playerSize the wrong way around for appnexus, so it totally messes up other bidder, with playerSize being a required attribute on the adUnit:

![DevTools_-_c](https://user-images.githubusercontent.com/8503167/99998062-fc4a7280-2db5-11eb-8354-65d43f5ba1a2.png)

**Comment by bretg** [comment]
Good find @spormeon -- this is a problem in the Prebid Server Bid Adapter -- https://github.com/prebid/Prebid.js/blob/cebae4a07748bcf0570e1781c31bb9f865bffbab/modules/prebidServerBidAdapter/index.js#L753

The PBJS 'playerHeight' and 'playerWidth' values are set (backwards) in pbsBidAdapter from the original PBJS bidRequest -- but I don't think anything downstream actually uses them, which is why it hasn't been noticed until now.

Still, something that needs to be fixed.
