### ISSUE TITLE
Bug filterSettings in 'exclude' bidders

### ISSUE THREAD

**Issue by richaudience** [prebid/Prebid.js#6082]
## Type of issue

BUG

## Description

We have detected a bug in the configuration of the userSync.
The problem is that the iframe has more priority than the image and then you’re blocking the sync after the first run reading the iframe “exclude” even if it the image one (the latter one) has the correct filter. This results on the image syncing never being launched.
Can you please push a change where the exclude option is applied after the include ones are launched?

## Steps to reproduce

Set the following configuration

`
var adUnits = [{
            code: 'div-gpt-ad-1460505748561-0',
            mediaTypes: {
                banner: {
                    sizes: [[300, 250], [300,600]]
                }
            },

            // Replace this object to test a new Adapter!
            bids: [{
                bidder: 'richaudience',
                params: {
                    pid: 'ADb1f40rmi',
                    supplyType: 'site'
                }
            }]

        }];

pbjs.setConfig({
    userSync: {
        filterSettings: {
            iframe: {
                bidders: '*',   // '*' means all bidders
                filter: 'exclude'
            },
           image: {
                bidders: '*',   // '*' means all bidders
                filter: 'include'
            }
        }
    }
});`

### Expected results
To be able to launch the image sync with the RA adapter

### Actual results
No sync launched

**Comment by jsnellbaker** [comment]
Hi @richaudience 

I'm not sure I'm following the described issue.  There should be no inherent priority of iframe vs image pixels within the logic userSync, these two aspects should be compartmentalized depending on how the publisher set up the config.

I tried to use the provided test params in this ticket, but it seemed the ad server returned the following commented code instead of a valid bid object:
```//NA3.6```

I tried other test params from the `richaudienceBidAdapter.md` file, however, those too only provided the commented code seen above or just no response at all.

To note - I did try another bidder who returns both image and iframe userSyncs.  When I tried to mimic the config provided above - I correctly saw the iframe sync was blocked and the image syncs were permitted.  So in this case, it seemed the module was working correctly.

If you can take a look at the test params for the `richaudience` bidder (to get a valid bid to return), I can certainly take another look into this matter.  Please let me know when you can.

An additional final note - I'm not sure if this was perhaps a typo, but if you want to enable all bidders for the userSync configs you need to pass `'*'` not just `''`.  Without the `*`, it's considered an invalid config and the module falls back to the default logic (where all image syncs are allowed and all iframe syncs are blocked).

**Comment by richaudience** [comment]
Here’s a test page where you can check the issue,
First of all, you must load a cookie that bypasses the //NA errors (it’s a brandsafe check from our end)
As you can see, the image sync isn’t loading correctly on the network tab.
Looking forward to hearing back from you,

[SetCookie](https://sync.richaudience.com/pwm/?v=gB8dqaNWlm)
[TestPageRA](https://labs.richaudience.com/cert/certis/testPagePrebid.php?pbjs_debug=true)

**Comment by jsnellbaker** [comment]
Hi @richaudience 

Thank you for providing the extra testing info.  I did some digging and found what's causing the behavior you're seeing.

The `syncOptions` param in the `getUserSyncs` function is primarily just reading the config set by the publisher to see if certain types of filters were specified.  If the config (for example `iframe`) is listed, then the flag here is activated for the bidder so they can submit a sync URL for that type, where it later gets evaluated against the logic the publisher had specified for that bidder.

So in this type of config, where both types of syncs are specified - both the `iframeEnabled` and `pixelEnabled` properties in the `getUserSyncs` `syncOptions` param are set to `true`.  In the case of the `richaudience` bidder, this means the iframe sync is added to the internal `syncs` array object before it gets to the logic for the image syncs.  As a consequence, the conditional if statement for the image syncs (`syncs.length == 0`) fails its check and doesn't attempt to register the intended image sync URL.

Given the current core logic, there are some options to get the image syncs to register:
- could remove the `iframe` config from the setConfig.  By not listing it, the `syncOptions.iframeEnabled` field would be set to `false` and this would let the logic in the `getUserSyncs` function to skip over the code for iframe sync and should logically go into the image sync code.
- another option would be to alter the if-condition logic for the image sync to not read the `syncs.length`.  This would allow both types of syncs to try to register and be checked against the publisher's config rules.  If the rules only allowed one type, then the filtration will happen and the core userSync code would load the proper sync.

Either of the two options above should work without any changes to the core code.  

That said, I am considering that we may want to make a core logic change to try to preemptively evaluate the rules set by the publisher for each bidder and update the `syncOptions` param based on the result for that bidder to provide a better picture up-front about what the bidder can expect to happen before they register.  

I'm not sure if a change like this would have other negative impacts or affect the implementations used by other bidders that are expecting the logic we have today (ie a semi-breaking change).  I will think on this more and consult with others to get their opinions.

I hope the information above helps; please let me know if you have any questions.

**Comment by patmmccann** [comment]
@richaudience does the solution proposed by @jsnellbaker achieve your intended result? If so, we plan to add documentation to make the implementation more clear.

**Comment by richaudience** [comment]
Sorry for not response for so long, we already have a solution for this in the next version I will upload the changes.
Thanks for the feedback.

**Comment by richaudience** [comment]
I close issue, add new pull request: [https://github.com/prebid/Prebid.js/pull/6523](url)
