### ISSUE TITLE
Previous consent-string value is sent to the bidders

### ISSUE THREAD

**Issue by mlapeyre3** [prebid/Prebid.js#6141]
## Type of issue
Bug

## Description
Hi,
As part of an investigation of our bidder, we noticed that the consent-string value returned by prebid to our adapter (when triggering a bidRequest) is not the latest one. You can find below my test plan to reproduce the issue on a page in production. I have simplified the consent-string value to show you exactly which one is logged by prebid.js debugger and which one is actually used by the bidders. The correct value is used only at the second refresh of the page.

## Steps to reproduce
Load the page from private navigation
INFO: Received a response from CMP
tcString: “DEFAULT CONSENT-STRING"
Call to Smart with the consent-string "DEFAULT CONSENT-STRING"

Without refreshing the page, accept all
INFO: Received a response from CMP
tcString: “POSITIVE CONSENT STRING“
(10 purposes and 606 vendors allowed)
No new call to Smart

Refresh the page
INFO: Received a response from CMP
tcString: “POSITIVE CONSENT STRING“
(10 purposes and 606 vendors allowed)
INFO: Bids Requested for Auction with id: fcd32906-f83f-4eba-bbb6-1372daff655
Call to smart with the consent-string “DEFAULT CONSENT-STRING"

Refresh the page again
INFO: Received a response from CMP
tcString: "POSITIVE CONSENT STRING“
(10 purposes and 606 vendors allowed)
INFO: Bids Requested for Auction with id: 1bd85e2b-969c-4d38-b299-9228f44244b
Call to smart with the consent-string "POSITIVE CONSENT STRING"

Edit CMP settings to decline all
INFO: Received a response from CMP
tcString: “NEGATIVE CONSENT-STRING“
(only legitimate interest remains true for 9 purposes)
No new call to Smart

Refresh the page
INFO: Received a response from CMP
tcString: "NEGATIVE CONSENT-STRING“
(only legitimate interest remains true for 9 purposes)
INFO: Bids Requested for Auction with id: 2004303a-dbde-4a29-a5a8-b18ec3d79f4
Call to smart with the consent-string "POSITIVE CONSENT STRING"
Call to Appnexus with  consent-string "POSITIVE CONSENT STRING"

Refresh the page again
INFO: Received a response from CMP
tcString: "NEGATIVE CONSENT-STRING"
INFO: Bids Requested for Auction with id: a40d90e5-c0f8-4d08-88ce-dfd0a2f6221b
Call to Smart with the consent-string “NEGATIVE CONSENT-STRING"
Call to Appnexus with consent-string "NEGATIVE CONSENT-STRING"

## Test page
https://www.lefigaro.fr/actualite-france/gerald-darmanin-recoit-des-representants-de-policiers-et-gendarmes-20201218?pbjs_debug=true

### Expected results
If I update the consent-string value, I expect the next bidRequests to have the latest value.

### Actual results
I have the value before the update of the consent-string, I need to refresh the page one more time.

## Platform details
Prebid.js v3.25.0

**Comment by smenzer** [comment]
Hi @mlapeyre3 thanks for reporting this. I checked on the test page you sent and I can confirm I see the same behavior. However, I ran through the same steps  on a simpler test page (https://samples.id5.io/prebid/basic) and I do NOT see the same behavior.

On lefigaro, I see two versions of Prebid, v3.25.0 that comes from lefigaro (https://static.lefigaro.fr/figads/fgds-short-ttl.js) and v4.18.0 from hubvisor (https://cdn.hubvisor.io/wrapper/01BYK28ENND8X5G8K0AJ2DPK9E/hubvisor.js). 

If you look through the Console on that page, you can see that the consent information is received from the CMP by the figaro version, while bid adapters are being called by the hubvisor version. I haven't had a chance to dig deeper into the code yet, but I would guess that this is where the problem is. I'm guessing that the figaro prebid is getting the consent information from the CMP but it's not getting passed properly to the hubvisor version until after a page load, at which point hubvisor has already made the bid requests with the old tc string.

**Comment by mlapeyre3** [comment]
Hello @smenzer,

Thank you very much for your response and your investigation. I will let the publisher know about this issue and I hope this will solve the problem 🙂

Have a great day and a happy 2021

**Comment by bretg** [comment]
@mlapeyre3 - may we close this?

**Comment by mlapeyre3** [comment]
Hey @bretg, yes I send this issue to the publisher but I don't see any response from them in this thread so let's consider it is ok !

Closing it :)
