### ISSUE TITLE
Update Webpack to more current version

### ISSUE THREAD

**Issue by pm-harshad-mane** [prebid/Prebid.js#6179]
## Type of issue
Reduce the build-size of PBJS by removing dead-code at build time using webpack

## Description
Webpack 4.41+ supports dead-code-elimination.
More details about dead-code-elimination: https://bundlers.tooling.report/transformations/dead-code/
Webpack example: https://github.com/GoogleChromeLabs/tooling.report/tree/live/tests/transformations/subtests/dead-code/webpack
This will reduce the file size of the final build.

**Comment by pm-harshad-mane** [comment]
Some help here, https://gist.github.com/gricard/e8057f7de1029f9036a990af95c62ba8

**Comment by patmmccann** [comment]
@pm-harshad-mane do you have a sense of impact on final build size for a minimal or typical build?

**Comment by pm-harshad-mane** [comment]
@patmmccann  i do not have estimations of the impact. 
Today i checked un-used code percentage shown in Chrome Dev tool for prebid.js is very high, used only pubmaticBidAdapter and prebidServerBidAdapter in the build and the un-used code percentage is 53.5%

**Comment by pm-harshad-mane** [comment]
@ChrisHuie , You might already know that Prebid build process has two options build and bundle.
In build, each module/ bidder code is build into respective minified files.
and in bundle the required bundles are concatenated into a final code that we deploy.
When we call `gulp build`, `bundle` is also called internally.
Based on the modules/bidders in final code,  the list of required functions from a particular package (say utils) may change.
So considering our bundle functionality, am wondering if web-pack will be able to take care of removing un-used functions correctly...

**Comment by ChrisHuie** [comment]
Currently working to update webpack to a workable version that support this (we are on v3). The only major difference is a plugin we currently use needs to be rewritten to the now internal implementation.

**Comment by gglas** [comment]
This is related to https://github.com/prebid/Prebid.js/pull/6663 -- we should be able to upgrade and take advantage of this when we can clean up the old dependencies.

**Comment by patmmccann** [comment]
@pm-harshad-mane are there other goals to updating webpack? if not, it seems we can consolidate into 7867, if so, it seems we should keep open

**Comment by dgirardi** [comment]
@pm-harshad-mane I have a PR for upgrading webpack in https://github.com/prebid/Prebid.js/pull/7935
I did not see an improvement in the bundle size, but I am also not sure that I should (from [this guide](https://webpack.js.org/guides/tree-shaking/)):

- `sideEffects` should remove unused files from the bundle, but since the linter will already prevent unused imports, I think that  would only apply to files that have a "naked" import and no side-effects (`import 'unused-file.js')`. I don't believe we have any, and if we do, they should be removed. 
- `usedExports` should help the minifier detect dead code, but it had no effect for me. I also tried (not in the PR) using [TerserWebpackPlugin](https://webpack.js.org/plugins/terser-webpack-plugin/) instead of running terser via gulp as we do now, that results in a tiny size increase.
