### ISSUE TITLE
Prebid analytics with ga - missing event

### ISSUE THREAD

**Issue by soman** [prebid/Prebid.js#6189]
## Type of issue

question

## Description
Enable prebid analytics with ga. Built prebid.js with google analytics adapter.
I'm not seeing any ga event information from google analytics report. Also not seeing from browser console with ?pbjs_debug=true

**GA log below:**

![prebid ga log](https://user-images.githubusercontent.com/2465685/104551043-4c301200-5660-11eb-939f-fd508e6cfa2a.jpg)

**Gtag code:**

![gtag](https://user-images.githubusercontent.com/2465685/104551337-e8f2af80-5660-11eb-9d08-4d523e3e801e.jpg)

### Expected results
I want to see the ga events log from both browser console and google analytics report.
https://github.com/prebid/prebid.github.io/blob/master/dev-docs/analytics-ga.md

**Comment by smenzer** [comment]
@muuki88 you're the only one to have touched the google analytics adapter in years...do you have any insights you could provide here?

**Comment by muuki88** [comment]
hi @soman 

I used the GA adapter quite a while ago, but dropped it due to bad data quality (we don't have Google Analytics 360 and sampling was really bad). Back than we integrated google analytics directly and not via gtag, not sure if that makes a difference.

Are there any analytics events being sent? I mean can you see them on the network tab? The logs you posted seem to say that there are indeed events being sent to google analytics.

The docs you reference show some diagrams when you actually analyse the data inside google analytics.

**Comment by DavidBowdoin** [comment]
@soman, I wrote a bit of adapter code 2 years ago:
```
function gtagTOga(a, b, category, action, label, value, fieldsObject) { gtag('event', action, { event_category: category, event_label: label, value: value, non_interaction: true }); }
pbjs.que.push(function () {
     pbjs.enableAnalytics([{ provider: 'ga', options: { enableDistribution: true, global: 'gtagTOga' } }]);
});
```

**Comment by gglas** [comment]
@soman have you had any luck with this issue / is it outstanding?

**Comment by gglas** [comment]
@soman closing this issue pending your response
