### ISSUE TITLE
[QUESTION] How to add more than two banners on the same page? 

### ISSUE THREAD

**Issue by yegorWaardex** [prebid/Prebid.js#6234]
## Type of issue

question

## Description

I want to add as more ads as I click on the button but something goes wrong after the second add. 

## Steps to reproduce

I've created a sample HTML page, just click on the "add new banner" 4+ times and you will see following picture: https://share.getcloudapp.com/ApuR62N7

Sample page is here: https://jsfiddle.net/1esvzrng/

## Test page

Sample page is here: https://jsfiddle.net/1esvzrng/

### Expected results
As more ads as I click on the button should be displayed

### Actual results
Only 2 ads are displayed

## Platform details

-

## Other information

-

**Comment by ChrisHuie** [comment]
Hey @yegorWaardex I have been digging into this and have a few ideas. Are you still having the same problem when getting blocked after adding more than one add with a button?

**Comment by wqi1972** [comment]
@yegorWaardex, it looks to me the result of the test page (https://jsfiddle.net/1esvzrng/) is not an issue.
That is due to the test GAM account 19968336 setup.
Inside GAM 19968336, the Prebid test lineitem only set 2 creatives, so you can only get the test ad show up in the same page twice, the house ad inside the 19968336 only set 1  creative. 
So you first get test ad show up 2 times, then house ad 1 time, after that GAM returns null, since there is no lineitem inside GAM available for this user session.
Inside your real GAM account, you can add more creatives inside Prebid lineitems to support the feature you need.
