### ISSUE TITLE
browserlist caniuse-lite outdated message when building

### ISSUE THREAD

**Issue by smenzer** [prebid/Prebid.js#6305]
## Description
When you build pbjs, there's a message at the top that says the `Browserslist: caniuse-lite is outdated` and suggests running `npx browserslist@latest --update-db` to fix this. I'm not sure what exactly this is used for and if we should update (or should should be responsible)...but I've seen this message for a while now so thought we should document and deal with it.

I'm not sure if this is an issue with my local environment or with packages used by prebid.

## Steps to reproduce
```zsh
$ gulp build
[08:56:04] Using gulpfile ~/src/Prebid.js/gulpfile.js
[08:56:04] Starting 'build'...
[08:56:04] Starting 'clean'...
[08:56:04] Finished 'clean' after 157 ms
[08:56:04] Starting 'build-bundle-prod'...
[08:56:04] Starting 'makeWebpackPkg'...
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
```

**Comment by ChrisHuie** [comment]
@smenzer 
Pretty sure Browserlist is just a config to define target browsers and versions. I think it is integrated directly into Babel but I could be wrong on that. 

I checked out the Babel/preset-env in the package-lock file and looks like this package is set to `"browserslist": "^4.12.0"` which should still be grabbing you the latest version of the package since there hasn't been a breaking version change as it's now on 4.16. 

I haven't come across this warning in my console yet though.

**Comment by bretg** [comment]
@smenzer - Chris and I chatted. We think you should try a fresh `npm install` and then try the build. Not happening for us.

**Comment by smenzer** [comment]
hi @bretg and @ChrisHuie  - thanks for taking a look. i did a fresh install but still getting it. sounds like it's local to my machine, though, so i'll look into it more on my end, I just brought this up to make sure it wasn't something impacting others. thanks!

**Comment by patmmccann** [comment]
appears to refer to db of which browsers are in the target 

https://github.com/prebid/Prebid.js/blob/eb5d18fb2d5b88aea5aeeb54e4c1be8e24de0dd4/package.json#L21

not sure how out of date it is

**Comment by patmmccann** [comment]
failed attempt to fix: https://github.com/prebid/Prebid.js/pull/11662

**Comment by patmmccann** [comment]
is this possible to solve by pushing https://www.npmjs.com/package/@babel/helper-compilation-targets to more recent version at https://github.com/prebid/Prebid.js/blob/master/package-lock.json#L249 ?

**Comment by patmmccann** [comment]
updating package-lock to https://www.npmjs.com/package/@babel/helper-compilation-targets/v/7.24.6 should fix?

**Comment by mkomorski** [comment]
The message is gone when I bump @babel/core to 7.24.6 but another problem shows up (same situation when I directly update version of `browserslist` so I believe it's a root cause). I can see runtime errors in each place when vars are initiated in this way:

`const bid = {
      'bidder': 'adg',
      'params': {
        id: '58278', // banner
      }
    };

    it('should return false when required params are not passed', function () {
      **let bid = Object.assign({}, bid);**
      delete bid.params;
      bid.params = {};
      expect(spec.isBidRequestValid(bid)).to.equal(false);
    });`

`ReferenceError: Cannot access 'bid' before initialization`

or (which I don't actually understand tbh since it's the first declaration of BID_ADAGIO):

`const BID_ADAGIO = Object.assign({}, BID_ADAGIO, { ... })`

Lots of tests fail because of this, so increasing mentioned libs versions would require to refactor all of those in order to get rid of caniuse-lite message

@patmmccann
