### ISSUE TITLE
gdprEnforcement and prebid-server: User sync not allowed for null

### ISSUE THREAD

**Issue by rsnigel** [prebid/Prebid.js#6325]
## Type of issue
When using prebid-server together with gdprEnforcement, each server side bidder causes a warning that user sync is not allowed for null. Not checked in detail, but it looks like it completely breaks the user sync for server side bidders.

Message:
utils.js:257 Prebid WARNING: User sync not allowed for null

## Description
Setup:
* 4 client side bidders
* 4 server side bidders
* prebid compiled with consentManagement, gdprEnforcement, and prebidServerBidAdapter modules (and others for bidders)
* prebid.js 4.26.0

User sync for the client side bidders is working as expected.

### Client side bidding
When looking at src/adapters/bidderFactory.js:201, the responses and consent information is passed to `registerSyncs`. This is used within the function to pass it to the gdprEnforcement module and it works as expected.

### Server side bidding
In modules/prebidServerBidAdapter/index.js:288, `registerSyncs` called with empty parameters. This is passed to the gdprEnforement module which is causing in modules/gdprEnforcement.js:219 to return `null` for the `config.getCurrentBidder()` and further more failing the validation and rejecting purpose1Rule, therefore rejecting the user sync.

## Steps to reproduce
When running this setup, you only need to have server side bidders enabled and the gdprEnforcement module will issue the warning "utils.js:257 Prebid WARNING: User sync not allowed for null" in gdprEnforcement:225.

### Expected results
Server side bidding should be working with gdprEnforcement and no warning should be issued.

### Actual results
Server side bidding user sync is not working due to bug in gdprEnforcement/ServerBidAdapter.

**Comment by bretg** [comment]
I agree there's a spurious warning here, but it's unclear to me that user syncs are broken. I set up a local test page and see the server-side sync happening.

1) We still want to be able to do client-side user-syncs for server-side bidders because there are DSP syncs that can take place and without doing some client-side syncing, there may be a cold-start problem.  (Related tangentially to #6361)
2) As for the warning, set a breakpoint at line 16699 of sneezy.aws.rubiconproject.com/rp-eng-soln/prebid/prebid-431-multibid-debug.js
3) I don't understand the code in generateTrap() -- it seems to be walking off the end of an array on purpose.


Here's a test page
[prebid_server_test_1001-gdpr.txt](https://github.com/prebid/Prebid.js/files/6260437/prebid_server_test_1001-gdpr.txt)

**Comment by ChrisHuie** [comment]
@rsnigel we believe this is a warning but not an actual blocking of user sync? Is this what you are experiencing? If not could you please provide a test page.

**Comment by dgirardi** [comment]
@rsnigel I cannot reproduce using prebid master. Is this still an issue? I tested with the page @bretg provided and I do see the warnings there (using prebid v4.31.0-pre), but they go away after updating.
