### ISSUE TITLE
Amazon adapter removal

### ISSUE THREAD

**Issue by jeff-crosby** [prebid/Prebid.js#64]
I am trying to use Prebid with OpenX, Yieldbot and Amazon A9. I see where the Amazon adapter used to be part of Prebid, but it was removed not long ago. Can you tell us why it was removed?

**Comment by RobertLippens** [comment]
@mkendall07 I would like to second this question - we would have loved to use the Amazon bidder, but noticed you removed it in an older commit.  What was the reason for this?

**Comment by ialex** [comment]
I think main reason is that amazon doesnt return the cpm for bids at least in a readable way, so you still have to use Amazon line item in order to the bids to work, and te purpose of Prebid.Js is to integrate all bidders into a simple set of line items.

I think you should file a ticket into amazon so they can change the way they work or at least provide an  alternative that works with Prebid.js

**Comment by jfpsf** [comment]
Amazon has made it pretty clear that they want to work directly with each publisher, so I don't think you will get anywhere with that, but worth a try.

**Comment by prebid** [comment]
Hey everyone, sorry about the delay. Amazon prefers to work directly with a publisher. However we've heard many publishers ask how to fit Amazon into prebid.js' framework, so that Amazon is not given more or less time to respond than other bidders. This is to the publisher's best interest for increasing competition and bid density.

Prebid.js has a custom bidder adaptor feature, where the publisher can choose to add any custom bidder code in there. Once added, this custom bidder adaptor will be called at the same time and be given the same timeout as other bidders. Note that this custom adaptor doesn't change the publisher's existing ad server setup (line items, creatives, targeting) with Amazon.

Sample code here (with instructions at the bottom of the page):
https://gist.github.com/Heray/277d421bda2b827f43da

The small feature tweak hasn't been made into a Github release yet (will soon), but the prebid.js version in that Gist works.

**Comment by dmitriyshashkin** [comment]
Just a small warning for those who decide to use the solution above. As the adapter doesn't notify prebid about the response, prebid doesn't emit neither "response" nor "timeout" events. So unless you modify it further, you won't see anything in Google Analytics. At least this is the behavior I've encountered in 0.7.0
