### ISSUE TITLE
Feature Request: allow publishers to configure bid filtering on .meta fields

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#6453]
## Type of issue
Feature request

## Description
The discussion on #3115 is currently around the ability for bid filtering on meta fields. Publishers may want to filter particular values of meta fields (eg banned advertisers or incomplete dchains) or when they are missing (no dchain or advertiserDomain at all). Publishers may want this ability via modules or via setConfig. This issue is to give that discussion a home and allow for the closing of #3115

**Comment by Slind14** [comment]
Isn't this pretty simple to do with just a few lines of code using the getBidResponses and markWinningBidAsUsed to remove it.

To avoid hurting performance one needs to do these blocks server side no? Otherwise, bids get rejected and the second-highest bid at the exchange never makes it to prebid.

So to properly use this, one needs to track and monitor rejected bids as well. At this point, the few lines of code are nothing in comparison to the coding required for tracking and monitoring.

Am I missing something?

**Comment by patmmccann** [comment]
I think publisher logic here might be arbitrarily complex and there's an opportunity for a module, but I think you are right for simple cases.

**Comment by Slind14** [comment]
If it is arbitrarily complex won't a module be limiting publishers and in the end custom code will prevail?

I'm not trying to find the negatives here, just wondering if there is an actual use case where it makes sense to have a module.

**Comment by patmmccann** [comment]
I am imagining the geoedge and future related module(s) might include this feature

**Comment by patmmccann** [comment]
Would you mind hashing out your example a bit more if you think we can close this with doc?

**Comment by Slind14** [comment]
```js
pbjs.requestBids({
    bidsBackHandler: (bids) => {
        // loop through ad units
        Object.entries(bids).forEach(([adUnit, bids]) => {
            // invalidate blocked ads
            bids.forEach(bid => {
                if (isBlockScopedAd(bid.meta)) {
                    pbjs.markWinningBidAsUsed({ adId: bid.adId });
                }
            })
        });
        // continue normal logic
    },
});
``` 

Alternatively, one could loop do a while loop with getHighestCpmBids() ...

**Comment by allanjun** [comment]
Hi,

I'd say it would be important to provide publishers (and eventually bidders) visibility on the filtration rate. IMO this could be done on two ways:
- Adding post-bid filtering events to Prebid Analytics, so that publishers can see filtrarion rate per buyer and report top offenders
- Adding a Loss URL mechanism to buyers so they can receive RT feedback

If there is enough Publisher demand for .meta validation features (maybe after prebid 5.0), would make sense to package this into a dedicated module to easy this job (examples: to enforce adomain, bid.cat, bid > bidfloor, meta ids)

Allan

**Comment by gglas** [comment]
Going to push analytics events + further module enhancements, will document @Slind14's code snippet in examples for publishers to utilize if they so desire.
