### ISSUE TITLE
Cannot use prebid cache with "Outstream" video context

### ISSUE THREAD

**Issue by npeceniak** [prebid/Prebid.js#6620]
## Type of issue

Question / Clarification 

## Description
When trying to use the prebid cache (https://prebid.adnxs.com/pbc/v1/cache) with an outstream video media type the ad is never loaded into the cache. Looking at the code in auction.js it looks like there is a specific check for "outstream" I just don't understand why outstream media types cannot be cached?

Code from auction.js
```javascript
function tryAddVideoBid(auctionInstance, bidResponse, bidRequests, afterBidAdded) {
  let addBid = true;

  const bidderRequest = getBidRequest(bidResponse.originalRequestId || bidResponse.requestId, [bidRequests]);
  const videoMediaType =
  bidderRequest && deepAccess(bidderRequest, 'mediaTypes.video');
  const context = videoMediaType && deepAccess(videoMediaType, 'context');

  if (config.getConfig('cache.url') && context !== OUTSTREAM) {
    if (!bidResponse.videoCacheKey || config.getConfig('cache.ignoreBidderCacheKey')) {
      addBid = false;
      callPrebidCache(auctionInstance, bidResponse, afterBidAdded, bidderRequest);
    } else if (!bidResponse.vastUrl) {
      utils.logError('videoCacheKey specified but not required vastUrl for video bid');
      addBid = false;
    }
  }
  if (addBid) {
    addBidToAuction(auctionInstance, bidResponse);
    afterBidAdded();
  }
}
```

## Steps to reproduce
Using the adunit configuration below 
```javascript
    const videoAdUnit = [{
      code: 'video1',
      mediaTypes: {
          video: {
              context: 'outstream', 
              playerSize: [[640, 480]]
          }
      },
      bids: [{
          bidder: 'spotx',
          params: {
            channel_id: 85394,
            ad_unit: 'outstream'
          }
      }]
    }];
...
    pbjs.setConfig({
      cache: {
        url: 'https://prebid.adnxs.com/pbc/v1/cache',
        ignoreBidderCacheKey: true
      }
    });
```

### Expected results
Outstream ad is loaded into the specified cache location then retrieved from the cache by the renderer.

### Actual results
When adUnit.mediaTypes.video.context = 'outstream' the ad is never loaded into the cache location provided and ad rendering fails. 

## Platform details

Tested using Prebid v4.35

**Comment by bretg** [comment]
@npeceniak - when using Prebid.js, why would you want to put outstream HTML in a cache?

For instream, the point of Prebid client-side caching is to put VAST XML in a network cache. This is needed because ad servers return a VAST URL to the in-page player, which pulls the VAST XML from the URL.

For outstream, the body of the creative is ad markup HTML, not VAST.  The creative in the ad server is just a regular banner, not video. It's expected that the HTML itself will be coded with the VAST location. There's no need to do client-side caching of the HTML.

When there's no Prebid.js (App and AMP), Prebid Server can cache the ad markup HTML which is retrieved by the Prebid Universal Creative (PUC) at render time.

**Comment by npeceniak** [comment]
Thank you for the explanation @bretg. This makes sense we just had a different idea of what "outstream" meant.
