### ISSUE TITLE
burl integration

### ISSUE THREAD

**Issue by asurovenko-zeta** [prebid/Prebid.js#7003]
## Type of issue
Question

## Description
Is there any guidline to support **burl** in adapter? I look at some conditions in **prebid.js** and notice **utils.callBurl(bid)** function, but it is not very obvious what needs to be done for the function to be called.
I can call that function directly, but it's not right way to implement burl logic I guess, so, I'd like to have the best practice to implement it.

Thanks!

**Comment by jsut** [comment]
Looking at the code, your adapter just needs construct a prebid bid with burl and source defined as top level keys in the bid structure. burl should be a url (i think) and source === CONSTANTS.S2S.SRC. That should cause the pixel to get triggered. 

Looking at the commit history it seems like it's only intended to be used by server to server adapters?  utils.callBurl doesn't have any documentation at all.  I'd think that burl should probably be mentioned in the list of [bidResponse parameters](https://docs.prebid.org/dev-docs/bidder-adaptor.html#interpreting-the-response), but it isn't.

Looking at the adapters in the repo, there are examples that trigger the burl pixel directly in the adapter, rather than letting prebid do it (modules/relaidoBidAdapter.js, modules/mediaforceBidAdapter.js, modules/adxcgBidAdapter.js). modules/readpeakBidAdapter.js uses them in it's native ad handling, and shoves the burl onto the list of impressionTrackers, which results in it getting called.

The only one that seems to result in utils.callBurl() getting called is modules/prebidServerBidAdapter/index.js

I don't really know what burl's even are, but looking at the code, and what the adapters that use them are doing, it seems like this could be cleaned up, and documented, and adapters could probably lose some code, and start leveraging the code that is already in prebid.js core.
