### ISSUE TITLE
Suppress (not necessarily fix) Console Errors

### ISSUE THREAD

**Issue by mkubarycz** [prebid/Prebid.js#7030]
## Type of issue
Question: Is there a way to suppress console errors

![image](https://user-images.githubusercontent.com/6887372/122071361-b04c3300-cdc4-11eb-944f-217a17e88d9d.png)

## Description
On our site, we see a ton of errors coming from prebid.js.  Most of them look like they are related to bad configuration on the ad-server side -- so my question is more about asking if there is a way to catch and suppress these errors to avoid flooding the javascript console rather than actually fixing them.  Please avoid judging that decision not to fix them if you can.

## Steps to reproduce
There is a screenshot above.  I redacted our site name for public consumption but this issue is easily reproducible on any browser on our site (DM me for the site name)

## Other information
prebid.js v4.25.0

Here is a link to the actual prebid script: https://storage.googleapis.com/didna_hb/prebid/didna_prebid.js.gz

**Comment by mkendall07** [comment]
hey @mkubarycz those seem to be errors from the chrome itself not something prebid is logging. I could be wrong but I don't know if there is a way to suppress them. They seem like legitimate network errors. Any idea why you have so many of those?

**Comment by gglas** [comment]
Yeah guys - after discussing in issue review today, these seem to be implementation related rather than core prebid execution related --  we'd recommend discussing with the adapters or checking on the implementation environment to see if it meets their expectations.  Closing this ticket for now - let us know if you have any further issues.
