### ISSUE TITLE
Handle undefined noP1Consent endpoint in pbs s2sConfig

### ISSUE THREAD

**Issue by muuki88** [prebid/Prebid.js#7046]
## Type of issue

bug / feature request

## Description

#6484 introduce two config options for requests with and without purpose1. We are hosting our own
prebid server and have not yet investigated how to faciliate the "no purpose 1" endpoint, so we didn't specify one.

```js
endpoint : {
  p1Consent: 'https://prebid.adnxs.com/pbs/v1/openrtb2/auction'
}
```

This causes a xhr call to `/undefined`, which is not ideal :stuck_out_tongue: 
If you are on example.com , prebid tries to call example.com/undefined

## Steps to reproduce

- Remove `noP1Consent` property

## Test page

None

### Expected results

Prebid server adapter is skipped

### Actual results

`/undefined` is called

## Platform details

prebid.js 4.43.0

## Other information

- #6484

**Comment by gglas** [comment]
@jsnellbaker this seems related to a feature from a few months back, mind having a look?

**Comment by jsnellbaker** [comment]
@muuki88 To confirm, you're only seeing this `undefined` request when you're trying to make a PBS request without consent (ie when purpose1 consent is not given) and you didn't specify the noP1Consent URL in the config?

I was trying to replicate this behavior and that was the only condition I found where it seemed to trigger this behavior.  Without any CMPs present on the page or when consent was given - using the above config, the PBS request went through fine (and only made 1 request to the endpoint).

For addressing the situation described above, we could try to scan the publisher specified `endpoint` config and copy the URL value from the `p1Consent` field to the `noP1Consent` field if the `noP1Consent` field didn't exist.  I'm not sure what else would be ideal, since someone could specify their own prebid server URL and we wouldn't know the 'correct' value for the non-consent requests.  Would this work?

**Comment by muuki88** [comment]
Thanks @jsnellbaker for taking a look :pray: 

> you're only seeing this `undefined` request when you're trying to make a PBS request without consent (ie when purpose1 consent is not given) and you didn't specify the noP1Consent URL in the config?

That is correct :+1: This is a rather common case as there's always a fair share of traffic where users don't give consent.

> we could try to scan the publisher specified `endpoint` config and copy the URL value from the `p1Consent` field to the `noP1Consent` field if the `noP1Consent` field didn't exist.

I wouldn't do that as there is no simple way left to deactivate prebid server for no consent traffic.

My suggestion would be to just not execute an ajax request:

https://github.com/prebid/Prebid.js/blob/191655ad6b7b43f625118c2a9a431916d0f83dda/modules/prebidServerBidAdapter/index.js#L1100-L1110

The same way as it's done a few lines above with the `cookie_sync`:
https://github.com/prebid/Prebid.js/blob/191655ad6b7b43f625118c2a9a431916d0f83dda/modules/prebidServerBidAdapter/index.js#L1089

**Comment by jsnellbaker** [comment]
Just to be sure - @bretg are you okay with the suggestion above?  

That is - to not execute the PBS request **at all** for this scenario; where the publisher did not specify the `noP1Consent` URL in their s2sConfig and the user did not give purpose1 consent.

**Comment by bretg** [comment]
I'm ok with this scenario:

1) if s2sConfig.endpoint/syncEndpoint is an object
2) if the p1Consent attribute is missing, don't call PBS when p1 consent is given
3) if the noP1Consent attribute is missing, don't call PBS when p1 consent is absent
4) if instead s2sConfig.endpoint/syncEndpoint is a string, it's used as both p1Consent and noP1Consent


This needs to be documented at https://docs.prebid.org/dev-docs/publisher-api-reference/setConfig.html#setConfig-Server-to-Server

**Comment by jsnellbaker** [comment]
Thanks @bretg - I'll put together a PR today.
