### ISSUE TITLE
Currency handling question

### ISSUE THREAD

**Issue by dapsych0** [prebid/Prebid.js#705]
Hi,

We've been looking through the various adaptors and have noticed that in some combinations, the currency returned from them is going to be different, but looking through the prebid code there doesnt seem to be a way to convert it... is this something we are expected to handle ourselves via the bidCpmAdjustment function?

e.g. Piximedia examples suggest EUR but most others we'd expect USD, or a currency provided in the response such as with Index or AOL

**Comment by mkendall07** [comment]
@dapsych0 
It's expected that you would work with a single currency and we don't expect to and any currency conversion process client side. 

With that said, you could use the `bidCpmAdjustment` adjustment to make these conversions if you want to incorporate different bidders. I'll ask bidders to specify their default currency in the bidders param page on prebid.org going forward.

**Comment by mkendall07** [comment]
@prebid/prebid-bidder-adaptors 
Can you comment on this ticket with your default adapter currency please?

**Comment by frazjp65** [comment]
Adblade is in USD.

**Comment by ojotoxy** [comment]
UnderdogMedia is always USD.

**Comment by JCarterGw** [comment]
J Carter Marketing is also USD only

**Comment by matan-ybrant** [comment]
Brightcom is USD.

**Comment by dapsych0** [comment]
Thanks guys, seems USD is the most widely used, though thats probably due to most adaptors being in the US.

**Comment by christopher-allene-piximedia** [comment]
Hello everyone, as you noticed our default currency is EUR. We also support bidding other currencies server-side, I submitted a PR to document the “currency” property to our bidder that allows sites to use USD if they wish.

Maybe it should be worth to have a standard property storing the currency (like the way “sizes” is working: you have a global value, that you can override from bidder to bidder).

In any case, I believe it would be difficult to adjust the currency in the browser, because the rates might be different across bidders.

**Comment by mkendall07** [comment]
Going close this out as I think Pixiemedia is the only bidder that is not USD, and they updated their documentation.
