### ISSUE TITLE
Unruly is not working for banner with the prebid version < 5.x

### ISSUE THREAD

**Issue by soman** [prebid/Prebid.js#7145]
## Description
Unruly is not working for banner with the prebid version < 5.x
I tried with 4.37,.0 4.43.0, and 4.9.0
It is working with 5.3.0 but some others adapter is not working with 5.3.0
So, I need to work unruly with the prebid version < 5.x

How can I solve this issue?

**Comment by ChrisHuie** [comment]
Just curious what adapter seems to be the issue with 5.3? We have had several recent updates to adapters for 5.0 :)

**Comment by gglas** [comment]
@soman we're aware of a number of publishers who are successfully using unruly with less than 5.x -- the issue seems like it could be elsewhere.  cafedelites.com , for example, is actively using unruly.  I think we're going to close this issue, and as you continue troubleshooting please feel free to open another.
