### ISSUE TITLE
mediaTypePriceGranularity not correctly applied to adServerTargeting

### ISSUE THREAD

**Issue by KianGroenen** [prebid/Prebid.js#7147]
## Type of issue
Question

## Description
Are the standard values 'high', 'medium', 'low' supported for mediaTypePriceGranularity?

**Comment by gglas** [comment]
Hey there @KianGroenen -- yes, it should work.

https://github.com/prebid/Prebid.js/blob/412277f72b97cab72644cb4a009f58067a165899/test/spec/unit/pbjs_api_spec.js#L720

if you have any issues, please feel free to reopen.

**Comment by bretg** [comment]
If you re-open, please do so with a full example showing what doesn't work. Thanks.

**Comment by KianGroenen** [comment]
## Description
When using both buckets and standard values (f.e. 'high'), the price granularity isn't correctly applied for all mediatypes present.
I've set up a jsfiddle with 2 price granularity configs defined 'workingGranularity' and 'brokenGranularity'.
I've also adjusted the bid response to get one with a high granularity to see if it actually gets applied correctly.
Run the jsFiddle with brokenGranularity and you can see the video-instream config isn't correctly applied to the adserver targeting.

## Steps to reproduce
1. Run the JSfiddle with 'brokenGranularity' variable in setConfig (as given)
2. run pbjs.getAdserverTargeting('video1');
3. result is hb_pb with high granularity.

## Test page
https://jsfiddle.net/yr2xL6v4/5/

### Expected results
hb_pb: 5.50
### Actual results
hb_pb: 5.54

## Platform details
Prebid.js 5.5.0
Browser: Chrome
OS: Windows

## Other information
Created an issue for this earlier but I wasn't able to figure out what caused it: https://github.com/prebid/Prebid.js/issues/6146

**Comment by bretg** [comment]
Spent some time with this. 

1) Prebid.js assumes that video ads will be in a separate auction. Things work the way you expect them to if you comment out the banner ads.

2) That said, I traced through some code and breakpoints -- think I see a minor bug and a maybe a major one that would prevent us from supporting a single auction covering multiple mediatypes.

The minor bug is in config.js -- it's checking for datatypes on val rather than val[item].

       set mediaTypePriceGranularity(val) {
         this._mediaTypePriceGranularity = Object.keys(val).reduce((aggregate, item) => {
           if (validatePriceGranularity(val[item])) {
-            if (typeof val === 'string') {
+            if (typeof val**[item]** === 'string') {
               aggregate[item] = (hasGranularity(val[item])) ? val[item] : this._priceGranularity;
-            } else if (utils.isPlainObject(val)) {
+            } else if (utils.isPlainObject(val**[item]**)) {
               aggregate[item] = val[item];
               utils.logMessage(`Using custom price granularity for ${item}`);
             }

However, even if this is fixed, it seems to me there may be a bigger issue... the getTargeting routines don't seem to be mediaType aware. 

Tracing through the output, I see the video-instream results are:
```
auto: "5.50"
custom: "5.50"    // this is the correct answer for video-instream
dense: "5.50"
high: "5.54"          // this is the banner results (high gran)
low: "5.00"
med: "5.50"
```

When getAdserverTargeting() is called, it's not clear to me that it has any mechanism to understand the request is for video. MediaType is not an arg -- I suspect this never worked for multi-mediatype auuctions . The targeting code is highly 'functional' and thus illegible and hard to debug for normal humans. If we prioritize a multi-mediatype auction, would need one of our super-humans to take a look. :-)


This all said @KianGroenen - please confirm that the workaround (constrain the auction to a single mediatype) works for you. Then we'll:

a) better document this
b) convert this issue to a feature request

**Comment by KianGroenen** [comment]
@bretg Yes, it works when the video mediatype is the only type in the request. For our sites we prefer to work with a single request with multiple types, so we only work with custom buckets now.

**Comment by bretg** [comment]
For the record, auctions are processed in parallel, so the page impact from splitting the auction should be negligible.

We'll discuss this issue in the next committee meeting.

**Comment by bretg** [comment]
@KianGroenen - made the docs change. Closing this out. We're not keen on rewriting the targeting components, so until there's solid community demand to support the 'mixed' use case, we're going to call this closed.

Thanks for bringing it up and helping others avoid the problem you discovered.
