### ISSUE TITLE
installedModules does not work for NPM build

### ISSUE THREAD

**Issue by muuki88** [prebid/Prebid.js#7287]
## Type of issue

Bug / Feature Request

## Description

The `pbjs.installedModules` returns `[ "v$prebid.modulesList$" ]` instead of the registered modules if built via NPM.

https://github.com/prebid/Prebid.js/blob/11df18dff4bf10f05ed01da62f214ce13690a2d2/src/prebid.js#L47

## Steps to reproduce

Built prebid via NPM as decribed in the readme.

## Test page

https://www.gutefrage.net/frage/kann-ich-ohne-abi-aber-mit-einer-pta-ausbildung-medizin-studieren

### Expected results

`pbjs.installedModules` returns all registered modules

### Actual results

 `[ "v$prebid.modulesList$" ]` is returned

## Platform details

Prebid 5.7

## Other information

- Feature was added in #6601

**Comment by patmmccann** [comment]
fyi @mmoschovas

**Comment by bretg** [comment]
@muuki88 - we're going to pick this up soon, but we're curious: how are you using the `installedModules`?

**Comment by dgirardi** [comment]
@bretg This is going to be hard to fix. `installedModules` is generated by our build process; if you're using a different build process you'll have to replicate the logic - we can think about making that easier, but all fast solutions will require the consumer to provide the list of modules they want in there. For example it would look like babel plugin parameters, instead of the current:

```
      {
        test: /.js$/,
        include: new RegExp(`\\${path.sep}prebid\\.js`),
        use: {
          loader: 'babel-loader',
          options: require('prebid.js/.babelrc.js')
        }
      }
```

We could have:

```
      {
        test: /.js$/,
        include: new RegExp(`\\${path.sep}prebid\\.js`),
        use: {
          loader: 'babel-loader',
          options: require('prebid.js/babelConfig.js')({ installedModules: [... manually maintained list of modules ...] })
        }
      }
```

Generating that automatically would require some research, I am not sure that module names are always inferrable from imports.

**Comment by dgirardi** [comment]
This is where we convert our build's `--installedModules` into files to include:
https://github.com/prebid/Prebid.js/blob/a2661725f9a39cf1c7cbf8f102d601769978a138/gulpHelpers.js#L73-L106

We need to reverse that and go from file to module name. It looks like that's doable with "internal" modules (because they all follow the patterns: `modules/moduleName.js` => `moduleName`, or `modules/moduleName/index.js` => 'moduleName'), but I don't see an easy way to detect external modules.

In practice, this means that if you are using prebid with a 3rd-party module as NPM dependencies, we can't tell that we should put the 3rd-party module in `installedModules`. So maybe a good middle-ground is to fix this for internal modules and require NPM consumers to manually specify 3rd-party modules in their babel config?

**Comment by bretg** [comment]
@snapwich - is externalModules related to the PBJS packager?

**Comment by bretg** [comment]
I'm not familiar with any external modules at all. 

If there's a solution where installedModules can be set for NPM but we can't support externalModules, that would be fine. 

If someone is depending on externalModules AND installedModules AND NPM, it's already not working for them.

**Comment by snapwich** [comment]
@bretg nope not related to the packager. looks like it is a new thing someone added a few months ago.

`pbjs.installedModules` as it is now doesn't really make sense in an npm context. currently `installedModules` is generated from the list of "installed modules" input in the command line when running the build step to make a pbjs bundle. the equivalent to that in npm i guess would be when you import a module, but that happens at runtime and there's not currently any way for pbjs to track that... so i think this is something that can't be supported unless we refactored how modules register themselves at runtime.

**Comment by dgirardi** [comment]
@snapwich if we are OK with `installedModules` not including modules that are oustide of the prebid package, we can make it work by generating it from our babel plugin: https://github.com/prebid/Prebid.js/pull/7739

**Comment by muuki88** [comment]
Sorry for being late to the party.

> we're going to pick this up soon, but we're curious: how are you using the installedModules?

We have a debugging console that shows our ad tag configuration, which also includes prebid. Sometimes devs forget to add modules or our yield managers want to check if module x or bid adapter y is acutally included.

So the main purpose is for on-site debugging of issues.

> but all fast solutions will require the consumer to provide the list of modules they want in there

I guess this causes more confusion than it helps :joy: You can import a module, but not specify it in the build or the other way round. The output of `installedModules` will be incorrect.

So I'm with @snapwich on this one "_but if you're doing that you might as well just hardcode the installed modules in your own code_"

> he equivalent to that in npm i guess would be when you import a module, but that happens at runtime and there's not currently any way for pbjs to track that... so i think this is something that can't be supported unless we refactored how modules register themselves at runtime.

I guess this would be a stable and predictable way to implement this. When modules register at runtime prebid pushes the module name to the `installedModules` array.
