### ISSUE TITLE
Include rubiconLite in Bidders' Params page 

### ISSUE THREAD

**Issue by caseybryan** [prebid/Prebid.js#759]
Can we please include "rubiconLite" to the Bidders' Params page? 
http://prebid.org/dev-docs/bidders.html#rubicon

Everything should be the same except for the following

bidder code:
rubiconLite

Send All Bids Ad Server Keys:
hb_pb_rubiconLite hb_adid_rubiconLite hb_size_rubiconlite

Default Deal ID Ad Server Key:
hb_deal_rubiconLite

**Comment by mkendall07** [comment]
I'm actually thinking it's time we deprecate the practice of adding every single bidder and bidder params into an example File. It's unwieldy to manage and not super helpful since no one will be running with that many bidders. 

Instead, all bidders should have docs on prebid.org (see https://github.com/prebid/Prebid.js/issues/659). Feel free to open a PR for RubiconLite adapter.

**Comment by mkendall07** [comment]
cc:
@bretg @snapwich
