### ISSUE TITLE
Is cedato adapter supported?

### ISSUE THREAD

**Issue by Hamper** [prebid/Prebid.js#7751]
## Type of issue

question

## Description

Cedato listed in documentation, but real module removed since prebid 5, is this adapter still supported?

## Platform details

Prebid.js 6.2.0

**Comment by ChrisHuie** [comment]
@Hamper with Prebid 5 there were a few updates that were required by some adapters like passing advertiserdomain. Most adapters have since made the needed changes and been added back. However, if they haven't made the updates they will essentially always now just be on the legacy 4 branch until the changes are made.
