### ISSUE TITLE
Bundle size inflated due to intra-module dependencies

### ISSUE THREAD

**Issue by dgirardi** [prebid/Prebid.js#7936]
## Type of issue
Bug

## Description
Prebid bundles are generated by concatenating "prebid-core.js" with a user-selected list of module files, which contain all dependencies of the module that are not in core. 

Since there is no real dependency tracking beside "core" or "not core", dependencies can be repeated across module files (if they [import from each other](https://github.com/prebid/Prebid.js/blob/4183f5d8f0875098e3041b366394ce24c43493cd/modules/adlooxRtdProvider.js#L14), or if they [import the same non-core file](https://github.com/prebid/Prebid.js/blob/master/src/AnalyticsAdapter.js)).

Fixing this requires coordination with external bundle vendors.

## Steps to reproduce

```
gulp build-bundle-dev --modules "adlooxRtdProvider,adlooxAnalyticsAdapter,id5AnalyticsAdapter"
```

Generated `prebid.js`: https://gist.github.com/dgirardi/86947f196a25fc753fbb6403094b97fe

- `AnalyticsAdapter` definition is repeated at lines #14737, #15830, #16447
- `adlooxAnalyticsAdapter` module is repeated at lines #14377, #15470

Problem persists in minified bundle, just harder to spot:

```
gulp build --modules "adlooxRtdProvider,adlooxAnalyticsAdapter,id5AnalyticsAdapter"
```

Generated `prebid.js`: https://gist.github.com/dgirardi/c3bb01de917407746950ec597cefbab2

- `"bundle"` (from [here](https://github.com/prebid/Prebid.js/blob/4183f5d8f0875098e3041b366394ce24c43493cd/src/AnalyticsAdapter.js#L28)) appears 3 times
- `window.pbjs.installedModules.push("adlooxAnalyticsAdapter")` appears twice

**Comment by snapwich** [comment]
having duplicate code show up in a `prebid.js` bundle is not necessarily a sign of a problem (and with analytics adapter it's not, but not sure about adloox case). the issues you've identified are known and were addressed with what i think are acceptable solutions:

the `AnalyticsAdapter` is intentionally not pulled into the primary `prebid-core.js` entry point (where most shared code under `/src` ends up).  the reason for this is some user bundles do not use analytics adapters (probably most) so for those that do not it would just be dead code; and those that _do_ use analytics adapters only include one of them. so the only way you would end up with multiple `AnalyticsAdapter` code blocks is if you included multiple analytics adapters in your bundle which you will most likely never do. you can see this exception intentionally addressed [here](https://github.com/prebid/Prebid.js/blob/master/webpack.conf.js#L10) in the webpack config.

as for `adlooxAnalyticsAdapter`, prebid modules should never import code from another prebid module to prevent what you're seeing. there is actually a custom lint plugin that enforces this: https://github.com/prebid/Prebid.js/blob/master/plugins/eslint/validateImports.js#L25 but you can see [here](https://github.com/prebid/Prebid.js/blob/4183f5d8f0875098e3041b366394ce24c43493cd/modules/adlooxRtdProvider.js#L12) that the lint rule was disabled which allowed this to happen. so it's possible this is a bug (you'd have to dig into the PR and/or ask reviewers/submitter why this was allowed and if it was intentional).

even though modules can't directly import other modules using es6 imports it is possible for modules to have dependencies on other modules but it is handled through the module/submodule pattern (which came up years after the prebid module system was implemented so i don't necessarily think it's the greatest solution and kinda hacky). you can see an example of this with the userId module: https://github.com/prebid/Prebid.js/blob/d8282ecaa726a62b5a71b72b49394e7aa11409ae/modules/userId/index.js#L862 and here's a submodule depending on it: https://github.com/prebid/Prebid.js/blob/d8282ecaa726a62b5a71b72b49394e7aa11409ae/modules/imuIdSystem.js#L151
there are several userId submodules that depend on the userId module as well as other module/submodule relationships [defined here](https://github.com/prebid/Prebid.js/blob/master/modules/.submodules.json). while this does allow modules to depend on each other i'm not a huge fan because: it's a custom-coded dependency that's hidden to tooling such as IDEs, it's resolved at runtime which is not ideal, and it relies on conventions such as updating that .submodules.json file which [the gulp build system uses](https://github.com/prebid/Prebid.js/blob/master/gulpHelpers.js#L61) which could introduce discrepancies keeping the file up-to-date with reality.

if the module/submodule issues are something you wanted to address during this refactor of webpack modules i think it could be beneficial, although i also understand how it might be out-of-scope.

**Comment by snapwich** [comment]
so it's true that there will be "dead code" for some users depending the combination of modules and/or features you choose to use. as you identified, some modules added or use shared util functions that really are only used in a one or few modules. this can be essentially solved by a publisher making their own prebid.js build from npm src, which many do. webpack performs tree-shaking to do dead code removal and if you are directly importing your modules using es6 syntax (as you should if you're using prebid from npm) webpack should be able to determine code you're not using and remove it. i haven't tested how friendly prebid is for tree-shaking, but i assume this is a solved problem; and if it's not then the bug fix should be making prebid friendly to webpack tree-shaking.

this doesn't work for users that need to build prebid.js through concatenation though. it doesn't need to be concatenation but the requirement for these users is that they can make a custom prebid.js builds quickly (i.e. not run a webpack build which is extremely slow). an example would be a user requesting the bundle `/prebid.js?modules=rubiconBidAdapter,rubiconAnalyticsAdapter` and it being created by the server instantly. right now approaches like this are handled by concatenating the individual webpack entry-points together. some tooling does this as part of a build process, not an http request, so http2 isn't necessary a solution either.

the last way in which prebid is customized is through features. it's pretty obvious now that if you use prebid.js but are not doing video, you are including a lot of video code in the prebid-core.js that you are not going to use. so it's essentially "dead code". solutions to this have been discussed in a few different threads. here's one i see that is still open: https://github.com/prebid/Prebid.js/issues/6361

these are the three use cases i think you should be considering when refactoring the build process.

**Comment by patmmccann** [comment]
fwiw, using multiple analytics adapters is not uncommon
