### ISSUE TITLE
Rubicon adapter does not call addBidResponse for adUnits with no bid.

### ISSUE THREAD

**Issue by nanek** [prebid/Prebid.js#798]
## Type of issue
Bug report / Prebid 14 / Rubicon adaptor

## Description
If one adUnit in rubicon returns an error, prebid will reach its timeout. This delays the loading of all ads.

The rubicon `FL_TIER_MAPPED` event does not appear to be called for an adUnit if the fastlane.json response for that adUnit is something similar to:

````
    "ads": [
        {
            "error_code": "10",
            "impression_id": "--",
            "reason": "floor-not-met",
            "status": "no-ads"
        }
    ],
````

The callback from https://github.com/prebid/Prebid.js/blob/master/src/adapters/rubicon.js#L307 is not called for this adUnit, so no bidResponse is added for this adUnit. pbjs.allBidsAvailable() remains false. This forces the the page to wait for the prebid timeout to fire.

**Comment by mkendall07** [comment]
@snapwich

**Comment by snapwich** [comment]
@nanek I'm going to talk with the team about the best way to solve this, unfortunately it might require listening to many of the error events which aren't currently exposed to prebid from the Fastlane library.  However, this issue is avoided entirely in the 'rubiconLite' adapter as it has no coupling to the Fastlane library if you want to give that a try.

@mkendall07 if we do come up with a fix, do you have a method for it to be applied?  Currently this adapter is no longer in master since it was replaced with 'rubiconLite' so we can't make the changes there.  Would creating a `0.14.x` hotfix branch off the `0.14.0` tagged commit be the correct route you think?

**Comment by mkendall07** [comment]
@snapwich 
We do generally do hotfixes for older tags. We would recommend users to upgrade to 0.15.0 as soon as it's released (this week) and use that instead.

**Comment by nanek** [comment]
This works for me. Thanks.
