### ISSUE TITLE
Move PBjs Release NPM Publish Job to AWS 

### ISSUE THREAD

**Issue by ChrisHuie** [prebid/Prebid.js#7983]
We have explored moving the job which publishes new versions of Prebid to npm and updates the needed cdn links. The main blocker for this previously has been storing the needed environment variables and not exposing them with our CircleCI setup. After talking with Demerio we feel there is likely a way to store these variables securely and still have the publish job run inside an AWS container.

**Comment by dgirardi** [comment]
To be clear, it does not have to be AWS. I am not familiar with CircleCI but I bet we could something like set up a github repo with locked down permission and link it to its own CircleCI environment with sideloaded credentials.

**Comment by dgirardi** [comment]
This is how I plan to approach this (tagging @bretg, @mkendall07, @ChrisHuie):

1. Create a "releaser" repo which exposes scripts that automate the release. This consists of everything in https://github.com/prebid/Prebid.js/blob/master/RELEASE_SCHEDULE.md + "npm publish" (currently part of the Appnexus Jenkins job). 
2. Include the build output in the files published to npm, which will make it also available through jsdelivr. This should allow the rest of the Appnexus job to be done without building Prebid.
3. Restrict write permissions to the releaser repo only to a group that should have write permissions to npm (prebid-core? do we need a new group?)
4. Set up CircleCI for the releaser, with all the required credentials (browserstack; npm; coveralls?) and configure it to not run on fork PRs and/or not pass secrets to them (CircleCI has options for both). Credentials in the CircleCI UI are write-only, so this should make them only available to who can write to the repo (it's not enough to have access to CircleCI itself). This seems the easiest option (compared to say AWS or GitHub workflows) because the work to run tests on it (part of the release) has already been done.

The release process then would look like: commit a new version number to some manifest file in this new repo, push, and let CircleCI run it. (Or, if we feel like we are ready for it, just completely automate it and have it run weekly).

**Comment by bretg** [comment]
Thanks for taking a cut at this @dgirardi . How would it support major release updates and periods where we support legacy branches?

Our github teams are hard to manage because we don't know which company various handles belong to and whether they're still active with that company. I did a little cleanup, removing a couple of groups and removing some Magniters who've moved on. If we choose to use 'Core' or 'PrebidJS Reviewers', we ought to review as a group. In general, I think we should have a very small new group.

**Comment by mkendall07** [comment]
Generally LGTM on the approach, assuming that we've done the proper vetting on the security around the keys in the circleCi environment. 

If we wanted to do this somewhere else (github, aws) I'd point out that the circleCI config is merely a thin wrapper over various gulp / webpack commands and it shouldn't in theory be hard to replicate the pipeline into another system with tests. 

Agree with Bret on reviewing who should have access and in favor of having a smaller new group for this as well.
