### ISSUE TITLE
Cannot install node packages

### ISSUE THREAD

**Issue by umutkirgoz** [prebid/Prebid.js#8046]
## Description
It was working without any problem in 4.x versions.
When I tried to install npm packages, with npm install command it returns **_ERESOLVE unable to resolve dependency tree_**
I am using this to build custom prebid package

## Steps to reproduce
```
cd /tmp
mkdir -p prebid
cd prebid
npm init -y
npm install prebid.js
cd /tmp/prebid/node_modules/prebid.js
npm install
```

### Expected results
Install required packages without any error

### Actual results
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: prebid.js@5.20.3
npm ERR! Found: @wdio/cli@7.16.14
npm ERR! node_modules/@wdio/cli
npm ERR!   dev @wdio/cli@"^7.5.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @wdio/cli@"^6.0.1" from @wdio/browserstack-service@6.12.1
npm ERR! node_modules/@wdio/browserstack-service
npm ERR!   dev @wdio/browserstack-service@"^6.1.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

## Platform details
Prebid.JS >= 5.x
Node Version v14.17.5
npm version v8.3.1

**Comment by dgirardi** [comment]
@umutkirgoz npm does behave as you describe, but why would you need to run `npm install` from within `node_modules`? this part will install Prebid as a dependency and it works without problems:

```
cd /tmp
mkdir -p prebid
cd prebid
npm init -y
npm install prebid.js
```

**Comment by umutkirgoz** [comment]
I need to do this, because I am building custom prebid by using command seen below:
`gulp build --modules=path/to/your/list-of-modules.json`

**Comment by dgirardi** [comment]
To build a standalone prebid, it's better to check out the repository rather than installing it from npm:

https://github.com/prebid/Prebid.js#install and  https://github.com/prebid/Prebid.js#build-optimization (also has instructions on how to build it within your own npm project, if standalone is not what you want)

Specific versions are tagged in git so that you can for example do `git checkout 6.11.0`.

I believe the reason you are seeing a difference is that npm changed how it caches dependencies somewhere around node version 12 (it used to store `node_modules` under each package, which would make your commands here work - but now it prefers to "flatten" them under the project root).

**Comment by umutkirgoz** [comment]
I changed my working style as you described

**Comment by dgirardi** [comment]
I can build 6.16.0 with node 16 - but not 18. None of the wdio dependencies are strictly necessary for the build (they are used in testing). Maybe we should move them under `optionalDependencies`, but I don't think we'll try to do that retroactively for 6.16. You could work around the issue by manually removing them from `package.json`.
