### ISSUE TITLE
Districtm DMX endpoint error P6.20.0

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#8383]
In P6.20.0 i'm getting Server call for districtmDMX failed.  I've noticed it in the last 4-5 days, so not 100% sure if its to do with P6.20.0 or a different server down or something

**Comment by patmmccann** [comment]
@maphe could you take a look? 

We're unable to reproduce on Cafemedia sites

**Comment by maphe** [comment]
The DMX exchange is turned off in favor of the Sharethrough exchange. I'd recommend contacting the Sharethrough Account Management team for more information.

Meanwhile we'll handle dismantling the DMX adapter altogether as well as removing it from the documentation. @patmmccann is there any process to be aware of to achieve that? or is it just a couple or regular PRs that drops all the concerned files? (since it might be considered a breaking change)

**Comment by spormeon** [comment]
@maphe I'm also constantly getting a user sync warning for districtm adapter, is the gvl id right?  

"args": {
        "type": "WARNING",
        "arguments": {
            "0": "User sync not allowed for districtm"
        }
    },

**Comment by maphe** [comment]
@spormeon the DistrictM adapter is deprecated altogether, it won't do anything as the endpoints have been turned off and migrated to Sharethrough.

What Publisher are your integrating DMX for? I can ask a Sharethrough Account Manager to reach out to them to let them know the migration process

**Comment by spormeon** [comment]
i've already got contact at sharethrough, just no ones told me anything about All districtm adapters being depreciated

**Comment by patmmccann** [comment]
Are both districtm endpoints deprecated?

**Comment by spormeon** [comment]
the districtm one works for me, its only appnexus in the end but i've been told by someone on email that they are both gone at the end of April.
