### ISSUE TITLE
Remove adlive bid adapter

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#8394]
## Type of issue
adapter removal

## Description
Docs issue https://github.com/prebid/prebid.github.io/issues/3731 requests the removal of the adlive bid adapter from the PBJS 7.0 branch. Keep the 'adlivetech' bidder please.

@chuie - can you take care of the code update please -- I'll take care of the docs update.

**Comment by patmmccann** [comment]
#7796 for linkage

**Comment by ChrisHuie** [comment]
@bretg @patmmccann so just reviewed this. Adlive js file is currently not in the repo. It was one of the adapters taken out as we moved to 5.0. I believe the issue was `adomain`. They then added an alias md file for Adllivetech. However, there is no code to alias since neither has a corresponding js file. We can move off the 7.0 board probably since this isn't breaking.
