### ISSUE TITLE
Prebid stopping lazy load ads from showing

### ISSUE THREAD

**Issue by tedrand** [prebid/Prebid.js#842]
## Type of issue

question

## Description

An ad is being loaded with the jquery_lazyload library, when the user scrolls to the bottom of the page. If Prebid/AiH is active on the page, lazy-loaded ad does not function.

**Comment by matthewlane** [comment]
[This page](http://prebid.org/dev-docs/examples/adunit-refresh.html) contains an example of refreshing individual ad units which may be helpful in a scrolling setup. If this doesn't apply, do you have a test page or JSFiddle we can look at?

**Comment by tedrand** [comment]
http://chat.georgia.sportswar.com/message_board/ugadawgrun/

The lazy-load ads are 728x90 and show up in the middle, and at the bottom of the forum.

Thanks for looking into this

**Comment by tedrand** [comment]
Solved. Removed:

`googletag.cmd.push(function() {
    googletag.pubads().disableInitialLoad()
});`

**Comment by kpingel** [comment]
I had the same problem, but realized after removing that line to `disableInitialLoad`, the timing was off with our header bidding. Using the Chrome Extension "Headerbid Expert" showed that DFP was firing immediately, and not waiting for Prebid to return bids, so we were rarely getting winning bids before the ads loaded with DFP.

From what I can tell, Prebid uses `disableInitialLoad` to hold the DFP push so that it can request bids, and then uses `googletag.pubads().refresh();` after it has everything it needs from the bidders or it's hit the timeout that was set. So it seems lazyloaded ads are also being affected by `disableInitialLoad`, but then are not visible when the google ads refresh so they never actually load.

I resolved this by adding `googletag.pubads().refresh();` to the end of my lazyloaded script. However, to avoid refreshing ALL ads again, you need to target just the individual slot that's come into view. Google provides some guidelines for doing this: https://support.google.com/dfp_premium/answer/4578089#slotRefresh

Good luck!
