### ISSUE TITLE
Question: MaxRequestsPerOrigin Intended Functionality

### ISSUE THREAD

**Issue by ccorbo** [prebid/Prebid.js#8649]
## Type of issue
Question

## Description
Opening this issue to get clarification around the `maxRequestsPerOrigin` config, and what the intended behavior is. The [runIfOriginHasCapacity](https://github.com/prebid/Prebid.js/blob/3fd3b5dca5dcc3fcd9f3c949e8e1a3238ea6b836/src/auction.js#L280) function seems to evaluated once for the entire batch of bid requests issued in a single requestBids statement, rather than for each individual bid request. So from what I can tell, it can only possibly work if you are making separate calls to pbjs.requestBids for each bid request.

Just looking to get the intended behavior out of the `maxRequestsPerOrigin` function, it doesn't seem to work like the documentation specifies.

**Comment by dgirardi** [comment]
The documentation does say that the unit of control is the auction:

> Prebid.js will queue auctions that would cause requests to a specific origin to exceed that limit.

I am not sure doing it any other way would make sense; if a single auction needs to make a ton of requests to the same endpoint, Prebid might as well let the browser queue manage that. (In effect what would probably happen is that some requests would time out). In contrast, delaying a whole auction makes sense because it allows the crowded endpoint to participate in it fairly - otherwise it would only be able to bid on whichever auctions happened to start first.

**Comment by muuki88** [comment]
I have a small follow up. We are currently investigating if this feature queues requests for our Prebid Server because we configure empty bids for all server side adapters.

I image the queuing thinks that there a "number of bidders" requests going to Prebid Server, thus queuing. However I'm not 100%

Indicators are
* Warnings from prebid.js
* Higher timeouts on Prebid Server
