### ISSUE TITLE
Prebid in the cloud ?

### ISSUE THREAD

**Issue by Deimos01** [prebid/Prebid.js#870]
Hello guys,

It is now one year since i've started using this amazing project.
Actually, i reading more and more article about header bidding solution in the cloud (server-side).

http://adage.com/article/digital/amazon-moves-poach-publishers-header-bidding/306985/

Will this project evolve in this way ?
I think it could be a good solution to reduce latency, prevent a bunch of client side errors, conflicts ...
I already know the answer to that question but does this project need a lot of changes to be running on a server ?

Thank you,

**Comment by mercuryyy** [comment]
@Deimos01  

to answer your question someone actually commented this 
"What does it different then selling in RTB? 
Header bidding is "client side RTB" and there is also the classical server side RTB thats is working today. publishes that doesn't have in house the ability to sell in RTB ( from the server) are working with the SSP that enable this."

which is 100% accurate, why do we see much better results tho using client side RTB vs using SSP's we get access to teir 1 inventory while RTB done by the SSP does not. also because the networks in your prebid get to actually call the clients browser the prices jumps up vs using server side.

The only way this would work is if google decides to unify everything and create a server side header bidding container that will be adopted and accepted as a standard by all networks and this they wont pay the same a client side because 3rd party advertisers dont get a chance to physically call on the users browser and google will never do that :)

**Comment by tedrand** [comment]
@Deimos01 in addition to @mercuryyy comments, if server-to-server does become the popular thing to do, the API for that will in no way resemble a header-bidding wrapper.

**Comment by mkendall07** [comment]
Prebid in the cloud or server 2 server is a bit different than traditional header bidding, as others have mentioned. Ideally, Prebid would support other S2S "Header Bidding" solutions but I don't foresee the project itself functioning in that capacity in the short term. Longer term it might be a possibility, depending on the industry trends, however, in it's current state it's not optimized to run on a server.
