### ISSUE TITLE
Targeting logic silently ignores bids that have sizes not supported by `sizeConfig`

### ISSUE THREAD

**Issue by Jordanjscott** [prebid/Prebid.js#8887]
## Type of issue
I've just set up Minute Media as another bidder, however nothing runs as GAM is not being sent their KV.

## Description
I have MM set up the same as other partners, and have had the ID's checked by the AM, all good there. All other partners are showing KV's in GAM and serving. Bids are being received, but no KV being sent in the request to GAM. 

### Expected results

For MM key values to be sent to GAM. 

## Platform details
v. 7.0.0

**Comment by patmmccann** [comment]
Please provide a test page

**Comment by Jordanjscott** [comment]
> Please provide a test page
> 
> just confirming the issue:
> 
> 'I am a publisher and I receive bids from MM bid adapter but I never see gam targeting set for them'

That's correct yeah, I have test mode on the mobile mpu (mpu1-m), so bids should always be received on this unit: 

https://www.thelondoneconomic.com/wrapper-test-page/

**Comment by dgirardi** [comment]
I did some debugging and I think what's happening is that bids from minutemedia are being silently ignored because they have a size that is not supported by `sizeConfig`:

![image](https://user-images.githubusercontent.com/10151381/187293638-dd3e5e6d-900a-45e1-8919-9ee1d61a945e.png)

What made this tricky to track down is that we only check against `sizeConfig` when we set up targeting; the bid is a normal (and possibly winning) bid otherwise:

https://github.com/prebid/Prebid.js/blob/ece711e73114e73a452541edcaa073281f8cd801/src/targeting.js#L452

I'm not sure if this makes sense or if it's a bug. (@bretg or @patmmccann  does it make sense that a bid may win if you call renderAd, but not if you call setTargetingForGpt?)  

For the time being, would you be able to update your `sizeConfig` to accept the sizes returned by minutemedia?

**Comment by dgirardi** [comment]
Actually, this may be a problem only when using minutemedia's "test mode", it appears to reply with predefined sizes and ignore what was requested? FYI @noamtzu

**Comment by noamtzu** [comment]
@dgirardi indeed. the sizes are predefined. the test mode it's only for 100% fill for integration purposes.

**Comment by patmmccann** [comment]
>  (@bretg or @patmmccann does it make sense that a bid may win if you call renderAd, but not if you call setTargetingForGpt?)

We should add sizeSupported filtering to the no adserver use case

**Comment by Jordanjscott** [comment]
It was the size missing from the config that wasn't sending bids to server. Added in now and it seems to work fine. Thanks @dgirardi !

**Comment by dgirardi** [comment]
Thanks for the update @Jordanjscott ! I'll keep this issue open because filtering out wrongly sized bids should not be done only for targeting. We should either:

1. not validate size on responses at all (we already do it for requests), or
2. reject bids with unsupported sizes before the auction ends (and probably do the same if you are using sizeMappingV2).

**Comment by dgirardi** [comment]
Agreed to go ahead with #2, bids of the wrong size should be rejected from the auction.

**Comment by patmmccann** [comment]
reopening for discussion with partial revert of 9013

**Comment by patmmccann** [comment]
@dgirardi on further consideration I think you are correct, if size enforcement is desired it should be a new feature request, not on this issue.
