### ISSUE TITLE
OpenX Adapter Not Working?

### ISSUE THREAD

**Issue by premesh** [prebid/Prebid.js#89]
Im not sure if this is because im using test tags ( adunit ids) that they setup for me but i never get any valid bids back. I debuged the adUnit coming back from the response and can see there is now property called "pub_rev" at all . see screenshot
![image](https://cloud.githubusercontent.com/assets/5246343/10811407/e92f8db8-7dc8-11e5-93d4-5e193419e6eb.png)

**Comment by mkendall07** [comment]
Hi @premesh,
OpenX should be working. You can email me directly (email is in my github commits) with your test page and I can take a look.

**Comment by BartVB** [comment]
As far as I know you need a different kind of account/permission to enable header bidding with OpenX. I'm told that you can't use normal publisher accounts with it.

**Comment by mkendall07** [comment]
Thanks for the info @BartVB 

@premesh  were you able to get this working?

**Comment by protonate** [comment]
Closing this, please reopen if there is new info to add.

**Comment by chrisevz1337** [comment]
@premesh - did you ever ascertain what the issue was here? I have a similar issue whereby we've been able to successfully configure three other SSP adapters, but I haven't been able to get a valid bid response back from OpenX yet, and I can't figure out what's causing it. We've had our account enabled for bidder activity - but no joy as of yet...

**Comment by premesh** [comment]
Sorry never got it working with prebid
