### ISSUE TITLE
DOMException: Failed to read the 'sessionStorage'

### ISSUE THREAD

**Issue by fasenderos** [prebid/Prebid.js#8934]
## Type of issue
Bug

## Description
Running `prebid.js` in a safe frame results in the following error

> DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document

I think the problem was introduced [here](https://github.com/prebid/Prebid.js/commit/da46bf2ebd96c47bff32a52d307b0f75ab4c87c1)

Modifying the `loadSession` function as below solves that problem
```
export function loadSession() {
  let storage = null;
  try {
    storage = window.sessionStorage;
  } catch (e) {}

  if (storage !== null) {
    let debugging = ctl;
    let config = null;
    try {
      config = storage.getItem(DEBUG_KEY);
    } catch (e) {}
    if (config !== null) {
      // just make sure the module runs; it will take care of parsing the config (and disabling itself if necessary)
      debugging.enable();
    }
  }
}
```

**Comment by robertrmartinez** [comment]
@dgirardi @fasenderos Should we also make a similar change to the debugging module files as well?

Guess since it is "debugging only mode" not a huge deal, but if you are testing something and load the lib in incognito or something it may throw errors?

https://github.com/prebid/Prebid.js/blob/master/modules/debugging/debugging.js#L34
