### ISSUE TITLE
how to add sonobi adaptor ?

### ISSUE THREAD

**Issue by HDaghash** [prebid/Prebid.js#90]
can some one help us to intgrate with sonobi using prebid.js
Thanks in advance

**Comment by prebid** [comment]
Hi @HDaghash, apologies on the delay. We've been focused on Analytics and AOL/Sovrn adaptors in the past weeks. Adding a new bidder adaptor is quite easy and has been documented here: http://prebid.org/dev-docs/bidder-adaptor.html. Do you think you'd need help on getting this in?

**Comment by HDaghash** [comment]
yes we read it but we have some problem  could  you please provide us with sonobi example .
many thanks

**Comment by KevinTBN** [comment]
We have a very close relationship with Sonobi and we have talked to them about this and they said you can do it with their older ad server platform (the name escapes me) and it will not work with their "morpheus" platform.  As a result you do get excluded from a lot of their high-end bids which would drive their performance down.  also since they require that the $4+ lineitems for Sonobi be at a priority 4 - it makes it so they have an unfair advantage on bidding for impressions (which could have been sold at a higher amount to someone else).

**Comment by Heray** [comment]
Thanks @KevinTBN! Could you help us understand why morpheus won't work with prebidjs? (If it's just returning a price and a creative identifier back) Or is it more of a policy issue?

**Comment by KevinTBN** [comment]
It is more of a Policy issue with Sonobi. because of the agreements Sonobi has with there Ad providers it causes some contractual issues with them (at least this is what our rep is telling us)

**Comment by rberner** [comment]
Hello, I'm an engineer at Sonobi. Thanks for providing some feedback, @kevinTBN. We are currently exploring options on how we can provide all the needed functionality of our platform from within a solution like prebid. As mentioned above, our implementation does require a sponsorship line item in order to properly activate our marketplace. If anyone would like additional details, please don't hesitate to contact me directly and I will make sure you are introduced to the right people on our side.
