### ISSUE TITLE
Changes to canonical url being preferred for site.page

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#9185]
As discussed in #9152

- canonical looses its query string params
- Some pubs have the wrong canonical on their page for some reason

cc: @jsadwith @nllerandi 

Proposal, ignore canonical being in pub config, append query string by default

**Comment by dgirardi** [comment]
Would it make sense to have a config toggle that gives preference to the page's location over canonicalUrl? 

```
pbjs.setConfig({
   useCanonicalURL: false
})
```

**Comment by dgirardi** [comment]
Or should the logic be `refererInfo.page = getConfig('pageUrl') || refererInfo.location || refererInfo.canonicalUrl` ?

**Comment by nllerandi3lift** [comment]
> Consensus is that the referer logic should be updated to `refererInfo.page = getConfig('pageUrl') || refererInfo.location || refererInfo.canonicalUrl`.

Was it `refererInfo.location` or `refererInfo.topmostLocation` as the second step?

**Comment by dgirardi** [comment]
@nllerandi3lift, consensus is that canonical should be used only if prebid is unable to determine the top frame location. That translates to `refererInfo.location` as the second step. Yes, I am regretting my name choices on those.

**Comment by dgirardi** [comment]
For a bit of history:

 - #6591 made it so that `setConfig({pageUrl})` overrides `refererInfo.canonicalUrl`
 - #8450 introduced `refererInfo.page = refererInfo.canonicalUrl || window.top.location` as an attempt to solve #5637 (adapters not picking up the `pageUrl` config)

It's unclear if the first was an attempt to solve the same problem with the expectation that adapters would pick up `canonicalUrl`. @mmoschovas, do you remember the context?

**Comment by mmoschovas** [comment]
@dgirardi Sorry, I dont really remember the context here. @bretg may remember the reason for this change

**Comment by bretg** [comment]
Sorry, wasn't really involved in this effort. FWIW, I think it's too many URL choices.

**Comment by patmmccann** [comment]
fixed in #9241
