### ISSUE TITLE
Native targeting keys are not set for bids that use ORTB native responses

### ISSUE THREAD

**Issue by JulieLorin** [prebid/Prebid.js#9246]
## Type of issue
I think this is a bug (but I may have missed something on native changes on Prebid)

## Description
We tried to implement IX on native, but it seems that since #8853, Index Exchange adapter returns a naive bid response with openrtb format instead of Prebid native.

### Actual results
Index exchange native bid response : 
![image](https://user-images.githubusercontent.com/635021/201982850-45fa59e5-36d4-4fc7-90a6-b9d36011171b.png)

### Expected results
Regular native bid response : 
![image](https://user-images.githubusercontent.com/635021/201983059-6c2d9044-f24f-4d13-a61c-0b1c32fa6a3c.png)

Is this an issue with IX bid adapter or should we adapt to handle this kind of native response ?

**Comment by dgirardi** [comment]
ORTB and the Prebid-proprietary formats should be interchangeable, but it's of course possible that something was overlooked. Could you expand on what you mean by "adapt"?

**Comment by dgirardi** [comment]
@JulieLorin - the difference in targeting is indeed a bug. It does not sound like that's the only thing you are missing though; are you working the bid response object directly for rendering (from `bidsBackHandler`?) 

The change in format comes from #8086. Part of the strategy is to translate ORTB native responses to the Prebid format so that it would maintain compatibility with existing creatives, but we were assuming that those would be interfacing through the same `postMessage` protocol that PUC uses. So the translation is not available to you if you're dealing with bid responses directly - which is something we can fix. 

However,  the long term plan is to allow ORTB in the adunit definition itself, and at that point it won't necessarily be true that a given native response can always be translated into the prebid native format. This may or may not matter in your case (if you control the adunit definitions you can choose to keep them in the prebid format and continue to get prebid responses back).

**Comment by JulieLorin** [comment]
> @JulieLorin - the difference in targeting is indeed a bug. It does not sound like that's the only thing you are missing though; are you working the bid response object directly for rendering (from `bidsBackHandler`?)

Yes exactly, we are directly using the bid object from `bidsBackHandler` (and more precisely the native property for native rendering)

> The change in format comes from #8086. Part of the strategy is to translate ORTB native responses to the Prebid format so that it would maintain compatibility with existing creatives, but we were assuming that those would be interfacing through the same `postMessage` protocol that PUC uses. So the translation is not available to you if you're dealing with bid responses directly - which is something we can fix.

Thanks for the link to the PR, I was not aware of this transition, and we are indeed not using the same protocol as PUB uses. 
I think it's always nice to have backward compatibility for this of course, especially as it seems all the conversion work has been done, but instead of being added on the bid response native property, it is added only at the time of the postMessage response to retrieve all assets (I think that was the point of https://github.com/prebid/Prebid.js/pull/8086/files#r920200871)

I can try to create a pull request that adds the parameters at bid response level instead of at the time of the post message.

**Comment by patmmccann** [comment]
@ix-prebid-development @ix-prebid-development
