### ISSUE TITLE
how to load all bids together?

### ISSUE THREAD

**Issue by sinairofe** [prebid/Prebid.js#929]
## Description

pubmatic had less time to bid, beacuse they loaded much later than the other bidders

**Comment by troels-jakobsen** [comment]
Using the header bidding expert plugin, I find that this is a general problem for Pubmatic across a number of sites.

I see two options:

1. Pubmatic requests are somehow systematically delayed due to some bug in prebid.js
2. The Pubmatic adapter is flawed

My money is on option 2.

**Comment by ialex** [comment]
@sinairofe i think the problem is how their adaptor is written taking a look at their adaptor really fast i see they create an iframe then load a script from their site to get the bids (i guess this make the requests to their server), where other adaptors just make the http requests the server directly to collect the bids.

Rubicon used to also load a JS file to collect bids but they remove that and changed the adaptor to make the calls directly to improve performance.

**Comment by mkendall07** [comment]
I think pubmatic still loads an external JS file - that is why bidding may be delayed. We are requiring all adapters going forward in prebid 1.0 to do direct demand requests (no library) so it should help after updating the adapter that way.
