### ISSUE TITLE
Cannot get floorprice of multi-format adUnit when mediaType = "*"

### ISSUE THREAD

**Issue by renebaudisch** [prebid/Prebid.js#9303]
## Type of issue
This seems to be a bug but maybe I just got and do it completely wrong...

## Description
A bidadapter calling getFloor on a multi-format aduntit will default to "*" but using a star for mediaType will fail even a match exists.

## Steps to reproduce
We're using this config (don't care about the variables please):

<img width="495" alt="image" src="https://user-images.githubusercontent.com/15980546/204807316-cf46255d-f765-4d54-bfed-b48e4ce11f71.png">

And this callback for the field "bidder":

<img width="395" alt="image" src="https://user-images.githubusercontent.com/15980546/204836198-8988df36-fbd2-481b-92c9-7b17cd2b5fc3.png">

As we have banner|*|* and video|*|* we have a definition for all besides native.
But every call with mediaType "*" has just these possibleMatches:

<img width="217" alt="image" src="https://user-images.githubusercontent.com/15980546/204835793-8a22834f-c197-4e5e-ad37-774449cb225b.png">

As there is no default and no match containing a type this results in NaN.

## Test page
You can find the adunit "mrec" using multi-format e.g. here:
https://m.bild.de/unterhaltung/tv/tv/promi-big-brother-findet-menderes-in-der-garage-die-grosse-liebe-82092404.bildMobile.html

But you need to make sure, that you're emulating a mobile device.

### Expected results
The defined floor should be returned as defined. 
I don't know if this is possible by passing "*" since every type should might have a different floor.

### Actual results
Wrong or no floor price is set on the bid request

## Platform details
PBJS 7.24

## Other information
Strangely passing mediaType = undefined solves the problem and defaults to banner...
This is done by e.g. adfBidAdapter.js

**Comment by patmmccann** [comment]
you need a rule for *|*|* in your config

**Comment by renebaudisch** [comment]
Why? There is a banner|*|* and video|*|* and the bidrequest is for banner and video, so it should be covered. There is no single price for *|*|* matching banner ne video, and also it would be the same as setting a default.

**Comment by patmmccann** [comment]
Perhaps @robertrmartinez can word it more elegantly than i, but the way i understand it is if a bidder calls the getFloor function they need to specify a mediatype and in this case some bidders eg magnite who would only answer on video may choose to request the floor for video, others that don't support video might request the floor for banner, and others might prefer a multiformat floor, which you simply don't provide.

**Comment by patmmccann** [comment]
That's an interesting trick to send different bidders different floors though, does that work?

**Comment by renebaudisch** [comment]
> 

understand, then the documentation is maybe a little bit misleading, as we have 4 bidders that run into getting no floor because they do not specify with floor but just calling getFloor and let it fall back to default "*". But that in this case doesn't mean, apply floors for all given adTypes and sizes, it means apply a floor that is set for all adTypes, let's call it an adUnitFloor.

**Comment by patmmccann** [comment]
You can have ad unit code as one of your dimensions and specify star on the mediatype

**Comment by renebaudisch** [comment]
AdUnitCode is added automatically, there is no need for that and adUnit + * will again result in what I called adUnitFloor, a floorprice valid for all adtype together available on the adUnit. But still I think some bidadapters have been coded without that knowledge and are expecting a star to apply all single floors available for a single type.

About that trick, it just results in floors for adtype `banner`. 
The composed `getFirstMatchingFloor` function will get this:
![image](https://user-images.githubusercontent.com/15980546/205003953-c017d5a8-ba30-4a34-ab83-8fbb7260e55d.png)
Because mediaType is undefined `fieldMatchingFunctions.mediaType` defaults it to `banner`.

So that's way for banner bidders only.

**Comment by renebaudisch** [comment]
I forwarded this information to the bidders we are working with and who uses "*" in their setup or do not pass an object. 
I really think it would be helpful updating the docs...

**Comment by robertrmartinez** [comment]
Yeah so the idea here is that this `bidRequest` has two possible floor values
One for `banner`
One for `video`

But any `bidResponse` that comes back can only have one `mediaType`.

So for this example, as a bidder what floor should be passed to them since only one can at a time?

The module checks the adUnit's mediaType and if there is only one mediaType it will infer use it, but if it has multiple mediaTypes, then it can't just guess which one to use.

For example, If we just pass the `banner` floor, which presumedly is much smaller, they potentially may return a `bidResponse` for `video` which does not meet the floor.

And the opposite case if we send them the `video` floor, and on their server they have a banner bid, but because it is below the video floor passed in, they simply do not send it back to prebid, when in reality it would pass the banner floor.

So, bid adapters who handle multi-format ads, can call `getFloor` for both mediaTypes, and if the floors are different, they can send both perhaps, or do an average, whatever they want to do.

Or, with the `*` case, the publisher or floor provider can have some floor that does a weighted average perhaps.

Or for your case, perhaps when it is multiformat, you want the banner floor passed to bidders if they pass `*`, so you can just mimic your banner floors into your `*` floors.

But yeah, perhaps this should be explained a bit more in getFloor docuementation.

**Comment by renebaudisch** [comment]
> But yeah, perhaps this should be explained a bit more in getFloor docuementation.

:heart:
