### ISSUE TITLE
Promise.race Error on UserId module on latest version 7.36.0

### ISSUE THREAD

**Issue by ialex** [prebid/Prebid.js#9551]
## Type of issue

Bug

## Description

I found out that in the current PrebidJS version (at the time of writing this, v7.36.0), and in combination with Angular a GreedyPromise.race doesnt return a Promise causing Type Error and preventing proper prebid execution. 

Line where it happens
https://github.com/prebid/Prebid.js/blob/master/modules/userId/index.js#L514

Error
```
prebid.js:formatted:31225 Uncaught TypeError: k.Z.race(...).finally is not a function
    at f (prebid.js:formatted:31225:57)
    at $ (prebid.js:formatted:31238:29)
    at prebid.js:formatted:31656:25
    at 2695 (prebid.js:formatted:31689:18)
    at r (prebid.js:formatted:9253:28)
    at prebid.js:formatted:31798:17
    at r.O (prebid.js:formatted:9273:37)
    at prebid.js:formatted:31802:15
    at n (prebid.js:formatted:9338:37)
    at prebid.js:formatted:30676:57
    at prebid.js:formatted:33305:6
```

## Steps to reproduce

I can provide a test page where this happens but its behind login 

### Expected results
Prebids runs
## Platform details
Prebid 7.36.0 Chrome

## Other information
Similar to issue #9422

**Comment by dgirardi** [comment]
Could you try this - _before_ loading either Angular or Prebid?

```
<script>
window.pbjs = window.pbjs || {};
window.pbjs.Promise = window.Promise;
</script>
```

If that doesn't work, how would we go about getting access to the test page?

**Comment by dgirardi** [comment]
Confirmed off line that the above fixes the issue. Tagging @javiermarinros since you might be also affected at some point - apparently it's not enough to reimplement `resolve`  / `reject` as in #9426, although that might depend on the zone.js' version. I'd much rather bypass its monkey-patching than reimplement _everything_ in Promise.

**Comment by javiermarinros** [comment]
@dgirardi snippet fixes the issue, but anyway this error is kind of obscure and hard to track, and it looks like can affect potentially all Angular users. Do you have any idea how to better fix this or at least communicate it to Angular developers?

**Comment by dgirardi** [comment]
@javiermarinros  Maybe we do need to assume that Promise is broken and just not rely on it from Prebid. We could provide an independent reimplementation as an optional module and suggest it as something you'd want if you use Angular? 
I'm not familiar with why angular thinks it's necessary to patch it, but I'm guessing that bypassing it is not a true fix - something's still likely to break if you attempt to use a promise you get from Prebid where angular expects one of theirs.

**Comment by javiermarinros** [comment]
The Promise class is monkey-patched by Zone.js, [a library that patches all browser asynchronous methods](https://medium.com/reverse-engineering-angular/angular-deep-dive-zone-js-how-does-it-monkey-patches-various-apis-9cc1c7fcc321) (e.g: `setTimeout`, `addEventListener`,...), and notifies Angular every time one of this method has been fired in order to allow the framework run its change detection algorithm and update the view.

As for a possible solution, I'm not too familiar with Prebid core to be really useful. What is the purpose of using the custom GreedyPromise solution? Based on the documentation, I assume it has to do with performance, but I'm not sure if there is any improvement by simply running callbacks synchronously when the promise has already been fulfilled or rejected.

**Comment by dgirardi** [comment]
It is performance, and you are correct, it's not better than running callbacks synchronously because that's exactly what it does :) 
After giving up reusing the OG `Promise` (https://github.com/prebid/Prebid.js/pull/9558), I think it's not too bad in terms of how much code it is, so that's probably the best solution.
