### ISSUE TITLE
Prebid 8 - Remove AOL Bid Adapter

### ISSUE THREAD

**Issue by ChrisHuie** [prebid/Prebid.js#9592]
On Prebid 7 release yahoo team expressed their desire to remove the AOL bid adapter in the next major version. This issue is to confirm and track removing AOL adapter

**Comment by slimkrazy** [comment]
Hey @ChrisHuie  - We're going to have a internal chat about this. I'll get back to you asap.

**Comment by slimkrazy** [comment]
Hey @ChrisHuie  - what is the planned release date for PB8?

**Comment by patmmccann** [comment]
Early June 2023

**Comment by slimkrazy** [comment]
Hey @patmmccann / @ChrisHuie,

Just to confirm: The PB team see removal of bid adapters as breaking API changes, thus only do this as part of major version releases, correct?

**Comment by patmmccann** [comment]
correct, but you can make an adapter not hit your endpoint (provide no bids)  between versions.

**Comment by patmmccann** [comment]
@radubarbos please give us a final go or no go on deleting this adapter.

**Comment by patmmccann** [comment]
assuming we won't delete and closing as won't do, lmk if you guys change your mind

**Comment by slimkrazy** [comment]
Hey @patmmccann  - good timing here. Had a meeting yesterday with the Product team and we should have an answer for you after this long weekend, so I'd say by Wednesday.

They also raised another point that I want to run past you guys. We have to rebrand the yahoossp bid adapter (the reason is outlined [here](https://www.adweek.com/programmatic/yahoo-shutters-ssp-and-narrows-focus-on-ad-buyers/)). Getting this into PB 8.0 would be good. I think we can do it like this, please correct me if I'm wrong:

- Rename all the modules to use the new branding (Yahoo Advertising)
- Add an alias to the newly branded module for yahoossp

Or would you say that we can add the alias to the current 7.x branch and drop it for 8.x?
