### ISSUE TITLE
Setting Prebid Default for TID to off in prebid 8

### ISSUE THREAD

**Issue by jtollestrup** [prebid/Prebid.js#9781]
Due to privacy concerns regarding back end stitching of data utilizing the TID, the publisher committee has elected to flip the default in Prebid for TID to off and allow each publisher to make their individual determination to turn this feature on.

**Comment by dgirardi** [comment]
Is this referring to `imp.ext.tid`, `source.tid`, or both? 

For `source.tid` this needs, in general, an update to every adapter. `imp.ext.tid` would be easier to toggle centrally.

**Comment by jtollestrup** [comment]
Both.

**Comment by jtollestrup** [comment]
We met with Prebid legal today and they strongly recommended that this feature be defaulted off.

**Comment by patmmccann** [comment]
TBD: should the config toggle be in activity control or its own top level flag?

**Comment by dgirardi** [comment]
Many adapters include auctionId as part of their payload, separately from `source.tid`. This is especially common for those that do not use ORTB, but not limited to them. What should we do about that? replace them with a random UUID?

**Comment by dgirardi** [comment]
Here's an alternative proposal:

 - refactor every usage of `auctionId` that is clearly interchangeable with `source.tid` as discussed above;
 - when it's not clear (see below), leave it untouched, and:
 - when transaction ID are turned off, add a check on outgoing network requests, and forcibly cancel requests that contain auctionId.

This way, when TIDs are turned on, adapters will continue to work as if nothing changed; when they are turned off, we can have good confidence that data won't be leaked.

Otherwise we don't have a good way to deal with a large number of adapters that use a pattern like this:

https://github.com/prebid/Prebid.js/blob/bc665aa7b6320c15df5553240d65a907837c162c/modules/proxistoreBidAdapter.js#L26-L30

in this case, it's clear that `transactionId` is meant to be the TID and should be protected by the new control we are introducing for 8. But we do not know what to do with `auctionId` - removing it has a good chance to unnecessarily break it.

I'll add that IMO it's too early to turn TIDs off by default - there's a good chance that it will break so many adapters that it the vast majority of publishers will be de-facto forced to turn them back on again.

**Comment by dgirardi** [comment]
The enforcement on network requests could also be made into a module - if we are OK with the default being "TID are off, but we don't know if they are actually being sent out".
