### ISSUE TITLE
[Video Module] `videoError` does not trigger for videojs when using videojs-contrib-ads

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#9894]
## Type of issue
Question:  Has the error event been tested in videojs as we are seeing nothing happening on videojs errors
## Description
videojs errors nothing shown in event 'videoError'

## Steps to reproduce
when an error is reported in console from videojs for error 4, nothing is shown for the event 'videoError'

![DevTools_-_127_0_0_1_5502_prebid_VideoDemo_DemoSite_pages_NewVideoModuleNeuwoGolf1_html](https://user-images.githubusercontent.com/8503167/235919828-e682b989-d89c-4de4-b55b-67cf5de6f71d.png)

nothing in console from  the event:

![NewVideoModuleNeuwoGolf1_html_—_Prebid_Publishers__Workspace_](https://user-images.githubusercontent.com/8503167/235920037-5c9824ac-b327-41e8-9878-5b34982aed8c.png)

## Test page
pretty impossible as the error is random and you could sit there for an hour trying to get it , like i have

### Expected results
onEvent 'videoError should display the error to console

### Actual results
only videojs is displaying the error in console, not the "video module"

## Platform details
chrome, mac, Prebid V 7.47.0

**Comment by spormeon** [comment]
let me try the way you got it there, i'm trying after setConfig & after que.push

**Comment by spormeon** [comment]
@dgirardi can you try with this demo, it falls down when usng GAM and playlist by the looks of it, of which i'm using both.  If you just take off the 4 from the first playlist mp4, the error throws but not caught by prebid/ video module:

https://cdn.adysis.com/VideoDemo/DemoSite/pages/videomoduleerrornotcaught.html

ultimately what I'm trying to do is "catch the error" and move to the next playlist item on error detection, which i just cant seem to do with this not catching it:

**Comment by dgirardi** [comment]
The issue is an interaction with videojs-contrib-ads:

https://github.com/videojs/videojs-contrib-ads/blob/703eeddbc3236b9b115422025df9193f5b7f7190/src/redispatch.js#L14-L16

it registers an `'error'` event handler that stops its propagation; if that is loaded before Prebid, their handler will run before our handler, and stop ours from ever seeing the error.

I am out of my depth here, not sure why contrib-ads is doing what it does and what we should be doing to accommodate it (@karimMourra  ?)

With your particular setup we can work around it by not waiting for the player to be ready before registering the event handler, i.e. change this:

https://github.com/prebid/Prebid.js/blob/bc6aa84ace332b582e9f125b4c8fa014e503e7a8/modules/videojsVideoProvider.js#L215-L217

to 

```javascript
registerListeners(type, callback, payload); 
```


however, we probably want to work properly when loading after contrib-ads, as I don't think there's any guarantee that we can get to the player first.

**Comment by dgirardi** [comment]
I believe contrib-ads is doing that to rename 'error' into `aderror`, which we are not listening to. Not sure if this is related:

https://github.com/prebid/Prebid.js/blob/bc6aa84ace332b582e9f125b4c8fa014e503e7a8/modules/videojsVideoProvider.js#L627-L628

`adserror` is [deprecated](http://videojs.github.io/videojs-contrib-ads/integrator/api.html). However, it does not look like `aderror` is a simple replacement:

![image](https://github.com/prebid/Prebid.js/assets/10151381/95e249fc-5bed-48f6-9e4a-d4c0c76fc3b2)

**Comment by spormeon** [comment]
ok, so i'm basically stuffed for catching and moving playlist to next on error, until get a fix i guess? luckily i've got a "block" list i build, so its catching by hand in the mean time and ading to "block list"

**Comment by dgirardi** [comment]
You should be able to unblock yourself using the player API directly, something like

```javascript
pbjs.onEvent('videoSetupComplete', e => {
    const player = videojs('player');
    ['ad', 'content'].forEach(prefix => {
        player.on(`${prefix}error`, () => {
            player.playlist.next();
        });
    })
```

although the details will vary depending on your setup.

**Comment by karimMourra** [comment]
The versions that were tested against when building and testing the video.js adapter are as follows:
videojs: 7.20.2
videojs-contrib-ads: 6.9.0
videojs-ima: 1.11.0

The reason I point this out is because of the screenshot indicating `imaAdError` is undefined.

**Comment by spormeon** [comment]
confirm those are the versions used on the test page

**Comment by spormeon** [comment]
@dgirardi I tried your "tweak" on videojsVideoProvider.js changing to: registerListeners(type, callback, payload); 
PV7.48.0

![DevTools_-_cdn_adysis_com_VideoDemo_DemoSite_pages_playlistUIvertical_html](https://github.com/prebid/Prebid.js/assets/8503167/8579f877-9feb-439d-ae88-d18360d3f697)

I'll see if I can hook into that now and do what I'm after, but prob not a "permanant method" as its not really going to help any others/ make it "simple" for others

**Comment by dgirardi** [comment]
@karimMourra my approach to fix this would be to brute-force it and map the prebid `videoError` event to *each one* of the videojs events: `error`, `aderror`, `contenterror` (without contrib-ads it's going to use the first one, but it looks to always be one of the others otherwise).

However, I am worried about other events that may not map cleanly, and I don't understand the logic for the renaming. From my testing it looks like pausing an ad triggers videojs `pause` and not `adpause` for example. What do you think?

**Comment by patmmccann** [comment]
Appears ready for dev if we listen for the additional event?
