### ISSUE TITLE
prebid.js 0-19-0 Javascript code contains non-standard characters

### ISSUE THREAD

**Issue by headerbidding** [prebid/Prebid.js#994]
0-19-0 prebid.js breaks the javascript code and I get a "Invalid or unexpected token" error.

**Comment by mkendall07** [comment]
@headerbidding 
I can't reproduce this issue.

**Comment by headerbidding** [comment]
Error was caused by using a text editor that dropped "text containing characters that cannot be represented in the file’s character set”  from the javascript code.

**Comment by mkendall07** [comment]
@headerbidding 
Sorry for all the hassle. Glad you figured it out finally.

**Comment by headerbidding** [comment]
Is it allowed in Javascript to have non-standard characters?
Up to Version 18, running the prebid.js javascript through a text editor has not been a problem.

**Comment by headerbidding** [comment]
The exact character that broke the code for my html editor (Microsoft Expression Web) was this one:
�

It is part of this sequence:
w=["	\n�\f\r Â áš€á Žâ€€â€�â€‚â€ƒ","â€„â€…â€†â€‡â€ˆâ€‰â€Šâ€¯â�Ÿã€€\

I am suspicious that the code may be corrupted...

Note: the character "�" does not display correctly here. It is the circle with arrow (male sign) ♂ symbol.

**Comment by headerbidding** [comment]
After further testing, I found that this issue does not occur if I only choose the appnexus adapter.

**Comment by mkendall07** [comment]
This is a complex topic, but to summarize, no a JS string can contain any UTF-16 encoded character. This is a superset of ASCII.

The reason why this is occurring in the build now is because of a change we made to include some polyfills for IE. The polyfill contains this source code: https://github.com/es-shims/es5-shim/blob/v3.4.0/es5-shim.js#L1304-L1324 (spec: http://es5.github.io/#WhiteSpace )
 
The characters that seem strange, are representations of whitespace / tabs. These get converted down to UTF-8 representations with the Uglify JS plugin. 

This all seems valid to me.
