### ISSUE TITLE
Feature Request: add support for fetch endpoints to topics module

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#9981]
## Type of issue
Feature Request

## Description
Topics from the fetch headers may be more richly populated than topics gathered in the iframe. This feature request is to add support for an endpoint that reflects the topics it saw on a fetch api call headers instead of an injected frame doing a post message. [Docs
](https://developer.chrome.com/docs/privacy-sandbox/topics/#use-headers-to-access-and-observe-topics) [Demo](https://topics-fetch-demo.glitch.me/)

**Comment by pm-harshad-mane** [comment]
The Topics are generated as per the user's browsing history so I am assuming that the generated Topics for a user will not change drastically within a day.  
The Fetch end-point for Topics needs a server-side infrastructure. 
To save the infra cost, we can avoid frequent calls to the end-points by caching the response on the client side in the first-party local storage. 
The Topics module can take care of managing the cache and calling the SSP Fetch endpoints when the cache is stale. 
@patmmccann please share your thoughts.

**Comment by patmmccann** [comment]
> The Topics are generated as per the user's browsing history so I am assuming that the generated Topics for a user will not change drastically within a day.

They change weekly

> the Topics module can take care of managing the cache and calling the SSP Fetch endpoints when the cache is stale.

this seems wise, assuming it is configurable and subject to publisher device access consent, like sharedid module

**Comment by github-kevin-margueritte** [comment]
Hello,

As you may already know, Chrome 115 is now available and comes with the Topics API. I haven't closely followed the implementation of the iframe in Prebid and the limitations that led to the current proposal. However, I see some drawbacks with the solution proposed by Google.

As suggested in this ticket, it would be great to have an additional option on the adapter to use Fetch instead of XHR to send user topics during the bid request (this option could be implemented [here](https://github.com/prebid/Prebid.js/blob/master/src/adapters/bidderFactory.js#L464)). Furthermore, granting the adtech actor full control of topics and allowing them to update the classifier by returning the HTTP header `Browsing-Topics: ?1` seems to be a more flexible and performant method, as recommended by Google. Are there any plans to implement this solution, and is there any way we can help with it?

**Comment by patmmccann** [comment]
@github-kevin-margueritte this comment is a dupe of another issue, #9980, recode ajax to fetch and allow topics to be appended

**Comment by remysaissy** [comment]
Follow-up on https://github.com/prebid/Prebid.js/pull/10124#discussion_r1269721510 conversation since I understand it is closer to a feature request than an expected PR comment.
@jlquaccia, yes either 0 or all by default would make more sense to me in my opinion.

**Comment by jlquaccia** [comment]
@remysaissy yea since this module would require a custom config setup for each participating bidder/ssp that wants to utilize it, I think the default at this point in time should be 0.

**Comment by dgirardi** [comment]
@jlquaccia , does https://github.com/prebid/Prebid.js/pull/10124 close this?

**Comment by jlquaccia** [comment]
@dgirardi, yes https://github.com/prebid/Prebid.js/pull/10124 closes this ticket :+1:
